### ISSUE TITLE
Cannot set/change Address's City on w101

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1016]
#### Which are the steps to reproduce?
* edit first address of https://w101.metasfresh.com:8443/window/123/2156451
* try changing the City
* when opening the address again the city is "OR".

### What is the expected or desired behavior?
Changing city name shall be persisted.

**Comment by metas-lc** [comment]
IT
1. go to BPartner window, select one and go to location tab
2. add a new address or update an existing one:
3. set country: United States, add a region like "OR"
(region field does not appear right away, you have to get out and open location again)
4. save, then open location again and set a country like United Kingdom
(region is set to United Kingdom, but not in database)
=> notice in the database, that the regionname is still on "OR"
5. open location again and change the city name. Close and open location again
=> city name is saved correctly OK
.
we could have 2 followups: (checking)
one to set regionname to null when you change the country 
and one to show/hide region directly if you set a country that has/doesn't have regions
