### ISSUE TITLE
Adding a new price for a product not possible 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1017]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Adding a new price for a product is not possible bc the price list version field is read-only:

![2018-08-01 10_10_24-metasfresh](https://user-images.githubusercontent.com/18696715/43509655-882ef240-9573-11e8-83a6-62c4cba5080f.png)

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Price list version must be editable.

**Comment by metas-dh** [comment]
same problem in bpartner tab: bpartner field is readonly

**Comment by metas-ts** [comment]
this one is related to https://github.com/metasfresh/metasfresh/issues/4426

**Comment by metasnw** [comment]
IT
- OK: price list version selectable when adding product price
- OK: partner selectable when adding partner relation to product

@metas-ts any cases for regression?

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-dh** [comment]
checked with metas-ts: nothing else to test, closing.
