### ISSUE TITLE
Error opening translation windows

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#1025]
### Is this a bug or feature request?
bug

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

opening translation windows:
* working fine from menu: OK
* working fine using referenced docs: OK

**Comment by metas-ts** [comment]
FYI, :cherries: picked https://github.com/metasfresh/metasfresh-webui-api/issues/1025 to the `release` branch
