### ISSUE TITLE
Window layout API shall provide text multilineText and multilineTextLines properties

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1032]
### Is this a bug or feature request?
Required for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1908

### Configuration
![image](https://user-images.githubusercontent.com/1244701/44846029-db872700-ac57-11e8-9ad5-0ac3a1676eec.png)

**Comment by teosarca** [comment]
Frontend:
![image](https://user-images.githubusercontent.com/1244701/44847595-a9c48f00-ac5c-11e8-8e3a-887e7db077d5.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. multilineText and multilineTextLines properties can be set: OK
=> set it for Request Tab in bpartner window:

![2018-09-13 11_38_58-decloudit001](https://user-images.githubusercontent.com/18696715/45480886-6254fd00-b74a-11e8-8757-a5ae98960494.png)



2. multilineText and multilineTextLines correctly taken for Frontend: OK
=> checked Request Tab in bpartner window:

![2018-09-13 11_42_17-metasfresh](https://user-images.githubusercontent.com/18696715/45480897-697c0b00-b74a-11e8-8b07-1da24a2a42c0.png)
