### ISSUE TITLE
API for "About" action in webui 

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#1033]
Backend Issue for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1945

**Comment by teosarca** [comment]
### Note to IT:
* regression: check Swing's record Info popup (click on bottom right corner of any standard window to see created/updated + change log entries).

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* WebUI part to be tested in metasfresh/metasfresh-webui-frontend#1945
* regression: Swing's record Info popup still working fine, correct info for created/updated + change log entries: OK

**Comment by metas-dh** [comment]
see IT dokus in me03 tasks: OK; Swing's record Info popup still working fine (checked once more)
