### ISSUE TITLE
Advanced tooltip support

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#1037]
### Is this a bug or feature request?
FR
related to  https://github.com/metasfresh/metasfresh-webui-frontend/issues/1952

Note to IT: 
* this issue can be ITed when metasfresh/metasfresh-webui-frontend#1952 is ready
* to test this issue, you can test https://github.com/metasfresh/metasfresh/issues/4558 and https://github.com/metasfresh/metasfresh/issues/4556

**Comment by metas-dh** [comment]
see ITs for metasfresh/metasfresh#4558 and metasfresh/metasfresh#4556.

**Comment by metas-dh** [comment]
works in general, see  metasfresh/metasfresh#4558, remaining issue to be done in metasfresh/metasfresh#4556. closing this one.
