### ISSUE TITLE
Use user language for messages and errors in Forgot Password feature

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1038]
### Is this a bug or feature request?
FR
### What is the current behavior?
Atm not all messages and errors you receive when using the Forgot Password feature are matching the user's language for whom you use the feature.

see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1878#issuecomment-406918987 ff. for info as well.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Messages and errors shall consider the resp. user language.

**Comment by teosarca** [comment]
note to IT: test it after https://github.com/metasfresh/metasfresh-webui-frontend/issues/1958

**Comment by metas-dh** [comment]
Results of IT1
tested in release

User language is correcly considered in Forgot Password feature:
* user had de_DE set: Accept-Language set in Frontend: de_DE: OK
* user had en_US set: Accept-Language set in Frontend: en_US: OK
