### ISSUE TITLE
Provide error msg with proper info when new PW does not match criteria

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1039]
### Is this a bug or feature request?
FR
### What is the current behavior?
Atm when you try setting a new PW, in Forgot PW feature, and it does not match the criteria, e.g. is too short, then you just get "Verbindungsproblem" displayed, but no info about the PW being too short.

see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1878#issuecomment-418295487
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Error msg shall give proper info so the user can adapt his new PW accordingly.

**Comment by teosarca** [comment]
frontend issue, shall be solved by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1957
