### ISSUE TITLE
Open PDF from Printing Queue stopped working

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh-webui-api#1043]
### Is this a bug or feature request?
Bug
### What is the current behavior?
See https://github.com/metasfresh/metasfresh/issues/4532
### What is the expected or desired behavior?
The process shall work

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* check process from grid view: working fine, PDF opens: OK
* check process from single view: working fine, ODF opens: OK

**Comment by metas-ts** [comment]
:cherries: picked to `release`
