### ISSUE TITLE
Sometimes there are no available DocActions for Sales Orders

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1046]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
Don't know. Happens only sometimes.

### What is the expected or desired behavior?
Shall always work.

### Note to IT
regression: check Swing DocActions. Shall be OK

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* DocActions were always available in Sales Order window (WebUI), also in other windows like e.g. shipment or invoice: OK
* checked DocActions in Swing (Complete / Reactivate / Void / Reverse - Correct / Close) for e.g. sales order or invoice: all worked fine: OK
=> had a problem when trying to reverse an invoice with customized document number, see https://github.com/metasfresh/metasfresh/issues/4575#issuecomment-422810514, but afais from the error msg that is related to the document number, not DocActions
