### ISSUE TITLE
Allow purchase disposition from sales order only for drafted sales orders

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#1047]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The purchase disposition overlay dialog in the wayUI is available for drafted and completed sales orders

### What is the expected or desired behavior?

i shall be available only for drafted orders;
in all other cases, the user may go to the purchase disposition window.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Allow purchase disposition from sales order only for drafted sales orders:
* action is only available as long as the order is in status: Draft: **OK**
* action can be called sev. times, for sev. orderlines, vendor infos / qties are correct: **OK**
* purchase disposition is created / updated correctly: **OK**

had a problem during IT, after overlay for purchase dispo closed: => #1048
