### ISSUE TITLE
Time switches when setting Preparation Date-Time

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#1064]
### Is this a bug or feature request?
Bug
frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1933

### What is the current behavior?
When having a different Timezone on Client and recording a date time field in metasfresh (e.g. Sales Order Preparation Date+Time) then the Time switches to different time after save. This should not happen.
![image](https://user-images.githubusercontent.com/13365687/46478007-51008d00-c7ec-11e8-860f-1c458df1f28e.png)

#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The Date+Time shall not switch.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Set time zone in browser to America/Denver (-8hrs)
2. Created sales order, with date & time promised & preparation date & time today, 23:59: OK

![2018-10-23 13_34_24-metasfresh](https://user-images.githubusercontent.com/18696715/47358038-ce9a1900-d685-11e8-9e7e-488584ca90f7.png)

3. Changed the date promised to 26.10., and the preparation date & time to 26.10., 18:59: 
=> changes are saved and displayed correctly: OK

![2018-10-23 13_35_07-metasfresh](https://user-images.githubusercontent.com/18696715/47358082-f25d5f00-d685-11e8-80c4-394a027583bd.png)

4. Refreshed the page: time is changed for both dates: afais that's NOK, should remain the same:

![2018-10-23 13_35_23-metasfresh](https://user-images.githubusercontent.com/18696715/47358280-90e9c000-d686-11e8-9872-55072607b990.png)

**Comment by metas-dh** [comment]
checked again:
* time is set correctly in the order, in the db
* when you open the sales order once more, the time is displayed correctly as well, only after refresh it is displayed wrong => frontend issue
