### ISSUE TITLE
Don't show KPIs if the ElasticSearch system is disabled

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1066]
### What is the expected or desired behavior?
If the Elasticsearch is disabled (i.e. sysconfig `de.metas.elasticsearch.PostKpiEvents` is `N`) then don't show the KPIs and Target Indicators in webui dashboard because it's is pointless.
More, the console is flooded with fail to connect to elastic search exceptions.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* have Elasticsearch  disabled (i.e. sysconfig de.metas.elasticsearch.PostKpiEvents is N): =>  KPIs and Target Indicators are not shown in webui dashboard, it just shows the "metasfresh" logo: OK
* the console is not flooded with fail to connect to elastic search exceptions anymore: OK
