### ISSUE TITLE
Attributes Filter in Picking shall work on load as before

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#1067]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When opening Picking Terminal --> Picking --> select Picking Slot --> Open HU Selection Window

The "Filter by: Consider Attributes" is set to "Y", but the Filter is not applied (active). If you apply, then the Handling Units are not shown that should be shown. If you take out the Consider Attributes Flag and Apply, also no Handling Units are shown.

#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Please Fix. When the HU Editor Panel is opened the Filter shall be applied on load and show the Handling Units that fit for that Filtering.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Attributes Filter in Picking is applied on load in Picking Terminal: OK
2. Handling Units shown in HU Editor fit the attribute filter: OK
3. when you clear the filter, all HUs are shown: OK
4. when you reapply the filter, then only the HUs fitting the attribute are shown once more: OK

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh-webui-api/issues/1067 to `release`
