### ISSUE TITLE
Cannot add orderline using "Add new", error when selecting product

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1068]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When trying to add an orderline using `Add new`, you get an error.
#### Which are the steps to reproduce?
1. Use `Add new`in e.g. sales order
2. Select a product, e.g. Convenience Salat: when trying to select it, you get

```
Error: ERROR: column "repoid" does...
Server error
ERROR: column "repoid" does not exist Position: 451 SQL: SELECT t.C_Tax_ID, t.validFrom, t.To_Country_ID , t.C_TaxCategory_ID FROM C_Tax t LEFT JOIN M_ProductPrice pp ON pp.C_TaxCategory_ID = t.C_TaxCategory_ID LEFT JOIN M_Pricelist_Version plv on pp.M_Pricelist_Version_ID = plv.M_Pricelist_Version_ID LEFT JOIN M_Pricelist pl on plv.M_Pricelist_ID = pl.M_Pricelist_ID LEFT JOIN C_Charge c ON c.C_TaxCategory_ID = t.C_TaxCategory_ID WHERE t.validFrom < ? AND t.isActive='Y' AND t.C_Country_ID = CountryId(repoId=101) AND t.To_Country_ID = 101 AND t.C_TaxCategory_ID = pp.C_TaxCategory_ID AND pp.M_Product_ID = ? AND (t.AD_Org_ID=0 OR t.AD_Org_ID=1000000) ORDER BY t.AD_Org_ID DESC, t.To_Country_ID, t.validFrom DESC SQL params: [2018-10-16 00:00:00.0, 2005572]
```

3. Add an orderline for the same product using batch entry: works fine, OK
### What is the expected or desired behavior?
Shall work.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* adding orderline using `Add new` working fine, line is created correctly (for both existing product from master data & newly created product): OK
* adding orderline using batch entry working fine as well (for both existing product from master data & newly created product): OK

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh-webui-api/issues/1068 to `release`
