### ISSUE TITLE
View: have a way to define if views support opening row details

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1069]
### Is this a bug or feature request?
FR
required for https://github.com/metasfresh/metasfresh/issues/4577

### What is the current behavior?
On a non-modal view, if you double click on a row, frontend tries to open it.
In some cases this will produce a 404 because simply that row is not a document.
e.g. https://w101.metasfresh.com:8443/window/540485

### What is the expected or desired behavior?
Backend shall be able to tell frontend if the view supports opening rows.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* double clicked on different rows in non-modal view, window/540485: no errors, 404s etc.: OK
