### ISSUE TITLE
Unpick action not working

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1075]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When trying to use the Unpick action, the HU remains picked, no error, nothing in console.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* unpick action: HU is not displayed in picking slot anymore: OK
* HU Editor shows this same HU as available for picking again, can be picked once more: OK

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh-webui-api/issues/1075 to `release`
