### ISSUE TITLE
Cannot create a new sales order because "DeliveryViaRule is not set"

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1076]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
try to create a new sales order.
The order remains in "red".

### What is the expected or desired behavior?
shall work nicely ;)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

creating a new sales order does not cause any errors ec., indicator bar shows it's saved correctly: OK
