### ISSUE TITLE
Material tracking ID not selectable in purchase orderline attributes

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1085]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Cannot select a Material tracking ID not selectable in purchase orderline attributes, although there is one existing for the resp. vendor and the product. Works in Swing.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by teosarca** [comment]
@metas-dh  @metas-ts  isn't this related or duplicate of https://github.com/metasfresh/metasfresh/issues/4737?

**Comment by metas-ts** [comment]
right. so i guess we can close this one; feel free to reopen
