### ISSUE TITLE
Login: Show a user friendly error when user or password is empty

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1094]
### Is this a bug or feature request?
FR

#### Which are the steps to reproduce?
Try login with empty user or empty password.
You get a very ugly error message:
![image](https://user-images.githubusercontent.com/1244701/47780126-71e0d300-dd03-11e8-9c24-0eaf4cb560d6.png)

### What is the expected or desired behavior?
Show a user friendly error message

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* try login without setting ID: "Erforderliche Felder ausfüllen: Nutzer-ID/Login" : OK
* try login without setting PW: "Erforderliche Felder ausfüllen: Kennwort": OK

=> always in base language, de_DE bc user is not logged in at this point
