### ISSUE TITLE
Document filters: consider empty strings as no filters

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1102]
This issue is a (temporary) workaround for https://github.com/metasfresh/metasfresh-webui-frontend/issues/2040.

**Comment by teosarca** [comment]
Note to IT: the case described on https://github.com/metasfresh/metasfresh-webui-frontend/issues/2040 shall work

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

case described on metasfresh/metasfresh-webui-frontend#2040 working fine: OK

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh-webui-api/commit/3886e805e43106ac99408a0f433bf7b3ef48edf0 to `release`
