### ISSUE TITLE
Migration Script Endpoint Improvement

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-api#1108]
### Is this a bug or feature request?
* Bug/ FR
Followup for https://github.com/metasfresh/metasfresh-webui-api/issues/1072

### What is the current behavior?
( taken from the IT of #1072)
 * Execute endpoint 
/rest/api/dev/migrationScriptsLogger/scripts/{filename}
getScript
* Set a filename ( e.g. the current file) without the folders ( e.g.  	
5506420_migration_2018-11-13_postgresql.sql)
 * => NOK: Error respone: 
![image](https://user-images.githubusercontent.com/16001442/48493446-80b3a380-e834-11e8-82a6-fe34eaa37a22.png)

* The same thing is happening for the 
/rest/api/dev/migrationScriptsLogger/scripts/{filename}
deleteScript

* The problem is that the " .sql"  part is somehow cut and the filename is no longer valid.
#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
* I should get/delete the file

**Comment by metas-rc** [comment]
The same thing is happening for the 
/rest/api/dev/migrationScriptsLogger/scripts/{filename}
deleteScript

**Comment by metas-ts** [comment]
# Dev-Test 

...pending (not yet sure how to test :blush: )

**Comment by metas-rc** [comment]
Talked with @metas-tc and an IT is not need. Closing it directly
