### ISSUE TITLE
webui frontend does nothing in latest chrome 

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1114]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
I am using latest chrome (e.g. Version 71.0.3578.80 (Official Build) (64-bit)).
When i try to open the webui i get "no connection"
Checking chrome's console i see that CORS errors related to "accept-language".

![image](https://user-images.githubusercontent.com/1244701/49732040-ec4b2e00-fc85-11e8-9d90-9a7edacb777d.png)

### What is the expected or desired behavior?
shall work

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* testing WebUI with Chrome Version 71.0.3578.80 (Offizieller Build) (64-Bit): no connection problems, working fine: OK
