### ISSUE TITLE
Introduce AD_Tab.AllowQuickInput

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1146]
### What is the expected or desired behavior?
If unchecked then no Quick input/Batch entry  button will be shown for given tab.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* AD_Tab.AllowQuickInput: if set to `Y`, then QuickInput/Batch entry button in e.g. sales order, c_orderline (AD_Tab_ID=187) is displayed and works: OK
* AD_Tab.AllowQuickInput: if set to `N`, then QuickInput/Batch entry button in e.g. sales order, c_orderline (AD_Tab_ID=187) is NOT displayed: OK

@teosarca => in e.g. AD_Tab_ID=187 AD_Tab.AllowQuickInput is called "Schnelleingabe **abschalten**", which means "**TurnOff** QuickInput", maybe we could change the name to  "Schnelleingabe **einschalten**"?

**Comment by metas-dh** [comment]
checked again: it's "Schnelleingabe **einschalten**" now: OK
