### ISSUE TITLE
Products proposal: Action to delete a product price from price list

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1150]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
* open an draft order
* click on `Products Proposal` action
* select some rows and call "Delete action" => price shall be deleted from price list (i.e. M_ProductPrice table) and also from view
* go to "More products" and bring some from base price list
* try to delete them => they shall be deleted from view

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new action `Delete` to delete selected row(s) from Customer Proposal List: OK
* Parm Window explicitly asks the user if she/he really wants to delete: OK
* `Delete` action in Products Proposal, for products from original pricelist:
  
     * products are deleted from view: OK
     * prices are deleted from price list (i.e. M_ProductPrice table): OK
     * works the same for products that were taken from `More products` (=> base pricelist) AND saved to the original pricelist: OK
* products that were taken from `More products` (=> base pricelist, just taken from pricelist, not saved yet!):
  
     * products are deleted from view: OK
     * prices are NOT deleted from base price list (i.e. M_ProductPrice table): OK
