### ISSUE TITLE
Products Proposal: consider campaign price

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1152]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
Products Proposal list called from Sales Order shall consider the campaign price too.
i.e.
* have yes-no column called AP(Aktionpreise)/CP(campain price) which is checked if the campaign price was used
* consider the campaign price, but only if is less the price list's price

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Campaign price is displayed in Produts Proposal (1st modal):
* displayed with indicator:Y : OK
* only displayed when CP < list price: OK

question:
 in 2nd modal, `More products`, the Campaign price is not displayed, but the price from pricelist: when that one is selected, the Campaign price is taken and displayed in the 1st modal nevertheless: => i think this is OK, but don't we need some info for the user, that there is a campaign price which will be set? not the one from pricelist which is displayed in `More products`?

**Comment by metas-dh** [comment]
checked remaining question with metas-mk: OK as it is
