### ISSUE TITLE
Product lookup performance improvements

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1167]
#### Sysconfig `de.metas.ui.web.window.descriptor.sql.ProductLookupDescriptor.DisableFullTextSearch`
Disables the "full text search" for Products lookup (that one that is used on order product batch entry).

#### Sysconfig `de.metas.ui.web.window.descriptor.LookupDescriptor.DefaultLookupSearchStartDelayMillis`
Advice frontend which shall be the delay after user typed something and backend to be contracted.

#### AD_Table.ACTriggerLength
* advices frontend about how many chars the search string shall be sent to backend
* backend will return empty result if the search string length is less that configured length
* if the configured length is less or equal to zero it shall be ignored

**Comment by metas-dh** [comment]
Results of IT
tested in customer db

* search only after entering the 3rd digit: OK
* takes ~1 sec or less for searching for the complete product no. ((1.09 sec) or when setting it digit by digit (1.01 sec): OK
