### ISSUE TITLE
webui server shall start even if something in picking terminal code fails

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#1180]
### What is the current behavior?
Atm, some picking terminal (v1) code is initialized when webui server starts.
If that code fails then the whole server is not starting.

#### Which are the steps to reproduce?
You as a tester (IT) cannot.

### What is the expected or desired behavior?
webui server shall start even if something in picking terminal v1 is fucked.

### Note to IT
You cannot test it, but, you can do regression.
Open the picking terminal v1. If it opens => OK!

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

regression:
* Picking Terminal v1 opened w/o errors: OK
* picking in  Picking Terminal v1 works fine (did basic picking of 1 HU for an orderline): OK

* problem itself cannot be tested, see above.
