### ISSUE TITLE
Results missing in batch entry dropdown

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1189]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Only 1 product with the resp. name is displayed in the batch entry dropdown, even though there are many more.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Results of all matching products shall be displayed.

**Comment by teosarca** [comment]
@metas-dh  closing this one because it looks like all tests were passed
