### ISSUE TITLE
HU received in manufacturing order cannot be selected for issueing in a second manufacturing order

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1190]
### Is this a bug or feature request?
Bug
### What is the current behavior?
A HU that was received in a manufacturing order cannot be selected for issueing in a second manufacturing order.
#### Which are the steps to reproduce?
BOM in BOM
1. Have 2 PP_Orders, e.g. one for Karotten gestückelt P002736 and one for Convenience Salat, P002737 (=> the Karotten are a component of the salad); make sure both have the same warehouse set
2. In the PP_Order for the Karotten, receive a HU and process
3. In the PP_Order for the Salat, select the Karotten and open the HU Selection to select HUs to issue: 
=> the HU you received earlier is not displayed, NOK
=> it works fine in Swing!

received HU:
![2019-04-24 09_09_14-Metasfresh](https://user-images.githubusercontent.com/18696715/56639337-bfb21480-6670-11e9-9972-ac667de4ef41.png)

WebUI:
![2019-04-24 09_07_43-Metasfresh](https://user-images.githubusercontent.com/18696715/56639352-c50f5f00-6670-11e9-8c24-3268235f8ceb.png)

Swing:
![2019-04-24 09_08_00-X2GO-dh-50-1556089054_stDLXDE_dp32@decloudit001](https://user-images.githubusercontent.com/18696715/56639369-d0628a80-6670-11e9-9933-647c3b47d728.png)

### What is the expected or desired behavior?
HU shall be displayed and can be selected for issueing in the 2nd PP_Order.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* produced ingredient P002736 in PP_Order:

![2019-05-02 13_19_29-Metasfresh](https://user-images.githubusercontent.com/18696715/57072392-d2b28d80-6cdd-11e9-990b-dd381ba9c3de.png)

* P002736 needed for producing P002737: the produced HU can be selected for issueing in PP_Order for P002737, same as purchased one (HU Selection window): **OK**

![2019-05-02 13_20_47-Metasfresh](https://user-images.githubusercontent.com/18696715/57072401-d80fd800-6cdd-11e9-93f6-6a030d3a0424.png)

* HUs can be selected as source HU, or issued directly: **OK**

(note: warehouse is the same for producing P002736 & P002737)

**Comment by metas-ts** [comment]
🍒 picked issue https://github.com/metasfresh/metasfresh-webui-api/issues/1190 to `release` branch
