### ISSUE TITLE
Empty Filter vs. Default Value in Window Filtering

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#143]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
When using Window Filters, then the initial behavior is that Flags are considered as null/ not set. As soon as you click a Flag filter then results are Filtered by FlagValue = 'Y'. When clicking off, everything is filtered by FlagValue = 'N' and the user has no single possibility to reset to null to not consider anymore.
#### Which are the steps to reproduce?
Try Filtering in Product Price Window.
### What is the expected or desired behavior?
Similar to ID Fields one should be able to switch off/ nullify the filter with some kind of 'X' (x in a circle) to empty the filtering criteria without resetting the whole window filter.
![image](https://cloud.githubusercontent.com/assets/13365687/23094574/d81b5c80-f5fb-11e6-93e1-ab04be9b7649.png)

**Comment by teosarca** [comment]
what about changing the checkbox filter to Yes/No/empty dropdown, like we do in swing?

**Comment by metas-mk** [comment]
Don't like that with a dropdown. But would be the info for backend what's needed, From user Interface, I would prefer something like this when a flag in not null. WDYT?
![image](https://cloud.githubusercontent.com/assets/13365687/23101973/97a5a1a6-f6a0-11e6-9aba-97188b7899cc.png)

**Comment by metas-mk** [comment]
Alternative have a flag input which can take and show 3 different status. 
a. Green + ticked = 'Y'
b. Grey + X = 'N'
c. Empty = null

**Comment by metas-mk** [comment]
Lets move on w/ Proposal A. (initialization possibility w/ circled X. @cadavre WDYT?

**Comment by metas-mk** [comment]
Moved further discussion to webui-frontend. closing here.

**Comment by cadavre** [comment]
Whao, never 've seen this. 😲 Please link to webui-frontend.

**Comment by metas-mk** [comment]
I believe that. But what other possibilities do you see to show the user which filters are set and which not? If we cannot show the user cannot see that she/ he is explicitly using a flag filter = 'N' because it could also just be [null] --> not set

**Comment by cadavre** [comment]
I definitely understand this – we need some additional state here for sure!

**Comment by teosarca** [comment]
Fontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/762
