### ISSUE TITLE
Remove deprecated REST API

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#148]
this is a followup of https://github.com/metasfresh/metasfresh-webui-frontend/issues/289

**Comment by teosarca** [comment]
Applying first step: "metasfresh.webui.debug.DisableDeprecatedRestAPI" shall be considered true by default.

**Comment by teosarca** [comment]
Note to IT: nothing to really test. pls pay attention while doing e2e.

**Comment by metas-dh** [comment]
last e2e in WebUI went fine; only problem (w/ adding new address entry) was fixed in the meantime
