### ISSUE TITLE
grid view websocket notifications: fullyChanged shall not be set when changedIds is set

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#151]
See: de.metas.ui.web.view.event.JSONDocumentViewChanges.JSONDocumentViewChanges(DocumentViewChanges)

Atm we are setting fullyChanged flag to true if changedIds is not empty.
We do this because we want to make #150 work until https://github.com/metasfresh/metasfresh-webui-frontend/issues/355 is implemented.

**Comment by teosarca** [comment]
see pull request #152

**Comment by teosarca** [comment]
Note to IT:

Test case 1.
* open receipt candidates
* receive some HUs & create the material receipt
* press DONE to go back to receipt candidates view (DON'T REFRESH)
* check the receipt candidate line: the quantities shall reflect the received HUs

Test case 2.
* open receipt candidates
* run the Korrectur quick actions (suppose you already received something on that line)
* reverse some receipts
* press DONE to go back to receipt candidates view (DON'T REFRESH)
* check the receipt candidate line: the quantities shall be updated

**Comment by metas-lc** [comment]
IT
Repeated testcase above:

1. create a new purchase order, add a product, complete
2. go to receipt candidates and receive some HUs (e.g. 4), press done
=> new receipt created
=> without refreshing, qty TU is updated to 4
3. receive 6 TUs
=> without refreshing, qty TU is updated to 10
4. receive 5 TUs
=> without refreshing, qty TU is updated to 15
5. receive 1 TU
=> without refreshing, qty TU is updated to 16
6. select Korrectur, reverse 2 receipts: the one with 4 and the one with 6
=> without refreshing, qty TU is updated to 6
7. reverse 1 receipt: the one with 1
=> without refreshing, qty TU is updated to 5
(while qtyTU was updated, moved qty was updated as well) OK
