### ISSUE TITLE
Have Letter Feature in Sales Order Window 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#178]
Have the letter feature from java client in generic windows at least in sales order window

### What is the expected or desired behavior?
1. go in any sales order
2. click letter
3. select a template
4. template text uses variables resolved from context
5. click print to receive PDF file

**Comment by metasnw** [comment]
as of now we have the feature like that for sending emails we just need "duplicate" and start a report instead of sending the mail

![image](https://user-images.githubusercontent.com/16079655/29354228-2a6e8bb2-826d-11e7-861f-7f885b9eb97b.png)

**Comment by teosarca** [comment]
NOTE: to be able to enable/disable this feature we need https://github.com/metasfresh/metasfresh-webui-api/issues/583

**Comment by teosarca** [comment]
note to IT: better test after frontend task is done: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1196

**Comment by metas-rc** [comment]
Results of IT

*OK:  The Letter feature is available for Sales Orders.
*OK: When oppening letter I can add some text, print preview or Create it
*OK: If I create a letter for a sales order, I can see a Record entry that is linked with the order.
*OK: The record entry contains an attachment with a PDF of my letter
*OK: If there is no boiler plate defined, there is no template button to choose from
*OK: If I add boiler plates, I can select one of them for the letter. The filter is added near the preview button
*OK: I can send as many letters as I wan for the same order. They are all stocked and accessible via Request.
