### ISSUE TITLE
Cleanup metasfresh-webui repository

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#179]
* remove metasfresh-webui-frontend because it's developed in https://github.com/metasfresh/metasfresh-webui-frontend
* remove metasfresh-webui-vaadin because it was an early days prototype, not working, not maintained
* move everything from metasfresh-webui-api to root

**Comment by metas-ts** [comment]
@teosarca  aggree..and maybe also rename the repo metasfresh-webui to metasfresh-webui-api?

**Comment by teosarca** [comment]
@metas-ts huha, i will leave that pleasure to you. Because it will affect  things like jenkins & stuff.

**Comment by teosarca** [comment]
I've removed the metasfresh-webui-vaadin and metasfresh-webui-frontend folders.
@metas-ts can you pls help me with:
* renaming the repository name
* moving everything from metasfresh-webui-api to "root"
?

**Comment by metas-ts** [comment]
@teosarca taking a look now

**Comment by teosarca** [comment]
danke

**Comment by teosarca** [comment]
checked and it works. we also had rollouts in meantime and everything is OK.
