### ISSUE TITLE
Fetch lookup values out-of-transaction

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#189]
### Is this a bug or feature request?
Bug

### What is the current behavior?
field lookup values are fetched using "thread inherited" transaction.

### What is the expected or desired behavior?
Use out-of-transaction.
Reason:
* lookup is called while loading a document => so we are running in a transaction
* if one of the lookups fails => the whole transaction fails

If we will load the lookups out-of-trx, then only fetching that value will fail and not the whole transaction.

**Comment by teosarca** [comment]
Note to IT: full webui regression needed

**Comment by metas-lc** [comment]
e2e was done. No bugs related were found
