### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#19]
Cache invalidation and reload when
a) master data changed
b) window, tab, fields and more changed
--> perhaps can be kept seperately to keep loading performance on top level.

**Comment by metas-rc** [comment]
I found another problem that seems to have the same cause.
Steps: 
* Go to invoice candidate, change its QtyToInvoice_Override ( e.g. from 100 to 200)
=> NOK: the rest of the qtys are not updated
* CHange it again now to 300
=> NOK: The rest of the qtys are updated to 200 (the old value) 
* If you change it again it will always update with the value that was set before.

**Comment by metas-dh** [comment]
problem with different docstatus in grid view / single view, sales order no. 759 on w101:

* grid view: status completed
* single view: status draft

**Comment by teosarca** [comment]
NOTE to integrator: only the commits from gh19webui branches are valid, i.e. those which are from 31.Oct or newer.
The older ones are garbage.

**Comment by teosarca** [comment]
NOTE to IT: full regression will be needed.
Also pls check again: https://github.com/metasfresh/metasfresh/issues/2074

**Comment by metasnw** [comment]
@teosarca 

> also pls check batch entries

do you mean quick order entry?

**Comment by teosarca** [comment]
@metasnw  yes, order quick entry but also in other places where we have it (invoice, empties return etc)

**Comment by metas-lc** [comment]
1. created follow-up for metas-rc's testcase https://github.com/metasfresh/metasfresh-webui-api/issues/807
> I found another problem that seems to have the same cause.
Steps:

    Go to invoice candidate, change its QtyToInvoice_Override ( e.g. from 100 to 200)
    => NOK: the rest of the qtys are not updated
    CHange it again now to 300
    => NOK: The rest of the qtys are updated to 200 (the old value)
    If you change it again it will always update with the value that was set before.

.

2. metas-dh's testcase works fine
> problem with different docstatus in grid view / single view, sales order no. 759 on w101:

    grid view: status completed
    single view: status draft
OK

3. receipt cands not being updated. Task: https://github.com/metasfresh/metasfresh-webui-api/issues/186
documented in task. Shall be fixed there  

4. didn't have to refresh page after creating requests in bpartner OK
5. didn't have to do cache reset after posting documents in swing OK
6.
