### ISSUE TITLE
mandatory fields in CU-TU subtab in product window

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#192]
### Is this a bug or feature request?
bug
### What is the current behavior?
you can add a M_HU_PI_Item_Product without validfrom, with qty 0 and infinite capacity on N
#### Which are the steps to reproduce?
1. go to product window, select a product
2. go to cu-tu allocation subtab
3. add new: add a packing instruction , press Done
=> nok: validfrom shall be mandatory. You should either select a qty >0, or set infinite capacity on Y 
### What is the expected or desired behavior?
you should get error messages to set valid from and qty/infinite capacity

this is a follow-up for https://github.com/metasfresh/metasfresh-webui/issues/171

**Comment by teosarca** [comment]
It's more a display issue. Shall be (partially) solved by https://github.com/metasfresh/metasfresh-webui-frontend/issues/437

**Comment by teosarca** [comment]
I think it's solved. Pls check it again.

**Comment by metas-rc** [comment]
Results of IT

* OK: ValidFrom is mandatory
* OK: It's mandatory to either set a qty or to check the flag IsInfiniteCapacity
