### ISSUE TITLE
Provide supportQuickInput flag to tab layout

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#201]

**Comment by metas-lc** [comment]
IT:
* bpartner, product, order tax (from order), pricelist, warehouse, payment, material receipt candidates, invoice candidates, shipment candidates, shipment, material receipt and invoice windows 
=>supportQuickInput is false on tabs
* order - orderline tab
=> supportQuickInput is true
(for now, if you try to select batch entry button, you get error "Batch entry is not available.")
