### ISSUE TITLE
HU Automatic Label Printing when received

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#209]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
There is no possibility to print/ reprint a processed HU.
#### Which are the steps to reproduce?
Process a material receipt in Handling Unit editor after Material Receipt.
### What is the expected or desired behavior?
When receiving an HU and this is then set to processed = Y and active, then automatically print the HU Label for material receipt on the local printer. Selected HU which is active/ processed are allowed to also print further copies via side action menu (new action/ process included there).
This is the label that shall be printed w/ 2 copies (screenshot from swing client but are talking about webUI above!)
![image](https://cloud.githubusercontent.com/assets/13365687/23578938/378e33b8-00e2-11e7-8113-91d7caff87a5.png)

**Comment by metas-ts** [comment]
We should be able to switch automatic printing on and off via `AD_SysConfig`
@teo if it's not to hard, we should also create a notification..i'll nag you about it when i get that far

**Comment by metas-ts** [comment]
what we need to do is what the process with `AD_Process_ID=540370` and value = `Wareneingangsetikett LU (Jasper)` does

**Comment by teosarca** [comment]
Btw, this might be related: https://github.com/metasfresh/metasfresh/issues/877

**Comment by metas-ts** [comment]
@teosarca thx for the hint, i'll check.
@metas-mk is it OK if we *always* print the label automatically? i mean, also for the swing client? if now, we could add an ad_Sysconfig for optionally switch it off for swing..

**Comment by metas-mk** [comment]
@metas-ts pls not for swing client atm. should avoid 2 moving targets. if users get used to webUI that way we can change on swing client accordingly later.

**Comment by metas-lc** [comment]
task was already tested. Moving to done
