### ISSUE TITLE
Print Material Receipt Document via Material Receipt Candidates Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#210]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Ther is no possibility to print the whole material receipt for a given material receipt candidate line.
#### Which are the steps to reproduce?
Create a purchase order and do Material receipts for the used Handling Units. Done. Back in Material Receipt Candidates, there is no action - not in action menu, nor inside action dropdown - to print the material receipt document.
### What is the expected or desired behavior?
Have an action to print the material receipt document manually per user interaction. Could also be the main action print icon.
Here what is meant w/ screenshot from swing client
![image](https://cloud.githubusercontent.com/assets/13365687/23578981/627efbb0-00e3-11e7-800f-f17112e90bcf.png)

**Comment by metas-ts** [comment]
@metas-mk so here (other than in #209  ) there shall just be a way to print if the user presses a button...but the print shall not be done automatically..right?

**Comment by metas-lc** [comment]
task was already tested. Moving to done

**Comment by metas-ts** [comment]
we need the "Material Receipt Document" to be printed with *two* copies, not one..
adding a SysConfig way of setting the number. Note that we also need https://github.com/metasfresh/metasfresh/issues/1240 for this to work

**Comment by metas-ts** [comment]
https://github.com/metasfresh/metasfresh/issues/1240 is now also integrated => moving the task back to "rollout"
