### ISSUE TITLE
HU assignment delete error when opening HU editor

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#231]
### Is this a bug or feature request?
bug

### What is the current behavior?
sometimes when i am opening HU editor, i get  http://pastebin.com/p5HCFnr6

**Comment by teosarca** [comment]
@metas-ts  pls take a look to this one when u have time

**Comment by metas-ts** [comment]
Hi @metas-mk @teosarca are you (still) getting that error?

**Comment by teosarca** [comment]
i got it only once...

**Comment by teosarca** [comment]
closing because it seems it's gone
