### ISSUE TITLE
Document no. in manual invoices should not be set by the user

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#235]
### Is this a bug or feature request?
Feature request
### What is the current behavior?
Document no. in manual invoices has to be set by user, can therefore be any no. the user chooses and will prob. not fit the order of the doc no.s of the rest of invoices.
#### Which are the steps to reproduce?
* Open sales invoice or purchase invoice, create a new one
* you have to set a doc no. (any no. will do) so the invoice will be saved
### What is the expected or desired behavior?
Document no. should be set by the system, according to the order of document no.s of the other invoices, e.g.: last purchase invoice had doc no. 145917, then the newly created one should get no. 145918

**Comment by teosarca** [comment]
IMHO, in case of vendor invoices, at least we shall allow the user to change the document no (if not enforce it?!) because that's the document no provided by vendor and it might not be in our control.

@metas-mk  wdyt?

**Comment by teosarca** [comment]
closing because it was already solved on some other task.
