### ISSUE TITLE
Transform CU on existing TU not working

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#237]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When transforming a CU onto an existing TU, this does not work.
#### Which are the steps to reproduce?
Receive CU's 2 lines w/ different products in Material Receipt Candidate. Transform some of Product a) into new TU. Transform some of the Product b) onto existing TU.
### What is the expected or desired behavior?
The CU Qty shall be transformed and shown in the existing TU.

![image](https://cloud.githubusercontent.com/assets/13365687/23708933/011ed330-0418-11e7-8c57-2e9c856a5e99.png)

**Comment by metas-mk** [comment]
Could be because of TU != infinite capacity and kg (not pce). Works if kg fits to max capacity of the TU.

**Comment by metas-dh** [comment]
@metas-mk, @metas-ts:

* when using >CU then fitting on a TU, when 1st transforming, i get >1 TU, e.g. 13kg product A, selected G1 x 10kg: i get 1 G1 x 10kg and 1 G1 x 3kg: OK?
* but when using more CU from another product, when 2nd transforming, i can put more product into the "full" TU, e.g. put another 5kg of product B into the G1 x 10kg, then it is displayed just as "G1": OK?

**Comment by metas-mk** [comment]
@metas-dh 
about a) yes, that's ok. not nice, but still have to decide in which direction we march. more strict or more flexibility.
about b) yes, same as a)
about c) yes, ok.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23237.md: OK
