### ISSUE TITLE
Attributes propagated on everything in TU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#238]
### Is this a bug or feature request?
Bug
**Important:** Wait for results of https://github.com/metasfresh/metasfresh-webui/issues/239 first!
### What is the current behavior?
TU w/ 2 different CU Products. Change an Attribute of Product a). Then Product b) Attribute and TU Attribute is changed also. Same thing happens if you change an Attribute on a CU Product c) outside the box and transform the product c) into the box. Then all Products and TU inherit the Attribute.
#### Which are the steps to reproduce?
As describe above.
### What is the expected or desired behavior?
Distinguish on which level the Attribute ist set and then only propagate top-down.

![image](https://cloud.githubusercontent.com/assets/13365687/23711199/749f8e92-041f-11e7-83cb-65e06e2fd712.png)

**Comment by metas-lc** [comment]
IT:
1. open hu editor with CU only, for 2 products
add some qty of both products on a TU
change some attributes on CU level => TU remain unchanged
2. open hu editor with CU only, for 2 products
add some qty of a product on a TU
change some attributes on the other product
add some qty of this product on the same TU => TU remain unchanged. Eventually the CU changes like in the TU (e.g. country) because was already set in TU

**Comment by metas-ts** [comment]
hi @metas-lc 
> is that OK?

it depends :-)
Attributes are propagated according to the roles se in their `M_HU_PI_Attribute` record
Example: If you add a CU to an existing TU, then the CU's weight shall be propagated, but the CU's "Herkunft" (origin) shall not.

**Comment by metas-lc** [comment]
resume	
	* CU->new TU: TU gets CU ASI; CU does not modify
	* CU->existing TU: CU gets the ASI; TU does not modify
	* CU-> modified TU: CU gets ASI; TU does not modify
	* TU->new LU: LU does not get the asi; TU does not modify
	* TU->modified LU: TU and CU gets the ASI; LU does not change

**Comment by metas-lc** [comment]
hi @metas-ts . Thank you. That works fine. An existing TU doesn't get modified by the new CU. 
not sure how it should work for new TU/LU.
the new TU gets e.g. origin from CU, but new LU doesn't get the origin from TU

**Comment by metas-lc** [comment]
Scope of the task was OK. Created a follow-up for propagation of attributes on LU and TU which don't wok the same: https://github.com/metasfresh/metasfresh-webui-api/issues/253
