### ISSUE TITLE
Attribute Readonly vs. editable swapped in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#239]
### Is this a bug or feature request?
Bug
### What is the current behavior?
It seems as if the Attributes read-only vs. editable swapped in WebUI after doing any Transform w/ an HU. Editable in WebUI is read-only in swing and vice versa. In initially created HU the editable/ read-only config is working properly.
### What is the expected or desired behavior?
Make it work same on both clients also after transform.

![image](https://cloud.githubusercontent.com/assets/13365687/23723970/6c150c12-044b-11e7-86a7-29724bbdaa03.png)
![image](https://cloud.githubusercontent.com/assets/13365687/23723985/757fb45a-044b-11e7-93b7-9dc00002b23a.png)
![image](https://cloud.githubusercontent.com/assets/13365687/23723993/8027ab24-044b-11e7-975e-70f9ad8c3810.png)

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

* Attributes read-only vs. editable remains the same after Transform, for LU, TU, CU level: OK

@metas-mk, @teosarca:
* in WebUI, Mindesthaltbarkeit is not editable for aggregated TUs, only free ones; different in swing: there it is always editable; is this wanted?
* in WebUI, the cost price is not displayed in CUs, like it is in swing; is this wanted?

**Comment by metas-dh** [comment]
checked with mk:
* Mindesthaltbarkeit must be editable for aggregated TUs, as well as for free ones, as in swing (=> needed for e.g. 2 different types of products on the same LU, products have different date of Mindesthaltbarkeit!): NOK

**Comment by metas-dh** [comment]
checked with tsa:
* Mindesthaltbarkeit is actually not editable on aggregated TUs in swing either, but looks like it because the swing UI renders it wrongly
created https://github.com/metasfresh/metasfresh/issues/1208
