### ISSUE TITLE
Document no. in manual material receipt should not be set by the user

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#240]
### Is this a bug or feature request?
Feature request
### What is the current behavior?
Document no. in manual material receipt has to be set by user, can therefore be any no. the user chooses and will prob. not fit the order of the doc no.s of the rest material receipts.
#### Which are the steps to reproduce?
* Open New Material Receipt, to create a new one
* you have to set a doc no. (any no. will do) so the receipt will be saved
### What is the expected or desired behavior?
Document no. should be set by the system, according to the order of document no.s of the other receipts; as it works already for manual shipment.

**Comment by teosarca** [comment]
The material receipt document type is not configured to be DocumentNo controlled.

**Comment by metas-lc** [comment]
IT:
tried with sales/ purchase order: the document no is set when you create a new one
tried with material receipt and shipment: docno is not set (not DocumentNo controlled document type)
