### ISSUE TITLE
KPIs: Introduce TimeRange ending offset

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#244]
### Is this a bug or feature request?
feature

### What is the current behavior?
When querying the KPI data, if the "toMillis" is not specified (basically current case) the system assumes the ending range is NOW.

### What is the expected or desired behavior?
* have a way to configure the range ending offset (relative to NOW) on each KPI
* have a way to override KPI's default range ending offset on Dashboard item level (be use able to reuse some KPIs)
* have a way to override KPI's default time range on Dashboard item level (be use able to reuse some KPIs)

**Comment by metas-mk** [comment]
Testing.

**Comment by metas-mk** [comment]
Tested. Works as required. Closing.
