### ISSUE TITLE
Row is not always marked as not saved

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#246]
### Is this a bug or feature request?
bug

### What is the current behavior?
Sometimes an included document row is not flagged as not saved (pale red, red line on the left).

#### Which are the steps to reproduce?
* order
* create a new line via batch entry
* clear the product field
=> field is marked as "error" but the row is not. => NOK

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Closing.
