### ISSUE TITLE
Provide to frontend: tab allow create new and delete as they change

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#252]
### What is the current behavior?
If an included tab allows creating new documents or deleting existing documents is not provided to frontend.
So the frontend is always showing the buttons for creating/deleting included documents.
If the option is not allowed it will fail when user presses the button.

### What is the expected or desired behavior?
That information shall be provided to frontend ASAP.
The frontend shall not display those options if not available => we will create a frontend task, as a follow-up of this task.

**Comment by metas-lc** [comment]
IT:
sales/purchase order
on new:
0. allowCreateNew:false
allowDelete:true
1. allowCreateNew:false
allowDelete:false

on existing, uncompleted document:
0. allowCreateNew:true
allowDelete:true
1. allowCreateNew:false
allowDelete:false

on completed document
0. allowCreateNew:false
allowDelete:false
1. allowCreateNew:false
allowDelete:false

Tested also in business partner - i could add and remove e.g. location
creating and completing orders went fine. Line for Tu was added. Tried to add a product after it was completed - got error . OK
TODO: see e2e (rest is OK)

**Comment by teosarca** [comment]
Update, @damianprzygodzki found several issues on this task and he documented them on here:
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/541#issuecomment-288412589
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/541#issuecomment-288415241
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/541#issuecomment-288416501

I will fix it here, in this task.

**Comment by metas-lc** [comment]
IT2
1. new order, set all mandatory fields
2. add an empty line (using add new with no product)
=> allowCreateNew:false, allowDelete:false OK
3. add mandatory field on line (the product) 
=> allowCreateNew:true, allowDelete:true OK
4. remove mandatory field bpartner from order
=> allowCreateNew:true, allowDelete:true NOK
created follow-up: https://github.com/metasfresh/metasfresh-webui-api/issues/271
