### ISSUE TITLE
Document fields: when receiving empty string values from frontend, convert them to nulls

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#255]
This task will solve a part of  https://github.com/metasfresh/metasfresh/issues/1173

which was also described on https://github.com/metasfresh/metasfresh-webui-frontend/issues/548

Suggestion for IT: test as described on https://github.com/metasfresh/metasfresh-webui-frontend/issues/548 .

**Comment by metas-lc** [comment]
IT:
1. go to Product window
2.  take an already existing product and remove the name
    => product is not saved, because name is mandatory. OK
    => red mark on name to see that is not set. When you hover it you can see "Mandatory field not filled" OK
3. set back the name, then set and remove the value from description, or other string field
=> that field is null OK 
4. checked poreference field in order.
=> on new is null
=> set it to 123 => value is 123
=> remove value 123 => is now null OK

TODO: see e2e (rest is OK)
