### ISSUE TITLE
BPartner contact cannot be saved because mandatory field Name is not set

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#257]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* pick or create a new BPartner
* try to create a new Contact
=> no matter what are you doing, the BPartner cannot be saved because Name field is mandatory.
But because it's not shown you cannot fill it.
Usually on before save the Name is build from Firstname and Lastname but webui is not reaching that point.

### What is the expected or desired behavior?
Implement a callout which will build the Name when user changes Firstname or Lastname.

**Comment by metas-lc** [comment]
IT: 
go to Bpartner, make a new one:
 set mandatory fields: name and company
add new contact: write only the first name, ok => it saves OK
add a new contact, write only the last name => it saves OK
add a new contact,don;t write any name, ok => not saved OK
