### ISSUE TITLE
Error when recording Swiss location in webUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#258]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Recording a new Business Partner Location with Country Switzerland is not saveable and shows a weird behavior. 
#### Which are the steps to reproduce?
Open the location editor, select Switzerland. The Region field opens and the country Field is deleted. The user cannot save the record.
### What is the expected or desired behavior?
Allow also Locations from Switzerland and other countries where regions are available.

![image](https://cloud.githubusercontent.com/assets/13365687/24073676/812f9ce0-0bfb-11e7-849b-33821f35f832.png)

![image](https://cloud.githubusercontent.com/assets/13365687/24073672/75ff5e82-0bfb-11e7-87e0-b194472fbaef.png)

**Comment by teosarca** [comment]
that's a frontend issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/551
