### ISSUE TITLE
New Warehouse is not saveable

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#259]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* create a new Warehouse
* will never be saved because C_Location_ID is not filled.
NOTE: that field is actually a legacy field which is set from C_BPartner_Location.C_Location_ID on before save (via model interceptor)... but we are not reaching that point.

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Closing.
