### ISSUE TITLE
cannot create receipt with multiple TU on LU 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#260]
### Is this a bug or feature request?
bug
### What is the current behavior?
when i want to create receipt from an LU with multiple TUs, nothing happens
#### Which are the steps to reproduce?
1. create a purchase order, add product, 50 kg,  complete
2. go to receipt candidates and select the line with product
3. open it on CUs
4. put the CUs on 5 TUs x10
5. put 3 TUs (one by one) on 1 new LU
6. select this LU and press on create material receipt => nothing happens
### What is the expected or desired behavior?
to get a material receipt for this LU i selected

![huedit](https://cloud.githubusercontent.com/assets/16001666/24074515/00120d10-0c13-11e7-9675-a7947b29b2b1.png)

**Comment by metas-ts** [comment]
i fixed this one together with metasfresh/metasfresh#1177

**Comment by metas-lc** [comment]
IT
repeated the testcase. Works fine
LU added in receipt. Correct qty TU
OK
