### ISSUE TITLE
Date offset in Dashboard KPI because of missing Timezone

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#261]
### Is this a bug or feature request?
Feature
### What is the current behavior?
Currently, the KPI Indicators show the numbers for a given Date 1 day too early.
#### Which are the steps to reproduce?
Create a Sales Order for today, Complete. Check the Dashboard. The numbers in the dashboard raise on today-1.
### What is the expected or desired behavior?
Raise the numbers on the correct day.

**Comment by metas-lc** [comment]
IT:
created order for today => green line got bigger for today
(you can either wait a bit or refresh the kpi to see the changes)
tested for other days that were displayed in the kpi => the lines changed accordingly
tested for a day that was not shown in the kpi => no lines changed
tested for a grey line (1 week ago) => the grey line changed accordingly
