### ISSUE TITLE
Bug in Warehouse window: View MRP Records NoMenuNodesFoundException

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-api#262]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* There is a NoMenuNodesFoundException if I open the "View MRP Records" from the referenced Documents list.
#### Which are the steps to reproduce?
* Go to a warehouse which has referenced documents, click on  "View MRP Records" 
* => NOK: there is an exception in the inpection: 
![image](https://cloud.githubusercontent.com/assets/16001442/24107426/56173c18-0d93-11e7-98d1-ae21d1713ba3.png)

### What is the expected or desired behavior?
* There should be no exception. The node should be added

**Comment by teosarca** [comment]
Known issue. Basically that window is not added to webui menu. Not sure when and if it will be added.
