### ISSUE TITLE
Support different printers for same user and different login locations

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#264]
### Is this a bug or feature request?

Feature

### What is the current behavior?

Currently,  if a user logs on via webui, the printing system has no information about the host from which the user logged in. In the old zk webui, metasfresh received a unique `HostKey` string but afaik this is not the case in the new webui.

#### Which are the steps to reproduce?

* Login via webui
* Select your most recent `AD_Session` record
* `AD_Session.HostKey` is empty

### What is the expected or desired behavior?

Similar to the old webui, there should be a Hostkey being created and stored locally (in a cookie?).

**Comment by teosarca** [comment]
note to IT:
* full regression tests on printing needed (mainly when using printing hosts)
* test login with different users on Swing
* test login with different users on webui
* test login on server /serverMonitor page
* test hostkey is set to context

always check how the AD_Session is created, updated, i.e.
* to not create more AD_Sessions than one
* when you logout, the session shall be flagged as destroyed (i.e. AD_Session.Processed=Y)

Below it's a query to check the last sessions:
```sql
select * from AD_Session order by AD_Session_ID desc
```

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15, WebUI & Swing

* test login with different users on Swing: each user gets his one printing hostkey, OK
* test login with different users on webui: each user gets his one printing hostkey, OK
* test login on server /serverMonitor page: no printing hostkey, OK
* when you logout, the session shall be flagged as destroyed (i.e. AD_Session.Processed=Y): OK
* always check how the AD_Session is created, updated, i.e.: different AD_Session_ID for each new session, correct ad_role_id & loginusername, websession set if WebUI login / empty if Swing login, correct data in created & updated, processed (=destroyed) when logout etc., OK

* to not create more AD_Sessions than one:
=> i can log in with the same user in WebUI or Swing >1 time, e.g. in different tabs in Chrome for WebUI, and get different AD_Sessions (same printing hostkey though): OK? (posted question on testing chat)
=> if i log in with the same user, once in WebUI, once in Swing, i get different AD_Session_IDs & different printing hostkeys, i guess that is OK?

* to check: test hostkey is set to context: OK for Swing, to check for WebUI
* remaining ToDo: full regression tests on printing needed (mainly when using printing hosts)

**Comment by teosarca** [comment]
hi @metas-dh 

about
> => i can log in with the same user in WebUI or Swing >1 time, e.g. in different tabs in Chrome for WebUI, and get different AD_Sessions (same printing hostkey though): OK? (posted question on testing chat)
> => if i log in with the same user, once in WebUI, once in Swing, i get different AD_Session_IDs & different printing hostkeys, i guess that is OK?

IMHO yes it is.... there is no other way around....

**Comment by metas-dh** [comment]
printing regression:
* no. of copies for bpartner not considered, https://github.com/metasfresh/metasfresh/issues/1240
* TU labels for products with long names: part of the name is missing, usually part of the french name: to check

**Comment by metas-dh** [comment]
Printing regression:

* no. of copies for bpartner now correct, see IT for metasfresh/metasfresh#1240
* TU labels for products with long names: created https://github.com/metasfresh/metasfresh/issues/1333
* besides that, printing regression testing worked fine (print / print preview / no. of copies / correct printer etc.)
