### ISSUE TITLE
API for Manufacturing UI Planning/ Doing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#269]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
Currently, there is no API to provide the action issue/ receipt for manufacturing in metasfresh WebUI.
Important idea: when issuing stuff from HU to planned manufacturing, then the split off/ used HU shall somehow only be blocked (not directly destroyed). This shall allow the user to manipulate until the 4-eyes check has been done. This will improve the flexibility for the user dramatically.
### What is the expected or desired behavior?
Concept and implement the provided API.
See https://github.com/metasfresh/metasfresh-webui-frontend/issues/580 for further UI details.

**Comment by teosarca** [comment]
Note to IT:
* full and strong e2e is mandatory; focus on manufacturing
* regression: https://github.com/metasfresh/metasfresh/issues/810

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

=> pls see task chat for problems found
