### ISSUE TITLE
Cannot change BPartner address

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#276]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* add new address just with country filled out
* "save"
* edit the address and add a string in first line
=> NOK: not saved indicated by red line:
![image](https://cloud.githubusercontent.com/assets/1244701/24548913/aa03640c-161f-11e7-88ee-5eb603195d87.png)

### What is the expected or desired behavior?
BP location shall be saved. BP shall not have save errors.

**Comment by teosarca** [comment]
might be related with https://github.com/metasfresh/metasfresh/issues/1173 because it seems the empty strings are not handled homogenous, so sometimes they are "" and sometimes they are null.

**Comment by metas-ts** [comment]
cherry-picked this into the `release` branch

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15release

* retested testcase from above, worked fine, all saved correctly, no red line in header: OK

**Comment by metas-dh** [comment]
Retested on mf15 WebUI: worked fine as well: OK
(problem with adding more new addresses bc of missing Add new button, see https://github.com/metasfresh/metasfresh-webui-frontend/issues/541#issuecomment-291982855)
