### ISSUE TITLE
Don't export JSONDocument.fields if empty

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#277]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Sometimes JSONDocument fields are exported to JSON as an empty array if though it's configured to @JsonInclude(JsonInclude.Include.NON_EMPTY)

#### Which are the steps to reproduce?
Try edit some document and line (e.g. a sales order).
Check chrome's Network tab, focus on those endpoints which are returning document changes.
In some cases you will something like
```
   fields : []
```

### What is the expected or desired behavior?
Never export "fields" if empty.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* edited document, e.g. sales order, bpartner, checked Network: never had JSONDocument fields which were empty: OK
