### ISSUE TITLE
Scan of Barcode "Bestellkontrolle" for Manufacturing execution

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#280]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The User has no possibility to scan a barcode to open the manufacturing execution window (issue, receipt) in webUI.
#### Which are the steps to reproduce?
Try it.
### What is the expected or desired behavior?
When in window manufacturing order grid view, the user shall be able to press a button/ action and then scan a barcode (i believe it should be a modal overlay that then only allows the scan). The Barcode will be read from the "Bestellkontrolle" report. The Barcode confirmation will automatically open the detail window for action issue/ receipt in webUI. In case the Barcode is not found, the user shall be informed.

**Comment by teosarca** [comment]
NOTE: all work is done on issue #269 (branch gh269webui)

**Comment by teosarca** [comment]
Update:
The Bestellkontrolle barcode was implemented in this task: https://github.com/metasfresh/metasfresh/issues/1315 => see db function: https://github.com/metasfresh/metasfresh/blob/master/de.metas.fresh/de.metas.fresh.base/src/main/sql/postgresql/ddl/functions/generate_barcode_order_checkup.sql

**Comment by teosarca** [comment]
Implemented.

**Comment by metas-mk** [comment]
Tested quickly. Works as required. Closing.
