### ISSUE TITLE
DocumentNo not generated for manual invoices in WebUI

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#281]
### Is this a bug or feature request?
bug

### What is the current behavior?
documentno is empty and has to be provided manually

#### Which are the steps to reproduce?
just open customer invoice window and create a new record

![image](https://cloud.githubusercontent.com/assets/16079655/24607887/3509c43c-1874-11e7-82ab-21d28b4a8a4e.png)

### What is the expected or desired behavior?
number should be automatically given by the system according to doctype and sequence number config.

**Comment by teosarca** [comment]
can you please check and paste the document type config for **exactly** that invoice?
(mainly i am interested in C_DocType's IsDocNoControlled, IsOverwriteSeqOnComplete, DocNoSequence_ID, DefiniteSequence_ID)

**Comment by metas-mk** [comment]
ah, ok. I' know the reason

**Comment by metasnw** [comment]
![image](https://cloud.githubusercontent.com/assets/16079655/24608289/38f6d740-1876-11e7-8c9f-9bbb390997bf.png)

**Comment by metas-mk** [comment]
Closing this issue, because will be fixed in metasfresh/metasfresh.
