### ISSUE TITLE
HU editor: Cannot receive stand alone TUs by default

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#284]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* create an purchase order for some standalone HUs (e.g. Paloxe)
* open Receipt candidates, select the line and try to receive using the default button
=> got an error about "infinite capacity" 

### What is the expected or desired behavior?
* receive one TU 

note: this task is not covering the issues from "receive with config" process.

**Comment by teosarca** [comment]
@metas-ts  pls cherrypick to master

**Comment by metas-ts** [comment]
@teosarca done

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* receive a standalone TU like Paloxe, using default button (set with 1 Paloxe): no error or exception, working fine: OK
