### ISSUE TITLE
UserSession language endpoint shall always work with JSON values

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#286]
### What is the current behavior?
* PUT /userSession/language - accepts "AD_Language" string as body
* GET /userSession/language - returns "AD_Language" string

### What is the expected or desired behavior?
* PUT /userSession/language - shall accept { "en_US" : "bla bla" }
* GET /userSession/language - shall return { "en_US" : "bla bla" }
* GET / - the language which is contained in that response shall be in same format (and not only the language code)

**Comment by metas-lc** [comment]
tested together with https://github.com/metasfresh/metasfresh-webui-api/issues/310 OK
