### ISSUE TITLE
Update current notifications when user language was changed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#287]
### Is this a bug or feature request?
Bug

### What is the current behavior?
* generate some material receipts or something, just to have some notifications in the queue.
* go to settings and change the language: https://w101.metasfresh.com:8443/settings
* check the notifications (NOTE: atm because of https://github.com/metasfresh/metasfresh-webui-frontend/issues/614 you have to refresh the page)
=> notifications are not translated to current language

NOTE: when checking it, make sure the messages behind those notifications are really translated!

### What is the expected or desired behavior?
Notifications shall be in current language, when those notifications are translatable.

**Comment by metas-lc** [comment]
IT OK
- changed the language in settings
- created new receipts
- notifications for receipt are translated
- changed language in settings again
=> notifications are translated
