### ISSUE TITLE
Return includedTabsInfo as an Object.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-api#288]
### Is this a bug or feature request?
FR
### What is the current behavior?
Is an array.
#### Which are the steps to reproduce?
Each patch and window init.
### What is the expected or desired behavior?
It would be great to have Object instead of Array.

**Comment by metas-ts** [comment]
cherry-picked into `relelease` branch

**Comment by teosarca** [comment]
note to IT: nothing to test.
