### ISSUE TITLE
New/Delete buttons missing when a document was initially loaded

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#289]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Open an existing document, e.g.
* https://w101.metasfresh.com:8443/window/123/2156591
* https://w101.metasfresh.com:8443/window/143/1004856

Remark that there are no New/Delete buttons for any of included tabs.
On a deep look, you will see that the buttons are not there because the API "thinks" that the document is not active.
If you would change something to document (e.g. deactive and then reactive) the buttons will be there.

**Comment by metas-dh** [comment]
Results of IT1
tested w101

* New & Delete buttons available in the included tabs after initially loading a document: OK
* buttons not available where not wanted, e.g. tab Vorgänge in bpartner: OK
* New button not available where mandatory field not filled yet: OK
