### ISSUE TITLE
Primary Key missing in Role Subtabs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#290]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When playing around w/ content in Role window, the Screen freezes.
#### Which are the steps to reproduce?
Open Window Role in WebUI. Click in one or 2 fields. The creed freezes.
### What is the expected or desired behavior?
Don't freeze.

![image](https://cloud.githubusercontent.com/assets/13365687/24766400/6dae6c3c-1afb-11e7-9a3e-8cf84a230f94.png)

**Comment by teosarca** [comment]
cannot reproduce
