### ISSUE TITLE
Show value/ name in breadcrumb but edit in window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#291]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, value and name fields are shown in Breadcrumb. When the value is not an automated value, then the user has to overwrite/ edit it in Breadcrumb.
#### Which are the steps to reproduce?
Open the Role maintenance window in WebUI and Add new. window/111/
### What is the expected or desired behavior?
Allow defining if value and name fields shall be shown in the Main window, besides only in the breadcrumb. It could even make sense to decide that all editable fields are only in the Main window and in breadcrumb only the read-only results are shown. WDYT?
![image](https://cloud.githubusercontent.com/assets/13365687/24837681/e334f1e8-1d39-11e7-8526-f33a4fe239b4.png)

**Comment by metas-mk** [comment]
@teosarca As discussed. we should drop editing in breadcrumb completely, and show the fields if wanted in editing mode in the normal window area. in the breadcrumb shall only be the value + name pairing description.

**Comment by teosarca** [comment]
UPDATE: implemented as follows:
* the DocumentNo-ish field will no longer be up there near breadcrumb
* the record summary string will be built as follows:
** from all columns which were flagged as identifier (same as lookups)
** if nothing found, will try Value_Name
** if nothing found, will try DocumentNo

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15releasetest

*adding value now in window, not in breadcrumb: OK
* if value is not an automated value, then it's a mandatory field in window: OK
* if e.g. name & value are mandatory (in e.g. New Pricesystem), then the values set by the user are displayed in the breadcrumbs after they were set: OK
