### ISSUE TITLE
Multiple entries with the same key error is interrupting manufacturing workflow.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-api#298]
### Is this a bug or feature request?
Probably bug
### What is the current behavior?
I can issue the same products multiple times and it causes error.
#### Which are the steps to reproduce?
-select manufacturing order
-start `Issue/Receipt` action
-select component product
-start `Issues` action
-select product in included view
-issue it with action two times
-after refresh issuing manufacturing order is not able to start
### What is the expected or desired behavior?
Prevent adding multiple times the same product if it is not allowed?

**Comment by teosarca** [comment]
shall be fixed also because now we are hiding the HUs which were issued.
