### ISSUE TITLE
Quickaction new Request in BPartner Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#300]
### Is this a bug or feature request?
Feature request
### What is the current behavior?
Currently, it is not possible to easily create a new Request in BusinessPartner Window.
#### Which are the steps to reproduce?
Open the BusinessPartner Window and check.
### What is the expected or desired behavior?
It shall be possible via action menu, to start a "new Request" action. A modal overlay with Request Fields shall open and allow the creation of a new Request. The request shall be shown in BusinessPartner Window in Subtabs after creation.
Info: Already existing Request References shall be shown in Referenced Documents in Sidelist.

**Comment by metasnw** [comment]
@metas-mk the expectation was more to use the "add new" Button that used to be there:
![image](https://cloud.githubusercontent.com/assets/16079655/25264556/1bab19ee-2668-11e7-84ab-bb53a5c14ec8.png)

**Comment by teosarca** [comment]
UPDATE:
* the backend will provide "advanced" flag in action response
* the layout will provide a caption

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* "Create new request" available in action menu, in bpartner window: OK
* Modal overlay with Request Fields opens when selecting it, for creating a new request: OK
* Modal has the correct caption, "Vorgang (alle)": OK
* Newly created request is displayed in bpartner window, subtab Vorgänge after creation: OK
* Existing requests are displayed in Referenced Documents in Sidelist: OK
