### ISSUE TITLE
ASI button not working from process panel

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#303]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* open a process which has ASI parameter (e.g. Revenue Busines Partner)
* try to edit the ASI => not working

### What is the expected or desired behavior?
shall work

**Comment by teosarca** [comment]
frontend part shall be solved on https://github.com/metasfresh/metasfresh-webui-frontend/issues/667

**Comment by metas-lc** [comment]
IT
tested together with https://github.com/metasfresh/metasfresh-webui-api/issues/319 OK
