### ISSUE TITLE
Show empty charts instead of errors in Dashboard when system is empty

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#307]
### Is this a bug or feature request?
bug/feature

### What is the current behavior?
the first three show error while the others just show no data.

![image](https://cloud.githubusercontent.com/assets/16079655/25290709/611e1f46-26cf-11e7-80f9-c9d6b2346485.png)

#### Which are the steps to reproduce?
install metasfresh from scratch via docker 

### What is the expected or desired behavior?
Can we make them all show no data instead of an error ?

**Comment by teosarca** [comment]
Frontend issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/713
