### ISSUE TITLE
Switching language does not switch all elements

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#308]
### Is this a bug or feature request?
bug

### What is the current behavior?
when switching the languages the name of processes and referenced documents do not switch

#### Which are the steps to reproduce?
1. set language en_US
2. open order window
3. switch language to de_DE
4. press F5 to refresh
5. press CTRL+5 to open references:

![image](https://cloud.githubusercontent.com/assets/16079655/25295812/82012120-26e5-11e7-86a8-c300fb2b6c89.png)

Workaround: Server cache reset

### What is the expected or desired behavior?
All elements switch language

**Comment by metasnw** [comment]
@teosarca If this is a duplicate please just close it. Wanted to document a precise case...

**Comment by teosarca** [comment]
@metasnw created 2 separate tasks for those issues.
Closing this task. If we find more issues we will create other tasks.
