### ISSUE TITLE
Delete Product Category

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#309]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to delete a newly created product category in webUI
#### Which are the steps to reproduce?
Try to delete one.
### What is the expected or desired behavior?
Have the possibility to delete a product category. Important: Deleting data in Swing UI was often complicated. In webUI we should provide a guidance for the user how and when deletion is possible and what the user shall do.

**Comment by teosarca** [comment]
Quickly checked, cannot reproduce.
