### ISSUE TITLE
Switching language does not translate document lookup values

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#311]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Described on https://github.com/metasfresh/metasfresh-webui-api/issues/308 .
In this task we are addressing only the lookup values e.g. (Document Type, UOM etc).

### What is the expected or desired behavior?
When switching the language, after page refresh, the document shall have all lookup values translated to current language.

**Comment by metas-lc** [comment]
IT
tested together with https://github.com/metasfresh/metasfresh-webui-api/issues/310 OK
