### ISSUE TITLE
Handling Unit Barcode selection 1:1

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#313]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is possible to select multiple lines in Handling Unit Editor and process at once.
#### Which are the steps to reproduce?
Open Manufacturing Order Window, select line, open Manufacturing UI, select Issue Product and Issue Button, Select HU Lines.
### What is the expected or desired behavior?
For the beginning, only allow 1:1 selection from HU. When scanning HU then initialize previous selection.

**Comment by metas-lc** [comment]
IT
1. go to manufacturing order and select one
2. press on issue/receipt
3. select the co product, press on issue
(if you don't have HUs you can create purchase order and receipt for that product)
4. select some TUs, select barcode
5. write the value of an HU you have there
=> that HU is selected, the other ones are not selected anymore OK
6. use barcode again and write the value of another TU
=> now this TU is selected and the one from step 5 is not OK
7. select some TUs and use barcode
8. don't set any value, press esc
=> your TUs are still selected OK
