### ISSUE TITLE
HU attributes shall be readonly if the HUStatus is not planning

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#314]
### What is the current behavior?
HU attributes are editable even if the HU editor is Active or something else.

#### Which are the steps to reproduce?
* select a manufacturing order: https://w101.metasfresh.com:8443/window/53009
* receive an HU => remark that the HUStatus is planning and attributes are editable
* run Process plan quick action
* remark that the HU is active but attributes are editable => NOK

![image](https://cloud.githubusercontent.com/assets/1244701/25345667/4db26178-291e-11e7-8c6c-6028dda8f711.png)

### What is the expected or desired behavior?
Attributes shall be readonly if HUStatus is not Planning.

**NOTE: atm I decided to apply this rule wherever the HU editor is involved (atm only in receipt candidates and manufacturing order). When we will need to edit the attributes for Active HUs too, we would improve the feature.**

Required for https://github.com/metasfresh/metasfresh-webui-api/issues/269

**Comment by metas-lc** [comment]
IT
1. go to manufacturing order (/53009)
2. select a line, press on issue/receipt
3. select the main product, press on Receive HUs (if you don't have any planning hus to process)
4. select the new LU 
=> attributes are editable OK
5. press on Process plan
=> your HUs are now grey
=> attributes are still editable NOK
6. press on done and issue/receipt again
7. select your HU
=> attributes are readonly OK

**Comment by metas-lc** [comment]
moving it to done. shall be solved in https://github.com/metasfresh/metasfresh-webui-api/issues/319
