### ISSUE TITLE
Manufacturing Issue/Receipt: merge BOM Type and HU Type columns

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#315]
### What is the current behavior?
The Manufacturing Issue/Receipt shows BOMType and HUType columns.

#### Which are the steps to reproduce?
just open it.

### What is the expected or desired behavior?
It shall be only one column with the information merged:
![image](https://cloud.githubusercontent.com/assets/1244701/25346937/f2ce5c04-2921-11e7-9ddb-29ae540c04dd.png)

Required for https://github.com/metasfresh/metasfresh-webui-api/issues/269

**Comment by metas-lc** [comment]
IT
it is only one, called Type. Shows both BOMType and HUType  OK
