### ISSUE TITLE
Implement password widgetType support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#316]
### Is this a bug or feature request?
Feature

### What is the current behavior?
There is no widget type for Password, so they are handled as Text widgets.

#### Which are the steps to reproduce?
See https://w101.metasfresh.com:8443/window/108/100

### What is the expected or desired behavior?
Password fields shall use a special widgetType, called "Password".

Required for https://github.com/metasfresh/metasfresh-webui-frontend/issues/248

**Comment by metas-lc** [comment]
IT
1. go to user window
2. create a new one and add all mandatory fields
3. set system user on Y
=> password field appears
4. set a password 
=> you see only dots OK
5. save
=> still dots OK
