### ISSUE TITLE
Manufacturing Issue/Receipt: show packing info for BOM components

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#318]
### What is the current behavior?
The packing info for main product or bom co/by products is empty.

#### Which are the steps to reproduce?
* open manufacturing orders: https://w101.metasfresh.com:8443/window/53009
* call Issue/Receipt
* take a look at the lines
![image](https://cloud.githubusercontent.com/assets/1244701/25359997/09fad186-2950-11e7-8681-4b9939e00202.png)

### What is the expected or desired behavior?
The packing info for main product or bom co/by products shall be displayed.
Also the button which now is called "Receive HUs" shall display the packing info (same as on material receipt).

Required for https://github.com/metasfresh/metasfresh-webui-api/issues/269

**Comment by metas-mk** [comment]
Tested. Works as required. Packing Instruction is taken from PP_order header.
![image](https://cloud.githubusercontent.com/assets/13365687/25376493/ba9c137a-29a4-11e7-82e1-5b0c22341ee1.png)
