### ISSUE TITLE
Manufacturing Issue/Receipt: receipt lines shall be displayed first

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#323]
### What is the current behavior?
At the moment, the lines are sorted as they were defined in the BOM

### What is the expected or desired behavior?
The lines shall be sorted as follows:
* main product line
* other co/by product BOM lines
* issue BOM lines

Required for https://github.com/metasfresh/metasfresh-webui-api/issues/269

**Comment by metas-lc** [comment]
IT
go to Manufacuring order and select 1, press issue/receipt
=>
main product line (+ the HUs received for it)
other co/by product BOM lines
issue BOM lines
OK
