### ISSUE TITLE
File Size Limit

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#324]
### What is the current behavior?
it seems that files with not more than 1 MB can be uploaded

![image](https://cloud.githubusercontent.com/assets/16079655/25397630/2dc86c92-29e9-11e7-9152-a22335db50c2.png)

#### Which are the steps to reproduce?
drag a file with 2 MB on to a business partner to upload

### What is the expected or desired behavior?
Is there a place to configure the file size?

**Comment by teosarca** [comment]
I guess you have to configure spring's application.properties
see http://stackoverflow.com/questions/28572700/i-am-trying-to-set-maxfilesize-but-it-is-not-honored

**Comment by teosarca** [comment]
set by default 100Mb.

**Comment by teosarca** [comment]
But the complete solution would be together with https://github.com/metasfresh/metasfresh/issues/1111

**Comment by metas-lc** [comment]
uploaded a file of 64 MB. worked fine
