### ISSUE TITLE
technical: Remove JSONProcessInstanceResult deprecated properties

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#326]
### What is the current behavior?
the JSONProcessInstanceResult  contains deprecated properties which are also in actions.

#### Which are the steps to reproduce?
Run processes.

### What is the expected or desired behavior?
Shall work as before.
Test for the cases:
* start a regular process => shall work
* start a report => shall get the report PDF
* receipt candidates, receive some HUs => the HU editor shall open
* bpartner -> create request action => the Request modal shall open
* manufacturing order => call Issue/Receipt action => Manufacturing Issue/Receipt modal shall open
** select an Issue line and press "Issue HUs" action => the HU editor shall be opened in the right side

Pls also include this test to test catalog as a regression for "processes with follow-up actions".

![image](https://cloud.githubusercontent.com/assets/1244701/25428254/f7fdf61e-2a7d-11e7-8dba-cfd12ebca577.png)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 et al.

* start a regular process: works fine, OK
* start a report: PDF report created correctly, OK
* receipt candidates, receive some HUs: HU Editor opens correctly, OK
* bpartner, create request action: request modal opens correctly, OK
* manufacturing order, call Issue/Receipt action: Manufacturing Issue/Receipt modal opens correctly, OK
** select an Issue line and press "Issue HUs" action: HU Editor is opened on the right side, OK
* checked in inspect for all processes: only "error" & "pinstanceId" displayed besides "action", no other properties: OK

=> need to check and update e2e, to include these tests there as well

**Comment by metas-dh** [comment]
Updated e2e doku for weekly e2e as well.
