### ISSUE TITLE
Manufacturing receipt mandatory Field not filled

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#328]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when receiving Products in Manufacturing WebUI, it's not possible to receive Paloxen w/o LU.
#### Which are the steps to reproduce?
Open Manufacturing Receipt, Try receive configuration w/ Paloxe and not LU.
### What is the expected or desired behavior?
Allow the receipt to Paloxe w/o LU
![image](https://cloud.githubusercontent.com/assets/13365687/25471840/17af48e0-2b29-11e7-8a93-ea9c57929dec.png)

**Comment by metas-lc** [comment]
IT
* testcase 1: (NOK)
1. create a new manufacturing order and set a Paloxe config
2. in gridview select your line and issue/receipt
3. press on the green action button (with your Paloxe)
=> packvorschrift is set to Paloxe OK
=> LU is null and not mandatory OK
=> qty LU is not shown OK
4.  set an LU
=> Qty LU appeared OK
5. remove the LU
=> Qty LU is hidden OK
6. press on start
=> Process error
Fill mandatory fields: Menge LU NOK

* testcase 2: (OK)
1. create a new manufacturing order and set a Paloxe config
2. in gridview select your line and issue/receipt
3. press on the green action button (with your Paloxe)
=> packvorschrift is set to Paloxe OK
=> LU is null and not mandatory OK
=> qty LU is not shown OK
4. press on start
=> hu was received OK

**Comment by metas-lc** [comment]
IT2
repeated the testcases from IT
=> no errors when you remove the LU
works fine OK
