### ISSUE TITLE
Issue HU 404 not found

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#329]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When issuing 2nd time not possible.
#### Which are the steps to reproduce?
Open Manufacturing Editor. Issue HU. Try again. Error.
### What is the expected or desired behavior?
Shall be available to issue more than once.

![image](https://cloud.githubusercontent.com/assets/13365687/25472402/6abc2736-2b2b-11e7-984c-f07feaee63d0.png)

**Comment by teosarca** [comment]
Usually this happens when there are no HUs to receive.
The actual issue is that the error is not displayed to user. Fixed that.

**Comment by metas-lc** [comment]
IT
1. go to Material Receipt Candidates and create a new one
2. set all mandatory fields and complete
3. go in grid view, select your line and press issue/receipt
4. select the co product and press on issue
5. issue all the HUs you have in there
(if you don't have any you'll get an error. But if you want to have HUs you have to create a purchase order and a receipt for that product)
=> the HUs are issued well
6. press done and select the co product again, select issue (now you don't have any HUs left)
=> error message: 
Error: No HUs to issue...
Server error
No HUs to issue found
