### ISSUE TITLE
Name missing in business partner modal

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#335]
### Is this a bug or feature request?
bug
### What is the current behavior?
Name missing when you want to create a new bpartner on go
#### Which are the steps to reproduce?
1. go to sales order
2. write a name of a bpartner that does not exists
3. select New Business partner
=> modal opens
4. set isCompany on N
=> Company Name hides and Name does not appear instead NOK
### What is the expected or desired behavior?
like in this task, when isCompany is on N show Name instead CompanyName
https://github.com/metasfresh/metasfresh/issues/1307

**Comment by teosarca** [comment]
Showing Name is not needed because in case IsCompany=N user will fill the Firstname and Lastname.
