### ISSUE TITLE
Make Setup Wizard work in webUI

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#337]
### Is this a bug or feature request?
feature request

### What is the current behavior?
you need the java swing client to do the initial setup

#### Which are the steps to reproduce?
try to open "ersteinrichtung Assistent" in webUI => does not open

### What is the expected or desired behavior?
make the wizard work with basic fields like company name, address, etc.
Logo can be done later

**Comment by metasnw** [comment]
I dropped the column logo and tried to open it on 5.7 but is did no work
may be there is a way to use it almost as is because its a generic process

**Comment by teosarca** [comment]
waiting for the webui frontend fix: https://github.com/metasfresh/metasfresh-webui-frontend/issues/702

**Comment by teosarca** [comment]
closing this task. pls reopen if there are more problems.
