### ISSUE TITLE
request not visible in busines partner tab

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#338]
### Is this a bug or feature request?
bug
### What is the current behavior?
create a new request from bpartner => the request tab is not updated directly. I have to refresh to see the request
#### Which are the steps to reproduce?
1. go to e.g. /window/123/2156682
2. actions: create request, add all mandatory fields, press done
=> look in request tab: the new one is missing. Refresh - you can see it now 
### What is the expected or desired behavior?
the request should be visible without refresh

**Comment by metasnw** [comment]
its working fine on latest. closing...
