### ISSUE TITLE
Sales Order also show Purchase Orders

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#339]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When opening the Sales Order window in WebUI, also Purchase Orders are shown. Although SQL where clause is set C_Order.IsSOTrx='Y'
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Only show Sales Orders. Please also check if other similar cases ecist (Purchase Order, Invoice, inouts)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* sales order window: shows only sales orders, no purchase orders, and vice versa: OK
* sales inout window (shipment): shows only sales inouts, no purchase inouts (receipts), and vice versa: OK
* sales invoice window: shows only sales invoices, no purchase invoices, and vice versa: OK
* sales shipment schedules: shows only sales shipment schedules, no purchase receipt schedules, and vice versa: OK
