### ISSUE TITLE
Manufacturing order: Prevent issuing VHUs which are not top level

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#340]
### Is this a bug or feature request?
bug
### What is the current behavior?
after you select a subHU (e.g. VHU) to issue, it remains there to be selected again
#### Which are the steps to reproduce?
1.  go to Manufacturing order and select one or create a new one
2. select issue/receipt
3. select the CO product
4. select issue
5. select a VHU (so not the parent, but the child HU) and issue it
=> the VHU appears as issued on the left side (under co product) OK
=> the VHU still remains on right side to be issued NOK
6. issue it again
=> Error: org.postgresql.util.PSQLException: ERROR: duplicate key...
Server error
org.postgresql.util.PSQLException: 
ERROR: duplicate key value violates unique constraint "pp_order_qty_uq" 
Detail: Key (pp_order_id, m_hu_id)=(1000015, 1008815) already exists. 
SQL: INSERT INTO PP_Order_Qty 
NOK
=> it gets you out from issue
7. select the CO product and press on Issue again
=> the VHU is not only under the parent but it appears a new line with it (same error if you try to select it) NOK
=> you can also issue the parent so you can double the qty - i think NOK 

### What is the expected or desired behavior?
- when you issue a child, it shall disappear from the issue. I guess the parent shall also disappear if the qty is 0 (or qty cu to be updated?)
- VHU shall not get back to issues when you close it and open it again 

![issue](https://cloud.githubusercontent.com/assets/16001666/25650807/12961c08-2fe8-11e7-88c3-c5cb30843dd5.png)

**Comment by teosarca** [comment]
i think we shall disallow issuing VHUs.

**Comment by metas-lc** [comment]
IT
1. go to manufacturing order, select one and press on issue/receipt
2. select the co product and press on issue
3. select a vhu which is a child, issue it
=> 
Error: Issuing VHUs is not...
Server error
Issuing VHUs is not allowed
OK
4. as regression select both TU and VHU => works fine: both are issued and they are still parent+child OK
5. select a TU only
=> both TU and VHU are issued OK
