### ISSUE TITLE
Apply role permissions when browsing/editing data

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#341]
### Is this a bug or feature request?
Bug

### What is the current behavior?
When browsing or editing documents or views the role permissions are not applied at all.
So basically, you can view, edit, delete system records as a regular user.

##### Login with non-System role:
1. browse AD_Elements which shall be visible only for SysAdm: https://w101.metasfresh.com:8443/window/151
=> shall not be allowed

2. browse currencies: https://w101.metasfresh.com:8443/window/115 => shall be visible
* select one => shall be readonly if Client=System

##### Login with System role:
steps above shall work

NOTE to IT:
* pls come up with more tests
* full regression on Swing and Webui is needed :(

**Comment by teosarca** [comment]
fixed: the manufacturing order -> Issue / Receipt could not be open.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 et al., WebUI & Swing

repeated testcases above:
* browse AD_Elements which shall be visible only for SysAdm (https://w101.metasfresh.com:8443/window/151): => not allowed: OK
* browse currencies: https://w101.metasfresh.com:8443/window/115 => visible, but readonly if Client=System: OK
* System role: steps allowed & not readonly

Swing:
* i noticed the same role for different Orgs had access  to a different numbers of windows etc. (e.g. Handel, Einkauf): could this be caused by this task?

**Comment by teosarca** [comment]
minor fix to enforce window access when the frontend acquires the window layouts

**Comment by metas-lc** [comment]
IT
- testcases above work fine (element and currency)

- swing: 
- log in with other role than admin, org 2 
=> you can see only docs for org 2 OK
=> you can create docs only for org 2 OK

- log in with admin, org 2
=> you can see docs for org 1 and org 2 OK??
=> you can create docs for org 1 and org 2 OK??

- log in with admin, org 1 (main org)
=> you can see docs for org 1 and 2 OK
=> you can create docs for org 1 and org 2 OK

- webui
- log in with other role than admin, org 2 
=> you can see only docs for org 2 OK
(cannot open in doc view some sales orders for org 2 - one i created today. role permission. but i see it in gridview OK??)
=> you can create docs for org 2 OK

- log in with admin, org 2
=> there isn't this option OK??

- swing and webui: check which windows you should have access and which not, then see if you can open them
=>

**Comment by metasnw** [comment]
@metas-lc if role admin has access to all orgs your cases seem fine to me
