### ISSUE TITLE
Exception in WebUI when opening initial Doc Outbound window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#342]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Happened when initially creating the doc outbound window in webui,
see https://w101.metasfresh.com:8443/window/540170

`Error: org.postgresql.util.PSQLException: ERROR: column reference...
Server error
org.postgresql.util.PSQLException: ERROR: column reference "record_id" is ambiguous Position: 1833 SQL: SELECT master.*, (SELECT NULLIF (TRIM(AD_Client.Name), '') FROM AD_Client WHERE AD_Client.AD_Client_ID=master.AD_Client_ID ) AS AD_Client_ID$Display , (SELECT NULLIF (TRIM(AD_Org.Name), '') FROM AD_Org WHERE AD_Org.AD_Org_ID=master.AD_Org_ID ) AS AD_Org_ID$Display , (SELECT concat_ws('_', NULLIF (TRIM(AD_Table.TableName), ''), NULLIF (TRIM(AD_Table.Name), '')) FROM AD_Table WHERE AD_Table.AD_Table_ID=master.AD_Table_ID ) AS AD_Table_ID$Display , (SELECT concat_ws('_', NULLIF (TRIM(C_BPartner.Name), ''), NULLIF (TRIM(C_BPartner.Value), '')) FROM C_BPartner WHERE C_BPartner.C_BPartner_ID=master.C_BPartner_ID ) AS C_BPartner_ID$Display , (SELECT NULLIF (TRIM(C_BP_Group.Name), '') FROM C_BP_Group WHERE C_BP_Group.C_BP_Group_ID=master.C_BP_Group_ID ) AS C_BP_Group_ID$Display , (SELECT AD_Ref_List.Name FROM AD_Ref_List WHERE AD_Ref_List.Value=master.EDI_ExportStatus AND AD_Ref_List.AD_Reference_ID=540381) AS EDI_ExportStatus$Display , (SELECT NULLIF (TRIM(C_DocType.Name), '') FROM C_DocType WHERE C_DocType.C_DocType_ID=master.C_DocType_ID ) AS C_DocType_ID$Display , (SELECT AD_Ref_List.Name FROM AD_Ref_List WHERE AD_Ref_List.Value=master.DocStatus AND AD_Ref_List.AD_Reference_ID=131) AS DocStatus$Display FROM ( SELECT C_Doc_Outbound_Log.AD_Client_ID AS AD_Client_ID , C_Doc_Outbound_Log.AD_Org_ID AS AD_Org_ID , C_Doc_Outbound_Log.AD_Table_ID AS AD_Table_ID , C_Doc_Outbound_Log.C_BPartner_ID AS C_BPartner_ID , (SELECT C_BP_GROUP_ID from C_BPartner where C_BPartner_ID = C_Doc_Outbound_Log.C_BPartner_ID) AS C_BP_Group_ID , C_Doc_Outbound_Log.IsInvoiceEmailEnabled AS IsInvoiceEmailEnabled , (select bp.IsEdiRecipient from C_BPartner bp where bp.C_BPartner_ID=C_Doc_Outbound_Log.C_BPartner_ID) AS IsEdiEnabled , (SELECT "de.metas.edi".getEDIExportStatus(AD_Table_ID, Record_ID)) AS EDI_ExportStatus , (SELECT getDocumentPOReference(AD_Table_ID, Record_ID)) AS POReference , (select COUNT(*) from C_Doc_Outbound_Log_Line where C_Doc_Outbound_Log_Line.Action = 'print' AND `
#### Which are the steps to reproduce?
Open the window https://w101.metasfresh.com:8443/window/540170 and see
### What is the expected or desired behavior?
Shall be able to open without that bug.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* no error when opening DocOutbound window (Ausgehende Belege): OK
