### ISSUE TITLE
backend: Document references: group them by their top level menu

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#344]
### Is this a bug or feature request?
Feature

### What is the current behavior?
The document references are just displayed as a plain list.
If there are more, it's quite hard to figure out at a glance what's created and what's not.

#### Which are the steps to reproduce?
Select a sales order and browse document references.
Pls make sure you selected one with a lot of document references.

### What is the expected or desired behavior?
The document references shall be grouped by their top level menu.

![image](https://cloud.githubusercontent.com/assets/1244701/25739863/73376bde-318c-11e7-86eb-fc89a1f0f0dd.png)

**Comment by teosarca** [comment]
frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/719

**Comment by teosarca** [comment]
NOTE to IT: in this task is just providing the document references grouped (see the JSON response).
The visual part will be addressed on https://github.com/metasfresh/metasfresh-webui-frontend/issues/719

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* document references grouped: OK
* top level menu Billing - Shipment / Material Receipt - Others: OK
