### ISSUE TITLE
Batch entry not working in order

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#345]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Opening Batch entry causes an error:
Error: Invalid AD_Client_ID=-1 / AD_Org_ID=-1...
Server error
Invalid AD_Client_ID=-1 / AD_Org_ID=-1
#### Which are the steps to reproduce?
* Create a sales order
* Open batch entry (with CTRL & Q or pressing the tab)
### What is the expected or desired behavior?
Batch entry should open and be usable, without error.

**Comment by metasnw** [comment]
OK: tested on latest RC
