### ISSUE TITLE
Zoom into error

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#346]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When trying to open shipment from shipment schedule (or invoice from invoice candidate), using referenced documents, you get an error:

Server error
More than one zoomInfo found for source=DocumentAsZoomSource{tableName=M_ShipmentSchedule, recordId=1000001, AD_Window_ID=500221}, targetWindowId=169: [ZoomInfo{zoomInfoId=relationType-540115, display=trl{trls={en_GB=Lieferung, de_CH=Lieferung, it_CH=Lieferung, en_US=Lieferung, fr_CH=Lieferung, nl_NL=Lieferung}, default=Lieferung}, AD_Window_ID=169, RecordCount=999999}, ZoomInfo{zoomInfoId=Fact_Acct, display=trl{trls={en_GB=Lieferung, de_CH=Lieferung, it_CH=Lieferung, en_US=Shipment (Customer), fr_CH=Lieferung, nl_NL=Lieferung}, default=Lieferung}, AD_Window_ID=169, RecordCount=999999}]

#### Which are the steps to reproduce?
* Create a sales order
* Create the shipment 
* Try opening the shipment, from shipment schedules, referenced documents (same for invoice)
### What is the expected or desired behavior?
No error when using referenced documents when trying to open shipment from shipment schedules.

**Comment by metasnw** [comment]
tested on RC 
OK: zoom from shipment schedule => shipment
NOK: zoom from order => shipment
NOK: zoom from order => invoice 

error message
```
"More than one zoomInfo found for source=DocumentAsZoomSource{tableName=C_Order, recordId=1000000, AD_Window_ID=143}, targetWindowId=167: [ZoomInfo{zoomInfoId=relationType-540160, display=trl{trls={en_GB=Rechnung, de_CH=Rechnung, it_CH=Rechnung, en_US=Invoice (Customer), fr_CH=Rechnung, nl_NL=Rechnung}, default=Rechnung}, AD_Window_ID=167, RecordCount=999999}, ZoomInfo{zoomInfoId=generic-167, display=trl{trls={de_CH=Rechnung, en_GB=Rechnung, it_CH=Rechnung, en_US=Invoice (Customer), fr_CH=Rechnung, nl_NL=Rechnung}, default=Rechnung}, AD_Window_ID=167, RecordCount=999999}]"
```

**Comment by teosarca** [comment]
Fixed

**Comment by metasnw** [comment]
tested on RC

OK: zoom from shipment schedule => shipment
OK: zoom from order => shipment
OK: zoom from order => invoice 
OK: Material Receipt => Purchase Order
OK: Purchase ORder => Vendor Invoice
