### ISSUE TITLE
Empty entry in address, deleted only after refresh

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#347]
### Is this a bug or feature request?
Bug
### What is the current behavior?
* Leaving the modal window for new address without adding any data creates an empty line in address
* when deleting that line, it does only disappear after refreshing the bpartner window
#### Which are the steps to reproduce?
* Open bpartner window
* Add new for Address: modal window opens
* click Done in the modal, and OK when you are asked if you want to leave the page
=> new address entry is created nevertheless, and is empty; page is not saved and has red header
* delete the empty address line: 
=> does not disappear,  page is not saved and has red header
* refresh the bpartner window: empty address line now gone
### What is the expected or desired behavior?
shall work as before

**Comment by teosarca** [comment]
Can you pls re-test this one? might be that the problem was already (partially) solved....

**Comment by metas-rc** [comment]
Results of IT1

Tested on webui


Open bpartner window
Add new for Address: modal window opens
click Done in the modal, and OK when you are asked if you want to leave the page
 => OK : new address entry is created nevertheless, and is empty;
 => OK: page does not have red header
delete the empty address line:
=> OK : The line disappears
=> OK:  page doesn't have red header
refresh the bpartner window
=> OK:  empty address line is still there
go somewhere else, then return to the partner window and go to the location tab
=> OK: The empty line is still there
Set the address in the empty  line
=>OK: the address saves correctly and is no longer red.
