### ISSUE TITLE
backend: Implement Zoom-into in webUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#348]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently there is no Zoom-into functionality in WebUI (that thing that in Swing can be used w/ right-mouse "Springe zu" and opens the window and record for the selected ID)
#### Which are the steps to reproduce?
Try it in WebUI.
### What is the expected or desired behavior?
Have that functionality or similar in WebUI.

**Comment by metas-mk** [comment]
Idea: In detail view have the labels then as links to zoom-into. let's solve that first, can think later about grid-view zoom-into.

**Comment by metas-lc** [comment]
IT
tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/720 OK
