### ISSUE TITLE
Introduce JSONLayoutType.primaryLongLabels

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#352]
The "primaryLongLabels" is similar with "primary" but will signal frontend that we need to render long labels.
At the moment will be used for checkboxes and switches in document filter layouts.

Needed for task https://github.com/metasfresh/metasfresh-webui-frontend/issues/411.

NOTE: this is a follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/334

Note to IT: nothing to test here. Just test https://github.com/metasfresh/metasfresh-webui-frontend/issues/411

**Comment by metas-lc** [comment]
IT
tested https://github.com/metasfresh/metasfresh-webui-frontend/issues/411 OK
