### ISSUE TITLE
Handling Unit is always No Handling Unit in WebUI on a particular case

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#353]
### Is this a bug or feature request?
bug

### What is the current behavior?
OK: java swing shows Virtual PI or the particular Packing Instruction
OK: webUI: add new shows Virtual PI or the particular Packing Instruction
NOK: webUI: batch entry shows for all products "NO HANDLING UNIT"

#### Which are the steps to reproduce?

- unknown. happens on a particular database where packing instructions and other stuff was modified
- no error in webui or API log 
- 

### What is the expected or desired behavior?

What is the logic of the code starting from the product to determine the packing instruction?

### error case

what ever I do there is always no handling unit already in the selection box:

![image](https://cloud.githubusercontent.com/assets/16079655/25914813/cf563e22-35bf-11e7-88c3-31e9cda9a6ca.png)

**Comment by metasnw** [comment]
- excluded pricing as cause
- made sure PIs are same as metasfresh vanilla
- imported the db into 5.8 but the problem persists

**Comment by teosarca** [comment]
Shall be fixed by https://github.com/metasfresh/metasfresh/issues/1502
