### ISSUE TITLE
Support for Record_ID buttons

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#354]
### Is this a bug or feature request?
Feature request

### What is the current behavior?
The "Record_ID" buttons are not supported

#### Which are the steps to reproduce?
Any window which has AD_Table_ID/Record_ID.
e.g. https://w101.metasfresh.com:8443/window/193
and click on Record_ID button. Shall zoom into.

Follow-up of: https://github.com/metasfresh/metasfresh-webui-api/issues/348
Frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/216

**Comment by metas-lc** [comment]
IT
1. window 193 - check layout, record_id element: 
supportZoomInto:true
widgetType:"ZoomIntoButton"
OK
