### ISSUE TITLE
Manufacturing Quickaction: Reverse Receipt

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#355]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to reverse an already prepared receipt.
#### Which are the steps to reproduce?
Try a receipt and try to reverse.
### What is the expected or desired behavior?
It shall be possible to reverse a prepared receipt HU Assignment. Select the receipt line and press reverse - all planned HU assignments are initialized.

**Comment by teosarca** [comment]
will  be solved in https://github.com/metasfresh/metasfresh-webui-api/issues/356
