### ISSUE TITLE
Manufacturing Quickaction: Reverse Issue / Receipt

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#356]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to reverse an already prepared issue.
#### Which are the steps to reproduce?
Try an issue and try to reverse.
### What is the expected or desired behavior?
Select any HU which was planned to be issued or receipt but not yet processed.
It shall be possible to reverse that Issue/Receipt candidate.

In case of Issues, the reverse will delete the candidate (i.e. PP_Order_Qty table) and unlock the HU.
In case of Receipt, the reverse will destroy the planned HU and will delete the candidate.

**Comment by metas-lc** [comment]
IT
- reverse an issue: HU is unlocked, PP_Order_Qty deleted and hutatus still Active OK
- reverse a receipt: (no HUs to unlock), PP_Order_Qty deleted and hutatus is Destroyed OK

after you reverse an issue you can look back in issue HUs => it's there OK
