### ISSUE TITLE
Manufacturing Quickaction: Issue selected HU w/ TU Quantity parm

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#357]
### Is this a bug or feature request?
Feature request.
### What is the current behavior?
Currently, the user can only issue whole HU.
#### Which are the steps to reproduce?
Do an issue and try to issue only a certain amount of TU of the selected HU.
### What is the expected or desired behavior?
It shall be possible to select an HU (via Barcode or manually) and then issue only partially. The user can enter the qty of TU to be used.

**Comment by teosarca** [comment]
Update: this task is basically implemented and integrated.
But while implementing this i found out the "HU transform - split TUs out of an existing LU" is not working correctly for some cases. We will have to do more testing and create specific tasks to fix here and there.
Pls do a quick IT and let's identify what's working and what's not.

**Comment by metas-lc** [comment]
IT (partial)
1. go to manufacturing order and select a docu
2. press on issue/ receipt
3. select the co product and press on issue
4. select a TU as top level (e.g. paloxe) , press on Issue TUs (partial) and add a qty
=> Error: NoSelection...
=> shall not be able to partial issue it

Same happens if you select an LU with multiple TUs (Error: NoSelection)
here shall work

**Comment by teosarca** [comment]
Note to IT:
* please test issuing from:
** a LU
** a top level TU => not enabled
** a TU
** an aggregated TU
** a LU which contains TUs and aggregated TUs (no idea how to get that case easily :( )
** CU
** top level CU

* please do full regression on HU transformations

**Comment by metas-lc** [comment]
IT: partial issue:
** a LU 
=> Issue TUs partial is enabled. Add qty of TUs => works fine, both left and right side are updated. I can also issue normally OK

** a top level TU 
=> not enabled (cannot select Issue TUs partial), but i can issue normally OK

** a TU
=> Issue TUs partial is enabled. Add qty 1 => works fine, both left and right side are updated. I can't issue normally 
Server error
Issuing VHUs is not allowed
OK????

** an aggregated TU 
=> Issue TUs partial is enabled. Add qty of TUs => works fine, both left and right side are updated. I can't issue normally 
Server error
Issuing VHUs is not allowed
OK????

** a LU which contains TUs and aggregated TUs (no idea how to get that case easily :( )
- transform is not working... postponed for now

** CU 
=> not enabled (cannot select Issue TUs partial),  I can't issue normally 
Server error
Issuing VHUs is not allowed 
OK???????

** top level CU
=> not enabled (cannot select Issue TUs partial), i can issue normally BUT the line does not disappear from right side NOK

**Comment by teosarca** [comment]
Fixed another test case:
* press to receive an LU
* split out an LU 
* click on "Select all on this page"
* run "Create material receipt"
=> was throwing an error about "cannot convert String DocumentIDs to integer"

**Comment by teosarca** [comment]
Fixed another case:
* issue an top level CU
* reverse => ERROR
Also pls make sure we can reverse ANY of the issued HUs (ofc, if they were not already processed).

**Comment by teosarca** [comment]
@metas-lc i've fixed some cases on this issue.
about that "VHU error", i will also check with @metas-mk  if we still needed, because it would take some time to fix.

**Comment by metas-lc** [comment]
IT2

retested cases above. Most issues got fixed, including the other cases

remaining questions:
what should happen when you want to use "Issue selected HUs" on:
- a TU from an LU (aggregated or not). For now you get "Issuing aggregated TUs is not allowed. Please use the quick action which partially issues TUs"
- a VHU from a TU. For now you get "Issuing VHUs is not allowed"
