### ISSUE TITLE
Replace HU editor's Barcode quick action with Barcode filter

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#364]
### Is this a bug or feature request?
bug
### What is the current behavior?
in normal window or modal, the HU is not selected if you use barcode for an HU from another page
#### Which are the steps to reproduce?
1. open handling units window 540189, remember a value from 1st page, go on 2nd page and search with barcode for it 
=> hu did not appear/ not visibly selected (you can go back on 1st page - is not selected)
2. go to manufacturing order and select one, use issue /receipt, select the CO product and select Issue
3. select with barcode a HU from page 1 when you are for e.g. on page 2
=> not selected
4. also select an HU from page 1, go to page 2 => you cannot make issue because nothing is selected
### What is the expected or desired  #behavior?
~~1. barcode shall work no matter on which page is the HU~~
~~2. if you select an HU from page 1 and you go on page 2, the HU shall still be selected~~

Drop the Barcode quick action and replace it with a Barcode filter.
The filter shall  be rendered like the current barcode quick action (see https://github.com/metasfresh/metasfresh-webui-frontend/issues/742 ).

**Comment by teosarca** [comment]
Note to IT: before starting the ITs please make sure the frontend tasks which were linked here are delivered.
