### ISSUE TITLE
Make Permission change active without server cache reset

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#366]
### Is this a bug or feature request?
feature 

### What is the current behavior?
after changing permissions you have to reset server cache which only can be done by admin and requires one extra step

#### Which are the steps to reproduce?
1. change permission
2. follow: http://docs.metasfresh.org/installation_collection/EN/How_to_reset_server_cache.html

### What is the expected or desired behavior?
If a permission is changed (e.g. grant/revoke access to some window) it shall be propagated automatically without any cache reset.
The cache invalidation shall be distributed.
e.g. Edit permissions on Swing, they shall be automatically propagated to webui server

**Comment by teosarca** [comment]
Note to IT:
* full regression test on permissions, also try different roles
* full regression test on permissions requests (grand and revoke)
* try changing permissions in Swing and expect them to be instantly updated on webui. e.g.
** webui: open a window
** swing: deactivate the permissions for that window
** webui: refresh page => "No access" error shall popup
** swing: activate the permissions for that window
** webui: refresh page => you shall get back your page

**Comment by metas-lc** [comment]
IT
1. logged in with different roles => depending on what permissions they had, you could or couldn't access a window OK
(also checked this testcase:
browse AD_Elements which shall be visible only for SysAdm (https://w101.metasfresh.com:8443/window/151): => not allowed: OK
browse currencies: https://w101.metasfresh.com:8443/window/115 => visible, but readonly if Client=System: OK)

2. permission requests:
created new role, similar with Admin and made Sales Order (ad_window_access) inactive.
=> webui: could still see it in Menu (NOK will be solved in: https://github.com/metasfresh/metasfresh-webui-api/issues/382 )
=> swing: not visible in menu OK
Open sales order page in webui (using link directly)
=> error: no access OK
In swing, go to last 2 tabs:
=> there is a new entry in each, saying that you don't have permissions for this role on sales order
Press on grant permission button and on read write say NO
=> AD_Window_Access for sales order is Active and read write is on No
Open sales order in swing and webui
=> webui: you can add new/ edit NOK (will be solved in: https://github.com/metasfresh/metasfresh-webui-api/issues/380)
=> swing: readonly: cannot add new or modify OK
Go back to Permission request subtab and press again on grant permission, read write on Y 
=> AD_Window_Access for sales order is Active and read write is on Yes
=> webui: you can add new/ edit OK 
=> swing: you can add new/ edit OK
Go back to permissions request subtab and press on Revoke permission
=> AD_Window_Access for sales order is deleted
=> webui: (here i used logout/login this time) Sales order is in menu NOK (will be solved in: https://github.com/metasfresh/metasfresh-webui-api/issues/382)
=> swing: Sales order is missing from menu  OK
Go back to permissions request subtab and press on grant permission
=> AD_Window_Access for sales order is added back
=> webui: (here i used logout/login this time) Sales order is in menu  OK
=> swing: Sales order is in menu  OK

note: on swing you have to logout/login to see the changes. On webui is working directly - just refresh the page OK
