### ISSUE TITLE
adding role to user does not work

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#369]
### Is this a bug or feature request?
bug

### What is the current behavior?

> reason: "Composed primary key is not supported"

![image](https://cloud.githubusercontent.com/assets/16079655/26004712/0eeffafa-3737-11e7-952d-9f8ec76bf1f6.png)

#### Which are the steps to reproduce?
1. select user IT
2. add new role

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* adding new role to user working without errors or problems: OK
* selecting a suggested role / searching fo a role and selecting that both working fine: OK
* tested with user it (Systembenutzer) and another user (Systembenutzer=N): OK
