### ISSUE TITLE
backend: endpoint for creating a filtered view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#372]
At the moment, when the frontend filters a view, it simply calls "POST /rest/api/documentView/{windowId}" (like when it creates any other new view) and provides the filters in request body.

The problem with that is backend is not aware the new view is actually an already existing view but filtered.
We would need this information because backend shall preserve things like internal filters (aka sticky filters) .

So, we shall have a new endpoint, i.e. "POST /rest/api/documentView/{windowId}/{viewId}/filter" which shall create a new view, based on previous one (identified by path variables windowId and viewId) and which shall be filtered by the filters provided in request body.

Required for https://github.com/metasfresh/metasfresh-webui-api/issues/364

### Frontend task
https://github.com/metasfresh/metasfresh-webui-frontend/issues/740

### Note to IT
Case 1
* open a view, e.g. https://w101.metasfresh.com:8443/window/143
* try filtering by different criterias => shall work

Case 2
* open a view, e.g. https://w101.metasfresh.com:8443/window/143
* select an order and from there navigate to it's invoices or candidates or any other referenced documents
* try filtering in that view => shall work

**Comment by metas-lc** [comment]
IT
1. open a view, e.g. Sales Order (window/143)
2. try filtering by different criterias (date, date+time, string, id ) 
=> works
3. open the document, go to referenced documents, open invoice/material receipt/material receipt candidates
=> correct window opens
4. filter there too
=> filter is applied only on those documents you seen at step 3, which are already filtered (a filter on a filter)
