### ISSUE TITLE
Initial Setup Wizard does not open after switching language

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#373]
### Is this a bug or feature request?
bug

### What is the current behavior?
does not open after switching language

#### Which are the steps to reproduce?
1. log on and have german language
2. switch language to English
3. go to menu and search for "wiz"
4. click on "Initial Setup Wizard" 
5. NOK: nothing happens
6. click on Sales Order
7. NOK: Initial Setup Wizard opens

### What is the expected or desired behavior?
should open

**Comment by teosarca** [comment]
Cannot reproduce.
But anyways, this sounds like a frontend bug.
