### ISSUE TITLE
Adding Role for User w/o Org_access restricts access totally

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#375]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when a user has multiple proper Roles and you add one role w/o AD_Role_OrgAccess, then the user cannot login anymore.
#### Which are the steps to reproduce?
Activate the Role test_gh365webui for Admin. Try to log in.
### What is the expected or desired behavior?
Shall still be able to login with other valid roles.

**Comment by metas-lc** [comment]
IT
tried to log in with both Admin and other valid orgs => works
