### ISSUE TITLE
Don't show zoom-to for non-zoom reference Lists

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#377]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the zoom-to link is shown also for labels/ fields which have list reference. Pressing on those don't open a browser tab with the detail record.
#### Which are the steps to reproduce?
Open Manufacturing Order Window in WebUI and press on "Priority" Label.
### What is the expected or desired behavior?
There shall be no link to these records (bugfix for now).

**Comment by metas-lc** [comment]
IT
checked "Priority" from manufacturing order and "Product Type" from product (both have list ref)
=> there is no zoom in OK
