### ISSUE TITLE
Document changes: provide the validStatus and saveStatus only when changed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#378]
### Is this a bug or feature request?
Bug

### What is the current behavior?
The validStatus and saveStatus are provided almost all the time.
In some cases, because of that, the document changes list that is provided back to frontend is huge and the frontend on it's turn freeze chrome for a while (i.e. you are not able to close the browser tab).

#### Which are the steps to reproduce?
Try editing a role, e.g. https://w101.metasfresh.com:8443/window/111/1000055.
Try changing the name, or try activating/deactivating a window access or a task access or something.
Your browser tab will freeze.
Wait a (long) while and the chrome tab will work again.
If you inspect the response of the endpoint which was called to change the document, you will see that it has a huge amount of changes, almost all of them are only about valid status and save status.

### What is the expected or desired behavior?
Backend shall keep the response as small as possible.
It shall send only the valid and save statuses which really changed.

NOTE: might be that we also have to rethink when and how the valid and save status are changed.

**Comment by metas-lc** [comment]
Found this while testing another task:
- create a new purchase order
- add an empty line - no product (with add new)
=> line should be pink but it's not NOK
- refresh the page
=> the line was deleted and the document is not saved (reason:"child invalid") NOK

**Comment by metas-lc** [comment]
IT
retested testcase above => adding an empty line makes it pink and refreshing the page doesn't make it disappear OK
the rest tested on https://github.com/metasfresh/metasfresh-webui-api/issues/365
- small problem with editing included tabs when the header is inactive. Rest is fine.
