### ISSUE TITLE
Password Field not shown in User Window.

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#379]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Password Field is not shown in User Window, although 
#### Which are the steps to reproduce?
Open the window window/108/1000000 and see. The password field should be in between the email and search key field.
### What is the expected or desired behavior?
Show the field.

![image](https://cloud.githubusercontent.com/assets/13365687/26095540/4bfd24e2-3a1e-11e7-8a6e-9011908cbb64.png)

![image](https://cloud.githubusercontent.com/assets/13365687/26095525/41109f78-3a1e-11e7-97ca-0504fa94ae8b.png)

**Comment by teosarca** [comment]
Please click on IsSystemUser flag and  you will have it :)

![image](https://cloud.githubusercontent.com/assets/1244701/26107107/d24d4b94-3a50-11e7-81f9-82b1408ac2c0.png)

**Comment by metasnw** [comment]
@teosarca 
I am the cause of the confusion.
It is not shown in 5.9 and also the field login is missing:

![image](https://cloud.githubusercontent.com/assets/16079655/26111961/db480260-3a56-11e7-99e9-5706da10289a.png)

**Comment by metasnw** [comment]
@teo I started from a fresh db to create a migration script that enables password and login fields which are not displayed in 5.9.
Password field works fine but i cant get the login field to be displayed:
![image](https://cloud.githubusercontent.com/assets/16079655/26140246/e811a27e-3ad5-11e7-85f9-483e88e0fbf7.png)

![image](https://cloud.githubusercontent.com/assets/16079655/26140274/123203be-3ad6-11e7-8165-49b0ff051140.png)

**Comment by metasnw** [comment]
restarted webAPI but problem persists

**Comment by teosarca** [comment]
@metasnw  pls check which is the field's DisplayLogic.

**Comment by metasnw** [comment]
Mark showed me that the login field is already in advanced view and therefore is not shown in main view.
He created a script to show it in main view.

**Comment by metas-lc** [comment]
loging and password fields are shown OK
