### ISSUE TITLE
ZoomInto shall consider AD_Ref_List.AD_Reference_ID if any

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#381]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Zoom into is not considering AD_Ref_List.AD_Reference_ID.

#### Which are the steps to reproduce?
See https://github.com/metasfresh/metasfresh/issues/1543 .
Also you can test with manufacturing order's resource field which shall open the "Manufacturing resource" window and NOT "Resource" window.

### What is the expected or desired behavior?
If set, AD_Ref_List.AD_Reference_ID shall be considered.

**Comment by metas-lc** [comment]
IT
1. open Manufacturing window (53009), open a line
2. zoom in on Workflow => window 53005 opens (Produktion Arbeitsablauf)
3. in Manufacturing, zoom in on Resource => window 53004 opens (Produktions Ressource)
(rest of the fields open the correct windows)
OK
