### ISSUE TITLE
menu is not updating when you change permission

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#382]
### Is this a bug or feature request?
bug
### What is the current behavior?
menu is not updating when you change permission (e.g. inactivate/delete sales order window in AD_Window_Access)
#### Which are the steps to reproduce?
1. go to rolle window and select one
2. go to AD_Window_Access subtab and select sales order and inactivate it /or delete it
3. go to webui - refresh => window is still visible in menu NOK
(i even used logout/login and it was still visible)
### What is the expected or desired behavior?
window shouldn't be visible

**Comment by metas-lc** [comment]
IT
1. go to rolle window and select one
2. go to AD_Window_Access subtab and select sales order and inactivate it /or delete it
3. go to webui - refresh => window is not visible OK
4. activate it or create it back 
5. go to webui - refresh => window is visible OK

**Comment by teosarca** [comment]
quickly tested together with @metas-mk 
* in swing, edit role and change the Menu field
* in webui, open the menu => u still get the old one
* cache reset
* in webui, open the menu => u get the correct one

**Comment by metas-lc** [comment]
IT
1. went to swing, rolle, selected my rolle
2. on root menu node selected something else instead of menu (e.g. Verkauf)
3. went to webui and checked the menu (no cache reset) 
=> menu is made only by sales
4. go back in swing and set root menu node on Menu
5. go to webui to check 
=> normal menu is there
