### ISSUE TITLE
Purchase Order from Sales Order Parms not initially filled in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#386]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
When starting the action "Purchase Order from Sales Order" in WebUI, the parms are not filled in WebUI (in swing they are).
#### Which are the steps to reproduce?
Open window window/540196, select a sales order with defined vendor products and start the quickaction "Purchase Order from Sales Order". The parms are not filled initially.
### What is the expected or desired behavior?
Fill the parms initially.

![image](https://cloud.githubusercontent.com/assets/13365687/26126622/a34e618a-3a86-11e7-8db2-e33288413f6d.png)

**Comment by teosarca** [comment]
Same root problem as https://github.com/metasfresh/metasfresh-webui-api/issues/302

**Comment by metas-lc** [comment]
IT (swing and webui)
1.  created relations between 2 bpartners (x and y), added the bpartner (y) to product and created a new sales order for bpartner (x)
2. went to gear/actions, selected Purchase Order from Sales Order
=> fields are preset, but the mandatory fields are missing OK?
3. run the process 
=> got a message with Success
4. went to referenced documents
=> purchase order is there , for bpartner (y) OK
