### ISSUE TITLE
Products in Quick-/ Batchentry available although not on Pricelist

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#387]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When searching for a product in Quick entry/ Batch entry, then all products are available, also those which are not on a pricelist used in that document.
#### Which are the steps to reproduce?
Open Sales Order/ Purchase Order and choose a product which is not on the selected pricelist.
### What is the expected or desired behavior?
Only show the products which are available in the pricelist and valid.

**Comment by teosarca** [comment]
pls check if this is still open?

**Comment by metas-lc** [comment]
IT
1. purchase/sales pricelist (batch entry/ add new):
- product not on pricelist at all => you can't add it in order
- product on pricelist => you can add it in order
- product on pricelist but inactive => you can't add it in order

Note: if you just updated the pricelist (like deleted, added or inactivated the product) while you are on swing, you have to do a cache reset so you can see the changes on w101
