### ISSUE TITLE
grid view: select "ALL" support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#388]
### Is this a bug or feature request?
feature

### What is the current behavior?
At the moment, on a document view, you are able to select all documents on current page.

### What is the expected or desired behavior?
Backend shall support selecting the documents on ALL pages.
In this case the frontend shall send the "all" keyword instead of selected documents.

Frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/752

**Comment by teosarca** [comment]
Note to IT: pls wait and test the frontend task

**Comment by metas-lc** [comment]
IT
frontend tested: https://github.com/metasfresh/metasfresh-webui-frontend/issues/752 OK
regression tests on quick actions:
- jasper process works (e.g. bestellkontrolle in sales order, pricelist in busines partner)
- process that creates new document (e.g. purchase order from sales order in sales order, create invoice from billing candidates, creating shipments from shipment dispo)
- processes that also have buttons - checked both buttons and process (all process from Material Receipt Candidates and Manufacuring Order)
OK

Issue:
don't know if it's related (never tested this before): 
1. go to Material Receipt Candidates and close a row
=> if you open the document view all actions are shown (stuff like receive HUs) NOK
=> grid view: inactive actions are hidden (or readonly for buttons)
2. reopen the line
=> actions you can see all, on buttons they are still readonly NOK
3. try to use those actions while line is open
=>works 
4. try to use the actions while line is closed
=>Process error
Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
 Bitte leiten Sie diese Meldung an metas weiter: Assumption failure: receipt schedule shall not be closed: X_M_ReceiptSchedule[M_ReceiptSchedule_ID=1000724, trxName=<<ThreadInherited>>]

noticed that refreshing the page fixes the grid view part, but noticed that if you close a row and open the document, on actions you have "close row" no matter if you refresh and all actions are visible.
