### ISSUE TITLE
Zoom-Into error for subtab orderline

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#389]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Try to zoom in c_orderline from new Materialdispo.
#### Which are the steps to reproduce?
Open the Materialdispo, go to subtab "demanddetail" (1), open advanced edit, zoom-to orderline. error.
### What is the expected or desired behavior?
Allow to zoom-into c_orderline

```
Error: org.postgresql.util.PSQLException: ERROR: missing FROM-clause... 1
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "d1" Position: 72 SQL: SELECT C_Order_ID FROM C_OrderLine WHERE /* entity where clause */ ((d1.IsActive = 'Y')) AND /* key */ C_OrderLine_ID=? SQL params: [2621144]

```

**Comment by teosarca** [comment]
NOTE to IT:
* you can reproduce it on manufacturing order, advanced edit and there click on Order line link
* pls also check in other documents, clicking on fields which basically shall zoom into an included tab

![image](https://cloud.githubusercontent.com/assets/1244701/26159218/aa94e68a-3b26-11e7-98e2-84911df599c6.png)

**Comment by metas-lc** [comment]
IT
opened Bill of Materials and Manufacturing windows, select c_orderLine_id 
=> order (sales or purchase) window opened OK
