### ISSUE TITLE
Change advanced edit layout

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#390]
### Is this a bug or feature request?
feature request

### What is the current behavior?
Current Advanced edit layout is all fields in one column.

![image](https://cloud.githubusercontent.com/assets/1244701/26171128/7e88ad76-3b4c-11e7-97fe-53b8d17e843f.png)

#### Which are the steps to reproduce?
open any advanced edit

### What is the expected or desired behavior?
In advanced edit the fields shall be layout-ed exactly line in single document layout but where there are advanced fields they be shown.

And vice versa, the single document layout shall be layouted like the advanced edit but the advanced fields shall not be shown.

![image](https://cloud.githubusercontent.com/assets/1244701/26171286/13bb027c-3b4d-11e7-87d8-9b1d061db3ff.png)

**Comment by metas-lc** [comment]
IT
checked multiple windows (like order, inout, invoice, warehouse, product and so on)
on 1st tab opened in normal view, on 2nd tab on advanced edit, and compared the tabs
=> advanced: looks like normal, plus the advanced fields, which are shown under the common fields
=> normal: looks the same as it used too.. the advanced fields are hidden
OK
