### ISSUE TITLE
role: besides menu tree, allow configuring the sub-tree to be used

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#391]
### Is this a bug or feature request?
feature request

### What is the current behavior?
Only the menu tree can be configured

#### Which are the steps to reproduce?
Edit role

### What is the expected or desired behavior?
In Role, have another field for the menu folder which shall be considered as root of our webui menu.

![image](https://cloud.githubusercontent.com/assets/1244701/26175806/983f3680-3b5c-11e7-863b-15c58d88cbeb.png)

**Comment by metas-lc** [comment]
IT
- swing and webui: go to Role window and see new field: Root menu node OK
old field is Menu Tree
- to to a role and change both. For root menu node set CRM, and the other one some old Menu
- login with that role on webui => the menu is only with CRM OK
- login with swing => it's the old menu OK
