### ISSUE TITLE
barcode field is readonly

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#392]
### Is this a bug or feature request?
bug 
### What is the current behavior?
barcode field is readonly when you are on a row

#### Which are the steps to reproduce?
1. go to https://w101.metasfresh.com:8443/window/53009
2. select a line
3. select Issue/receipt (barcode) 
=> field is readonly

![barcodeee](https://cloud.githubusercontent.com/assets/16001666/26200574/69f38238-3bd7-11e7-89e2-fbde5bc5ba39.png)

### What is the expected or desired behavior?
make button readonly OR field editable

**Comment by teosarca** [comment]
Fixed, bug introduced by https://github.com/metasfresh/metasfresh-webui-api/issues/386

**Comment by metas-lc** [comment]
IT
works if you select a row, but doesn't work anymore if you don't select any
e.g. open https://w101.metasfresh.com:8443/window/53009 and use barcode directly
Error: java.lang.NullPointerException

**Comment by metas-lc** [comment]
IT
1. open https://w101.metasfresh.com:8443/window/53009
- Issue/ Receipt barcode without selecting any line => works and editable
- Issue/ Receipt barcode while selecting a line => works and editable
