### ISSUE TITLE
Manufacturing Issue/Receipt: cannot receive HUs

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#393]
### Is this a bug or feature request?
Bug

### What is the current behavior?
When trying the Receive HUs quick action you get something like "String document IDs cannot be converted to int: PP_Order_1000001"

#### Which are the steps to reproduce?
* manufacturing order
* Issue/Receipt
* try receiving on main product, try receiving on co/by product
=> error

### What is the expected or desired behavior?
The process shall be started

**Comment by metas-lc** [comment]
IT
1. created and completed new manufacturing order
2. selected it in grid view, press on issue/ receipt
3. received on main product and by product (LU + TU, TU)
=> worked fine
4. issued on the co product (receiving is readonly)
=> worked fine 
5. open the window in document view and go to actions, select issue/receipt
6. repeat steps 3 and 4
=> 3 worked fine
=> 4 issue panel didn't open. Created task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/766
