### ISSUE TITLE
Invoice marked as paid only in grid view

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#398]
### Is this a bug or feature request?
Bug.
### What is the current behavior?
A sales invoice that was paid is marked as paid in grid view, but not in single view.
#### Which are the steps to reproduce?
* Create a sales invoice
* Create a payment for it
* Check the invoice: grid view: paid is checked, open single view: paid is not checked
### What is the expected or desired behavior?
If the invoice is fully paid, it shall be marked as paid both in grid and single view.

**Comment by teosarca** [comment]
Side effect of https://github.com/metasfresh/metasfresh-webui-api/issues/19

**Comment by metas-lc** [comment]
tested in https://github.com/metasfresh/metasfresh-webui-api/issues/522 
works fine 
OK
