### ISSUE TITLE
Two sessions at once with two different roles

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#399]
### Is this a bug or feature request?
bug

### What is the current behavior?
if you have two sessions open to the same system with two different roles you get weird behaviour

#### Which are the steps to reproduce?
1. log on with role WEBUI 
1. log on with role admin 

not clear how to reproduce in detail.

### What is the expected or desired behavior?
either support this or avoid it

### Severity
was reported once until now. I think we just come up with a concept at one point

**Comment by teosarca** [comment]
Basically you cannot. There is one session per browser (ofc, if u are not using incognito mode).

**Comment by metasnw** [comment]
thx teo.
good. let me go back to the user how he got the point

**Comment by metasnw** [comment]
talked with user.
he could not reproduce it and I guess it was luck to get there.
basically we should test in this area as I assume login off not working reliably
