### ISSUE TITLE
minimum password length error message not displayed

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#400]
### Is this a bug or feature request?
bug

### What is the current behavior?
nothing is shown to the user
browser log says: "undiscovered error blabla"

#### Which are the steps to reproduce?
follow his manual BUT put less than 8 characters into password field:
http://docs.metasfresh.org/webui_collection/EN/NewUser.html

### What is the expected or desired behavior?
message is shown explaining to the user that he needs 8 characters at least

**Comment by teosarca** [comment]
Update:
* introduced process "Change my password" - available from profile window (also from User window) when you are on current logged in user
* introduced process "Change password" - available from User window, not available for current user (use the other process for that)
* TODO: take out the Password field from My profile and User windows

Note to IT:
* i did a massive refactoring around AD_User table => full regression / e2e test is needed

**Comment by teosarca** [comment]
Update 2: those 2 processes shall look like this:
![image](https://user-images.githubusercontent.com/1244701/27009958-0439d6e8-4ea3-11e7-94ac-db56c85131e1.png)
![image](https://user-images.githubusercontent.com/1244701/27009960-077b4e86-4ea3-11e7-8049-c207d0cf91e9.png)

**Comment by metas-mk** [comment]
Tested on w101. works as required. Closing/ Done.
