### ISSUE TITLE
Backend shall provide JSON document fields indexed by field's name

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#405]
### Is this a bug or feature request?
feature

### What is the current behavior?
Atm, the backend it's providing document fields as array.

#### Which are the steps to reproduce?
Check on of the following responses:
* getting document data (browse single document)
* patching a document (i.e. change some document fields)
* browse a view

### What is the expected or desired behavior?
In all responses, besides the "fields" property (to be deprecated in this task) we shall have "fieldsByName" property which will contain a map of fields indexed by their name.

This issue it's a sub-task of https://github.com/metasfresh/metasfresh-webui-api/issues/292

**Comment by metas-lc** [comment]
note for IT: if documents still work fine can be put in done after e2e

**Comment by metas-mk** [comment]
Tested. Works fine.
![image](https://cloud.githubusercontent.com/assets/13365687/26631216/51d170ce-460a-11e7-85a7-5528aa6e3dc2.png)
Frontend Issue will be tested in a few days after taking out the "fields" from backend.
