### ISSUE TITLE
Provide "size" to layout element

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#411]
Described here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/772

## Configuration
![image](https://cloud.githubusercontent.com/assets/1244701/26361342/6117463a-3fe3-11e7-8432-4b6981ae21ac.png)

![image](https://cloud.githubusercontent.com/assets/1244701/26361329/5119ee68-3fe3-11e7-9faf-e8e7100ed4ee.png)

**Comment by metas-mk** [comment]
Tested. Works nicely with current data. Done, closing.
