### ISSUE TITLE
Provide API for sorting included tab

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#412]
### Is this a bug or feature request?
feature

### What is the current behavior?
There is no way to sort an included tab

### What is the expected or desired behavior?
Endpoint [GET /rest/api/window/{windowId}/{documentId}/{tabId}](http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDataUsingGET_2) shall accept "orderBy" parameter.

Required fro https://github.com/metasfresh/metasfresh-webui-frontend/issues/781

**Comment by metas-lc** [comment]
IT
order by works in included tabs (also see frontend task) OK
