### ISSUE TITLE
Referenced Windows for Subtab Records

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#414]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to go deeper in Subtab Hierarchy than 1 Level.
#### Which are the steps to reproduce?
For example. Go to Business Partner Window and select the Vendor Tab. Try to go to Vendor Accounting from there.
### What is the expected or desired behavior?
Have the possibility on Tab Level to define windows that can be referenced from that tab. When the user then presses on the right mouse on that row, she/ he sees a list of referenced windows if available. The user can select one and similar to zoom-to the window opens in new tab already filtered.

![image](https://cloud.githubusercontent.com/assets/13365687/26455570/ee603ed8-416a-11e7-9234-d00ec2d42e16.png)

**Comment by teosarca** [comment]
NOTE: atm we  providing the referenced documents for all windows.
If it will turn out that there too many or it's not efficient/fast we will find a way to narrow them.

**Comment by metas-mk** [comment]
Tested. Works as required. Closing.
