### ISSUE TITLE
Notification for Vendor returns jumps to wrong window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#415]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Notification for Vendor returns jumps to the wrong window "Material Receipt" and returns a 404 error.
#### Which are the steps to reproduce?
Open Material Receipt Dispo. Do a Receipt. Do Correction for that Receipt. Do a Vendor Return. Go to Notification. Press on Vendor Return Notification. Window Material Receipt is opened w/ 404 error.
### What is the expected or desired behavior?
The Window for Vendor Return shall be opened.

![image](https://cloud.githubusercontent.com/assets/13365687/26484364/f15cd786-41f1-11e7-82f3-458376268231.png)

**Comment by teosarca** [comment]
fixed for customer and vendor returns.

**Comment by metas-lc** [comment]
IT
tried with both return to customer and return to vendor and works fine: if you select the notification it's opening the right window OK
