### ISSUE TITLE
AD_UI_Section's Name and Description shall be translatable

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#416]
### Is this a bug or feature request?
Feature

### What is the current behavior?
There is no way to translate the AD_UI_Section's Name and Description.

### What is the expected or desired behavior?
* AD_UI_Section's NAme and Description shall be translatable
* the name shall be provided as "title" to frontend

Frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/790

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
