### ISSUE TITLE
Disable zoom into string lookups until it's fixed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#418]
### What is the expected or desired behavior?
See See https://github.com/metasfresh/metasfresh-webui-api/issues/417 

For those lookups, the label shall not be clickable.

Note to IT:
* regression: make sure the "list references" are not zoomable

**Comment by metas-lc** [comment]
IT
can't zoom in on ad_language, but you can on other type of lists which are not strings OK
