### ISSUE TITLE
Star/ Bookmark a window/ process/ report and show in Quick Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#420]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the "Quick Menu" opened via Navigation Menu, shows a static selection of Menu entries.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
The User shall have the possibility to "star" a window. 

This is the API Issue for the frontend stuff, described here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/803

**Comment by teosarca** [comment]
NOTE: under the hood, consider using AD_TreeBar to store the "starred" windows.

**Comment by teosarca** [comment]
duplicate of https://github.com/metasfresh/metasfresh-webui-api/issues/425
