### ISSUE TITLE
Cant get default view after Zooming 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#423]
### Is this a bug or feature request?
bug

### What is the current behavior?
once you jumped in a window using: http://docs.metasfresh.org/webui_collection/EN/JumptoviaSidebar.html
there is no easy way to see all records again

workaround: close tab and open window freshly from menu

#### Which are the steps to reproduce?
1. partner window
2. jump via http://docs.metasfresh.org/webui_collection/EN/JumptoviaSidebar.html
3. into request window
4. NOK: tried to clear the filter: button is not shown
5. NOK: tried to reopen the window from the menu: records are still filtered

### What is the expected or desired behavior?
have a button to clear the filter and / or remove the filter when opening the window from menu again

**Comment by teosarca** [comment]
Shall be fixed by https://github.com/metasfresh/metasfresh-webui-frontend/issues/804
@metasnw  pls check if that would fulfill the requirements from here...
