### ISSUE TITLE
Implement picking window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#424]
i.e. alternative for Swing's Picking Terminal.

**Comment by teosarca** [comment]
UPDATE: implemented and integrated the Picking window prototype (WIP).

**Comment by metas-lc** [comment]
IT
swing:

1. go to picking terminal
=> first warehouse is selected by default

2. select a warehouse with multiple products
=> products and bpartners for the corresponding warehouse appear
=> products are aggregated per warehouse

3. select a product
=> bpartners and dates are filtered for it
=> qty of this product is per all bpartners and dates
=> date you see on the product is the first one (min)

4. select a bpartner
=> your product is still selected, and other products appear
=> qty of this product is per this bpartner and dates

5. select a date
=> qty of this product is per this bpartner and the date you selected
=> date on product line is updated with the one you selected

6. select bpartners, lines, dates in different order 
=> products and qtys, dates and bpartners update accordingly

7. press ok (then close)
=> picking opens for this amount only 

8. press on distribution pos
=> distribution pos opens for this warehouse and existing bpartners

9. press on shipper transportation 
=> shipper transportation window opens

10. press on inventory button
=> inventory window opens

11. create and complete a sales order and go back to picking terminal, select your warehouse
=> qty of your product is updated accordingly

12. select your bpartner a and date
=> qty from your order is on your product

13. select a warehouse and on barcode field write an HU vaue that is on that warehouse
=> your product is selected 

14. press ok, select a slot, press on hu editor
=> your HU (from barcode) is selected 

15. close and open another warehouse, enter the same barcode
=> nothing happens

webui

1. open window 540345
=> products are aggregated per warehouse

2. use filter for bpartner, date, product and warehouse
=> qty updated accordingly, depending on your filter

**Comment by teosarca** [comment]
Update:
* loading included lines when the root rows are loaded
* providing "expanded" flag to frontend: see https://github.com/metasfresh/metasfresh-webui-frontend/issues/835#issuecomment-306413536

Note to IT: nothing really to test (besides regression on views, but that will be part of e2e test too)

**Comment by teosarca** [comment]
TODO: introduce "collapsible" flag, see https://github.com/metasfresh/metasfresh-webui-frontend/issues/835#issuecomment-307301886

**Comment by metas-rc** [comment]
Results of IT

Nothing to test atm. Will be included in e2e when we have the complete functionality

**Comment by teosarca** [comment]
TODO: shall be added to "release-TODO", but not this release!

**Comment by teosarca** [comment]
Closing it. Work shall be continued on #469
