### ISSUE TITLE
API support for bookmarking menu items

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#425]
See frontend concept: https://github.com/metasfresh/metasfresh-webui-frontend/issues/803

API changes:
1. introduce "PATCH /rest/api/menu/node/{nodeId}" with
```
{
  "favorite": true|false
}
```
The call shall return all menu nodes which were changed

2. All API calls which return menu nodes will provide "favorite" property for each node

3. Deprecated "GET /rest/api/menu/node". Please use "GET /rest/api/menu/node/{nodeId}"

4. Deprecated "GET /rest/api/menu/path". Please use "GET /rest/api/menu/node/{nodeId}/path".

5. "GET /rest/api/menu/root" now supports "favorites" boolean parameter. If set to "true" it will return the menu tree containing only favorites.

See http://w101.metasfresh.com:8081/swagger-ui.html#/menu-rest-controller

**Comment by teosarca** [comment]
Note to IT:
* pls test when the frontend task is implemented
* regression: add to/remove from favorites on Swing (the left side panel from main window). To make sure it's working pls do: add to favorites, logout/login and check, remove from favorites, logout/login and check

**Comment by damianprzygodzki** [comment]
@teosarca i've checked PATCH endpoint, and i see that as one and only has other structure of payload. Can we just use standard

```
[
  {
    "op": "replace",
    "path": "string",
    "value": {}
  }
]
```
instead of:
```
{
  "favorite": true
}
```

**Comment by teosarca** [comment]
@damianprzygodzki  if that would make the frontend efficient, for me it's not a problem to accept the data in that format.

But on the other side, somehow feels not right because:
* basically that { op:replace, path:"...", value:"..." } is specific for documents PATCHing where everything is dynamic and you don't know which are the properties to set.
* would make the (swagger) documentation unclean (or uncomplete) because when you will browse it you will not know what things you can update.

I am very interested in what are your reasons for suggesting this change?

**Comment by damianprzygodzki** [comment]
> I am very interested in what are your reasons for suggesting this change?
Consistency and usage of the same endpoint generator for every patch in the application.

> basically that { op:replace, path:"...", value:"..." } is specific for documents PATCHing where everything is dynamic and you don't know which are the properties to set.

The assumption for that object in patch payload was to do not patch single properties because the PATCH method is to patch whole object, not just updated property.

And it will be great to keep the assumption to every PATCH in the project.

**Comment by teosarca** [comment]
ok, will change it

**Comment by cadavre** [comment]
> { op:replace, path:"...", value:"..." } is specific for documents PATCHing

The truth is: { op:replace, path:"...", value:"..." } is specific for **ALL** PATCHing

This is "REST done right" rule for PATCH HTTP method. :)

**Comment by teosarca** [comment]
@cadavre  ok, got it. thanks.

**Comment by cadavre** [comment]
> PATCH /menu/node/{nodeId} shall accept List<JSON**DocumentChangedEvent**>…

Now I see. ;)

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Closing/ Done.
