### ISSUE TITLE
internal: JSONDocument - drop "fields" array field

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#426]
Basically this task shall cleanup stuff after https://github.com/metasfresh/metasfresh-webui-api/issues/405 .
Also will make https://github.com/metasfresh/metasfresh-webui-frontend/issues/773 testable.

**Comment by teosarca** [comment]
Note to IT: test the frontend task.

**Comment by metas-lc** [comment]
was already tested: https://github.com/metasfresh/metasfresh-webui-frontend/issues/773
