### ISSUE TITLE
internal: Include AD_Language in layout ETags

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#428]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* open a sales order
* open advanced edit for that sales order => remark the field names language
* close the advanced edit
* in another window, go and change the language: https://w101.metasfresh.com:8443/settings
* in your first window try opening the advanced edit again 
=> it shall use the current language but usually (when it's coming from cache) it's using the previous language

### What is the expected or desired behavior?
Language switching shall be instant.

NOTE: this is a follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/402

**Comment by teosarca** [comment]
Update:
1. introduced optional "lang" parameter to all "GET layout" endpoints. Of the "lang" parameter is specified then that language will be used to fetch the layout. If not set, the session language will be used.
2. the language is incorporated in the resulting ETag.

Note to IT:
* before this change, no matter what language you picked, the advanced edit layout is provided using the language of the first retrieval (because it's cached on browser and the ETag was not language dependent)
* after this change:
** after browser cache expires (atm it's 1min by default) the layout using the right language is provided
** to make this really instant i think the frontend shall append the "lang=xx_XX" parameter. A frontend task will be created for that.

**Comment by teosarca** [comment]
TODO: after https://github.com/metasfresh/metasfresh-webui-frontend/issues/819 is implemented, enable the "metasfresh.webui.http.use.AcceptLanguage" by default.

**Comment by metas-lc** [comment]
IT
1. open an already existing sales order, advance edit, close advance edit 
=> in advance edit language is DE
2. in other tab open settings, change language to EN
3. go back to sales order tab (do not refresh the page), open advance edit again
=> language is still DE. NOK should be EN
(if you refresh the page then it works)

![lang](https://user-images.githubusercontent.com/16001666/26976107-2807f434-4d2b-11e7-884d-041c9a30d1b8.png)

**Comment by teosarca** [comment]
If that's the case then it's OK.
Will work as you described when this will be implemented: https://github.com/metasfresh/metasfresh-webui-frontend/issues/802#issuecomment-307410903

**Comment by metas-mk** [comment]
Tested after Implementation of https://github.com/metasfresh/metasfresh-webui-frontend/issues/802#issuecomment-307410903. Works very nice. The Language settings are instantly w/o refresh. Closing/ Done
