### ISSUE TITLE
Create request from BPartner not working

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#431]
### Is this a bug or feature request?
Bug

### Which are the steps to reproduce?
* pick a bpartner, e.g. https://w101.metasfresh.com:8443/window/123/2156481
* run "Create request" process
![image](https://cloud.githubusercontent.com/assets/1244701/26739598/1431d178-47db-11e7-97fb-7710f524ea1e.png)

**Comment by teosarca** [comment]
Found the reason: the R_Request.R_Request_ID's reference is "Table direct" instead of ID.
It seems it was changed lately.
![image](https://cloud.githubusercontent.com/assets/1244701/26739634/43ebe6d8-47db-11e7-9903-6ec9a4a15852.png)

**Comment by metas-lc** [comment]
IT
tested together with https://github.com/metasfresh/metasfresh/issues/1687. Creating a new request works OK
