### ISSUE TITLE
Generic swimlane maintenance w/ cards and including details

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#432]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no possibility to have a "Project" dashboard in metasfresh, that allows to add "cards" and move between lanes.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
It shall be possible to create dashboards with flexible amounts of lanes. Each lane has a certain name (status). The user can add "cards" to the lane. Depending on which data the card takes, the information on the cards can be different on each dashboard. These can be uses for our new Project Management or to make sales funnel visible.

First rough ideas. Details to be described.

**Comment by teosarca** [comment]
Implemented on https://github.com/metasfresh/metasfresh-webui-api/issues/441
