### ISSUE TITLE
Show Manufacturing Order number in window header

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#433]
### Is this a bug or feature request?
feature

### What is the current behavior?
cant see it anywhere
![image](https://cloud.githubusercontent.com/assets/16079655/26824504/f6f51cbc-4ab1-11e7-9ac0-5cbb7067e486.png)

#### Which are the steps to reproduce?
1. select PP Order
1. click Issue / receive

### What is the expected or desired behavior?
Show it after label "PP Order Issue / Receipt" <docno>

**Comment by teosarca** [comment]
I think we shall solve it in a generic way.
i.e. think about introducing caption, description and other fields to view layout

**Comment by teosarca** [comment]
Update: now, API provides the "description" in view result:

![image](https://user-images.githubusercontent.com/1244701/27010170-0ad4cc2a-4ea7-11e7-90a1-4eef3c0da60d.png)

**Comment by metas-lc** [comment]
IT
checked description in view result =>  it's there: depending on your language is doctype and doc number OK 
 frontend part will be tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/862
