### ISSUE TITLE
Provide endpoints for user avatar and user settings

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#434]
see https://github.com/metasfresh/metasfresh-webui-frontend/issues/802#issuecomment-306415788

**Comment by teosarca** [comment]
API changes:
1. endpoint [GET /rest/api/userSession](http://w101.metasfresh.com:8081/swagger-ui.html#!/user-session-rest-controller/getAllUsingGET) returns following extra fields (if availble!):
* fullname -> the full name that shall be displayed near avatar
* email -> might not be needed for now
* avatarId -> the avatar ID. In case it's present, the avatar image can be fetched using [GET /rest/api/image/{avatarId}](http://w101.metasfresh.com:8081/swagger-ui.html#/image-rest-controller). Please remark that the endpoint has 2 new parameters: maxWidth and maxHeight. The frontend shall use them to get the image in optimum size.

**Comment by teosarca** [comment]
Functional changes:
* the login BL is now using user/role DAO and services (no longer SQL)
* on login, the AD_User.AD_Language is used if available.
* in webui, when changing the language it is automatically persisted to database (in AD_User.AD_Language field).

**Comment by teosarca** [comment]
Note to IT:
* pls also do full regression on Swing login, different roles, different users.

**Comment by metas-mk** [comment]
Tested together with Avatar Frontend Issue. Works nicely as required. Closing/ Done.
