### ISSUE TITLE
document: stale tab events shall be sent to document's websocket endpoint

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#435]
### Is this a bug or feature request?
feature request

### What is the current behavior?
Tab stale events are sent as part of document patch response.
e.g.
![image](https://user-images.githubusercontent.com/1244701/26865254-7f0d8d84-4b64-11e7-8d5f-a6bdce4f1dbb.png)

#### Which are the steps to reproduce?
Create a new sales order, complete the sales order.

### What is the expected or desired behavior?
As discussed on https://github.com/metasfresh/metasfresh-webui-frontend/issues/795#issuecomment-306444024 , we shall send the tab stale events to document's websocket endpoint .

As a temporary solution, until frontend is ready, we shall send the tab stale events as part of the PATCH response too.

**Comment by teosarca** [comment]
API changes:
* all endpoints which are returning document changes, e.g. [GET /rest/api/window/{windowId}/{documentId}](http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDataUsingGET_4), will return the "websocketEndpoint" property if available. That's the document's websocket endpoint where frontend shall listen for changes. The frontend shall connect to it when the document is opened and it shall disconnect from it as soon as the document is not in the scope anymore.
* while patching the document, if some tabs become stale then:
** the stale info will be provided in reponse (like now, but that's a temporary solution which we will take it out and use only websocket notifications)
** the backend will send a websocket event which is similar with the one from PATCH response but only with relevant data. e.g.
```
{  
   "windowId":"143",
   "id":"1003649",
   "includedTabsInfo":{  
      "1":{  
         "tabid":"1",
         "stale":true,
         "allowCreateNew":true,
         "allowDelete":true
      },
      "2":{  
         "tabid":"2",
         "stale":true
      }
   },
   "timestamp":"2017-06-07T09:53:58.193+03:00"
}
```

**Comment by metas-rc** [comment]
Results of IT

Nothing to test
