### ISSUE TITLE
Manufacturing Order Issue not possible after barcode filtering

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#436]
### Type of issue
Bug 

### Current behavior
cant issue after filtering

### Expected behavior
I should see the same actions as if I am not filtering and just selected one HU

### Steps to reproduce
1. open https://w101.metasfresh.com:8443/window/53009
1. search for pp order 630004 
1. click on issue/receive
1. click on p002735 and then issue
1. click on filter and select barcode
1. enter 1008965
1. NOK: issue is missing
![image](https://user-images.githubusercontent.com/16079655/26869058-55cab5d0-4b6b-11e7-8d8b-8599aeee49ac.png)

**Comment by teosarca** [comment]
Note to IT:
Please test in [Handling unit window](https://w101.metasfresh.com:8443/window/540189) but also in receipt hu editor, Manufacturing Issue/Receipt -> Issue HUs included view.

Test cases like:
Case 1
* filter (by Barcode for example)
* issue the HU => the HU shall vanish
* clear the filter => the HU shall not be there neither

Case 2
* filter
* split out some HUs => the newly created HUs shall be on the bottom of the list
* clear filter => the newly created HUs shall be present in the list

**Comment by metas-lc** [comment]
IT

1. original testcase works fine - issue selected HU is there and works when you filter a barcode (also when you don't use barcode)

- HU
2. handling unit window, use barcode and transform
=> hus are shown while filtered and also without filter OK
3. handling unit window - create material receipt on a planning HU 
=> nothing happens. OK?

- Receipt
4. receipt candidates - Receive HUs (multiple LUs) - filter for HU, create receipt, then remove the filter
=> your Hu is among the others, but readonly and Active (not planning) OK
5. filter again for the same HU - dispse => HU disappears OK
6. remove the filter => HU didn't appear back OK
7. create material receipt + dispose without a filter => works the same OK
8. filter for another LU, transform it into 3 LUs
=> All 4 LUs are shown while using the filter OK
9. remove the filter 
=> all LUs you have are shown, including the transformed ones OK

- Manufacturing
10. go to Manufacturing order, issue/receipt, select the co product and issue
11. filter, transform LU into multiple LUs => LUs are there OK
12. issue one of those LUs => that LU is removed
13. remove the filter => the LUs that are not issued are shown, the LU which you issued is still gone OK
