### ISSUE TITLE
minor: error for wizard with no picture

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#438]
### Is this a bug or feature request?
bug
### What is the current behavior?
error only in preview when you open wizard
#### Which are the steps to reproduce?
1. open the wizard for the first time (you don't have any picture set)
=> error:"Internal Server Error"
exception:"java.lang.IllegalArgumentException"
message:"Invalid image id"
path:"/rest/api/image/-1"
status:500
timestamp:1496830758421
### What is the expected or desired behavior?
no errors

**Comment by teosarca** [comment]
The solution would be to return NULL instead of -1 in case the AD_Image_ID is missing.
On the frontend side we shall make sure the API is not called for null value.

**Comment by teosarca** [comment]
but this is a uber minor thing, we can live with it for now :)

**Comment by metas-dh** [comment]
tested in e2e, in release: no error anymore, neither displayed in WebUI frontend nor in inspect: OK
