### ISSUE TITLE
qty not updated in pp order

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#439]
### Is this a bug or feature request?
bug
### What is the current behavior?
delivered qty is not updated in pp order
#### Which are the steps to reproduce?
1. go to manufacturing order and create a new pp order
2. set all mandatory fields, save and complete
3. go to grid view, select your pp order and issue/receive
4. receive and issue the HUs and do planning complete
5. go back to your pp order and select advanced edit 
=> delivered qty is 0
=> check the swing - the qty there is updated with what you received. Or check in database qtydelivered
### What is the expected or desired behavior?
qtydelivered to be updated

**Comment by teosarca** [comment]
Side effect of https://github.com/metasfresh/metasfresh-webui-api/issues/19

**Comment by metas-lc** [comment]
other cases to test: 
- qty delivered in shipment schedule not updated after shipment is created
- qty picked in shipment schedule not updated after picking

**Comment by metas-lc** [comment]
1. delivered qty in manufacturing is set OK
2. qty shipped in shipment schedule is updated after shipment is created OK
3. qty picked in shipment schedule is updated after picking OK
