### ISSUE TITLE
Implement Board API

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#441]
Implement API for https://github.com/metasfresh/metasfresh-webui-frontend/issues/833

#### Note IT
Nothing to test by IT team.
Assigned to @teosarca, he will take care.
Do not put in Done

**Comment by teosarca** [comment]
update: delivered the first, prototype. rolled out on w101.
See http://w101.metasfresh.com:8081/swagger-ui.html#/board-rest-controller

**Comment by teosarca** [comment]
query used to check the content of a given dashboard (here is for C_Order):
```
SELECT 
  a.WEBUI_Board_Lane_ID
, a.Record_ID
, (SELECT NULLIF (TRIM(C_Order.DocumentNo), '') FROM C_Order WHERE C_Order.C_Order_ID=r.C_Order_ID ) AS card$caption
, u.AD_User_ID AS card$user_id
, u.Avatar_ID AS card$user_avatar_id
, u.Name AS card$user_fullname
, a.WEBUI_Board_RecordAssignment_ID
, a.SeqNo
 FROM WEBUI_Board_RecordAssignment a
 INNER JOIN C_Order r ON (r.C_Order_ID =a.Record_ID)
 LEFT OUTER JOIN AD_User u ON (u.AD_User_ID = r.UpdatedBy)
 WHERE 
 a.WEBUI_Board_ID=1000000
 AND r.IsActive='Y'
--  AND Record_ID=1003649
order by a.WEBUI_Board_Lane_ID, a.SeqNo
```

**Comment by metas-rc** [comment]
Results of IT

Nothing to test. It will be tested with frontend

**Comment by teosarca** [comment]
Closing. Future work shall be done on follow-up tasks.
