### ISSUE TITLE
Make remaining UI components translatable

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#443]
### Is this a bug or feature request?
feature

Frontend Issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/861

## What is the current behavior?
lot of components not be translated and therefore remain static if you change the language

### grid buttons
- add new
- batch entry
![image](https://user-images.githubusercontent.com/16079655/26980899-c71e52c2-4d33-11e7-870a-f76487adcd07.png)

### context menu
- actions
- actions text if there are no actions
- settings
- logout

![image](https://user-images.githubusercontent.com/16079655/26981095-63d5a8fe-4d34-11e7-87a7-fc7a176715d9.png)

### menu search
![image](https://user-images.githubusercontent.com/16079655/26981148-84ec62f8-4d34-11e7-9ae8-234aa4ebe3a7.png)

### Tooltips
![image](https://user-images.githubusercontent.com/16079655/26981167-8f51bd24-4d34-11e7-8801-d09420a74d97.png)

### Page Record Navigation
![image](https://user-images.githubusercontent.com/16079655/26981181-a089014c-4d34-11e7-8e88-bb6ddfc1e8f3.png)

### attachment note
![image](https://user-images.githubusercontent.com/16079655/26981192-aa313a84-4d34-11e7-8a46-ef8451b4483c.png)

### Filter labels
![image](https://user-images.githubusercontent.com/16079655/26981217-b53b87e0-4d34-11e7-81b4-b2816f8d6746.png)_

### Settings
![image](https://user-images.githubusercontent.com/16079655/26981548-cd96477a-4d35-11e7-8136-d666ff319afb.png)

#### Which are the steps to reproduce?
1. set language to de_DE
1. open sales order window
1. NOK: buttons are "add new"

### What is the expected or desired behavior?
buttons shall be translatable in one way

**Comment by metas-mk** [comment]
**Avatar Profile:** Settings and Logout
![image](https://user-images.githubusercontent.com/13365687/26981383-3b2ffd86-4d35-11e7-8859-d0804b7c7cc6.png)

**Comment by teosarca** [comment]
Introduced /i18n/messages endpoint which will return a map of "message key" to "message text" pairs, translated into current language.
The frontend shall fetch this map once and then use it as a message bundle.

----
Internally, the webui API server will return all AD_Messages which start with "webui." prefix.
In the resulting map, the prefix will be cut out.
e.g.
If you define an AD_Message=webui.test1, MsgText="first test", then the endpoint will return:
```
{
  "test1": "first test"
}
```

**Comment by metas-mk** [comment]
Tested. Works mostly as described. Any further missing Translations will be done in further Issues. Future Implementations will be done via message caption w/ prefix "webui." per requirement. Closing/ Done.
