### ISSUE TITLE
Make Dashboard Translatable

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#444]
### Is this a bug or feature request?
feature

### What is the current behavior?
![image](https://user-images.githubusercontent.com/16079655/26982411-9f3cf31c-4d38-11e7-8a5c-6a257a2bdd50.png)

#### Which are the steps to reproduce?
see above 

### What is the expected or desired behavior?
be able to translate all the labels

**Comment by teosarca** [comment]
Update: KPI field and Dashboard item are now translatable.
But, atm, you are able to do that just from Swing.

**Comment by metas-lc** [comment]
IT
swing -> kpi dashboard -> item -> item translation -> Update the translations -> webui -> login with other language -> items are translated
(note that you need to do cache reset to see the changes)
