### ISSUE TITLE
Truncate WEBUI_ViewSelection tables on startup

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#447]
### What is the current behavior?
WEBUI_ViewSelection and WEBUI_ViewSelectionLine tables tend to grow quickly.
This could affect the overall performance when browsing views.

e.g. on w101, "select count(1) from T_WEBUI_ViewSelection" returns "11 315 919" rows!

### What is the expected or desired behavior?
On webui server start, cleanup those temporary tables.
This might be contradictory to https://github.com/metasfresh/metasfresh-webui-api/issues/35 but at the moment we are not persisting the view state anyways (like filters, sticky filters, order bys etc).
When we will do that, then we might come up with a different cleanup strategy.

**Comment by metas-mk** [comment]
Tested after the last rollout on w101.
"select count(1) from T_WEBUI_ViewSelection" gave 5701 results.

Done/ Closing.
