### ISSUE TITLE
Key Field Missing in KPI Field Translation Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#449]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Window for KPI Fields Translation does not show any data because of a missing key field.
#### Which are the steps to reproduce?
Open the Window and see: https://w101.metasfresh.com:8443/window/540348
### What is the expected or desired behavior?
Add the Key Field and check if the Window is now loading data properly.

![image](https://user-images.githubusercontent.com/13365687/27009471-cead2470-4e8f-11e7-95ee-1638cf4e2cb1.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
window works fine. Data loaded properly
