### ISSUE TITLE
Introduce URL widget type

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#452]
### Is this a bug or feature request?
feature request

### What is the current behavior?
There is no URL specific widget type. All URLs are rendered as text components.

#### Which are the steps to reproduce?
Check, for example, the BPartner window: https://w101.metasfresh.com:8443/window/123/2155894

### What is the expected or desired behavior?
See https://github.com/metasfresh/metasfresh-webui-frontend/issues/865

**Comment by metas-mk** [comment]
Tested. Works as required. When Clickable as Link the URL is opened in new Browser Tab.
