### ISSUE TITLE
Outbound Mail endpoint prototype

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#456]
Prototype outbound email endpoint for https://github.com/metasfresh/metasfresh-webui-frontend/issues/836

#### Note to IT
* full regression test on Swing EMail sending is needed (also open it from different documents)
* full regression test on text templates is needed
* besides those regression tests, pls test the frontend task

**Comment by teosarca** [comment]
API changes (please check swagger for details)
* /mail/templates endpoint which returns a list of key/value templates which user can pick from a dropdown and apply them to current email
* to apply a given template you shall use the regular PATCH operation with path="templateId", value={ templateId : templateName }

API is ready for frontend implementation

**Comment by teosarca** [comment]
Changed the mail configuration on w101:
```sql
update AD_SysCOnfig set Value='-' where name='org.adempiere.user.api.IUserBL.DebugMailTo';
update AD_Client set SMTPHost='localhost', IsSmtpAuthorization='N' where AD_Client_ID in (0, 1000000);
update AD_User set EMail='it@w101.metasfresh.com' where AD_User_ID=2188223;
/*
select name, value from AD_SysCOnfig where name='org.adempiere.user.api.IUserBL.DebugMailTo';
select AD_Client_ID, SMTPHost, IsSmtpAuthorization from AD_Client;
select AD_User_ID, login, Email from AD_User where Login='it';
select * from AD_MailBox;
*/

```

**Comment by teosarca** [comment]
Tested on w101, using only the mail API:

1. Create a new email for current user, having C_Order_ID=1005626 in context
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
   "documentPath": { "windowId":143, "documentId": 1005626} \ 
 }' 'http://w101.metasfresh.com:8081/rest/api/mail'
```

2. Send the email (assuming mandatory email fields like To was filled automatically on previous request).
Also assuming the emailId returned on previous call is 1".
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: */*' 'http://w101.metasfresh.com:8081/rest/api/mail/1/send'
```

**Comment by metas-rc** [comment]
To be tested together with https://github.com/metasfresh/metasfresh-webui-frontend/issues/836 when it is finished as well.
