### ISSUE TITLE
Debug endpoint to track websocket outbound events

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#458]
### Is this a bug or feature request?
Feature

### What is the current behavior?
At the moment there is no way to check what websocket events were sent from server.

### What is the expected or desired behavior?
We shall expose some debug endpoints which would help the developer or tester test what websocket events where sent from server.

**Comment by teosarca** [comment]
Now we are providing following endpoints:
* http://w101.metasfresh.com:8081/swagger-ui.html#!/debug-rest-controller/setWebsocketLoggingConfigUsingGET - used to enable the websocket outbound events logging
* http://w101.metasfresh.com:8081/swagger-ui.html#!/debug-rest-controller/getWebsocketLoggedEventsUsingGET - used to get currently logged events

**Comment by teosarca** [comment]
Note to IT: nothing to test but please remember those endpoints because might help you when testing webui and you have to do triage to check if that's an backend or frontend websocket problem.

**Comment by metas-rc** [comment]
Results of IT
* Nothing to test.
