### ISSUE TITLE
make editing partner address less error prone

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#460]
### Is this a bug or feature request?
Feature request

### Current behavior
you can add address without filling the mandatory fields leaving the complete partner record in an unchangeable state

### Expected behavior
1. have cancel button
1. do not allow the user to click done if mandatory fields are not filled
1. do not save the record in cache if mandatory fields are missing

#### Which are the steps to reproduce?
1. go in partner window
1. add new address
1. click directly to done
1. try to add a bank account

### What is the expected or desired behavior?
to be defined by Mark ;-)

**Comment by metasnw** [comment]
@metas-mk feel free to just close the issue if we have this on the agenda or other issues anyway

**Comment by metasnw** [comment]
same problem appears in role window but there it is even worse. 
the cached but not saved to db record is at the end of a very long list (e.g. tab windows) and there is no user can find out why he cant add more permission records

**Comment by teosarca** [comment]
@metasnw  atm, when u press new to create a new address and then directly press done, you get warning.
Isn't that sufficient?

![image](https://user-images.githubusercontent.com/1244701/32159097-acd58dcc-bd54-11e7-8041-a82d42e0ed59.png)

**Comment by metasnw** [comment]
@teosarca: doesnt work. users ignore / dont see / understand the message

**Comment by teosarca** [comment]
note: this issue shall be solved by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1308

**Comment by metasnw** [comment]
I tested https://github.com/metasfresh/metasfresh-webui-frontend/issues/1308 and I think its much better now. 
so I consider this to be solved
