### ISSUE TITLE
Action Transform To existing HU does not refresh

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#461]
### Is this a bug or feature request?
Bug
### What is the current behavior?
In Material Receipt Window when using Transform Action "To existing HU", the UI after processing the action does not refresh. The CU still seems to be "outside" the HU. As soon as you do the material Receipt, the HU presentation is refreshed and the CU are shown "in the box".
#### Which are the steps to reproduce?
Create a few Material Receipt Dispo lines. Select them all and do CU receive. In HU editor select 1 Line and Add to new TU. Then select the next line and add to existing HU.
### What is the expected or desired behavior?
The HU presentation shall refresh after each action of Transform "To existing HU".

**Comment by metas-ts** [comment]
cherry-picked into the branches `release` and `release_gh1306`

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* Create a few Material Receipt Dispo lines. 
* Select them all and do CU receive. 
* In HU editor select 1 Line and Add to new TU. 
* => OK: Refreshed: The product appears below the TU
* Then select the next line and add to existing HU.
* => OK: Refreshed: The second product appeared below the first product in the TU.


Regression: Created receipt with all the HUs . All correct.
