### ISSUE TITLE
Dashboard editing API prototype

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#462]
API prototype for https://github.com/metasfresh/metasfresh-webui-frontend/issues/905

**Comment by metas-rc** [comment]
Results of IT

Nothing to test. This is work in progress ( teo)

**Comment by metas-ts** [comment]
cherry picked this one to `release` 
only commit https://github.com/metasfresh/metasfresh-webui-api/commit/fc5edb308a32e43dd4678892d1f0c1e8b37951e9 manually...had trouble with the github-api this time

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15releasetest

This was covered by the latest tests about KPI widgets, etc. Moving this to done
