### ISSUE TITLE
filter is ignored when doing mass invoice or shipping

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#463]
### Is this a bug or feature request?
bug

### What is the current behavior?
filter is ignored

#### Which are the steps to reproduce?
1. open Rechnungskandidaten
1. filter for an order partner
1. Do Not select the lines you want to invoice
1. select action invoicing
1. NOK: all partners are invoiced and the filter is ignored

Happens also with shipping.

Workaround: select the lines you want to process.

### What is the expected or desired behavior?
only the lines resulting from the filter settings should be enqueued

**Comment by teosarca** [comment]
Note to IT:
* pls do full regression on webui view filtering: open different windows, filter by different things AND(important) call different processes.
* check HU editor
* check manufacturing Issue/Receipt

**Comment by teosarca** [comment]
hotfixed: if there is no selection and your are in webui => FAIL
on Swing shall behave as before

**Comment by metasnw** [comment]
IT on w101 for shipping and invoicing is fine
system shows "no Selection" error when no lines are selected and avoids the problem

**Comment by metas-ts** [comment]
cherry-picked this fix into the `release`branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/184/
