### ISSUE TITLE
Dashboard API: unify get available kpis/targetIndicators endpoints

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#464]
Instead of
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/getKPIsAvailableToAddUsingGET
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/getTargetIndicatorsAvailableToAddUsingGET

Provide only http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/getKPIsAvailableToAddUsingGET which shall return all available KPIs.
It shall accept "firstRow" and "pageLength" parameters (optional).
Each returned JsonKPI shall have "widgetTypes" property, e.g.
```
"widgetTypes" : ["KPI", "TargetIndicator"]
```

This is a followup of https://github.com/metasfresh/metasfresh-webui-api/issues/462
Required for https://github.com/metasfresh/metasfresh-webui-frontend/issues/905

#### Note to IT
Pls test the frontend task.

**Comment by metas-rc** [comment]
Tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/905
IT OK
