### ISSUE TITLE
Provide Endpoint w/ entry selections for given Breadcrumb

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#465]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Breadcrumb Navigation in Frontend receives the whole Bookmarks Menu Tree for the from API.
#### Which are the steps to reproduce?
Open Inspector, press on breadcrumb and see.
### What is the expected or desired behavior?
The API shall provide only the needed entries for the breadcrumb.

Example:

![image](https://user-images.githubusercontent.com/13365687/27383036-7bbf3968-5689-11e7-8183-35cd3e49a9e6.png)

![image](https://user-images.githubusercontent.com/13365687/27383042-8180aa4e-5689-11e7-8569-5cc8ae9e0bfc.png)

**Comment by metas-rc** [comment]
Moving to done.
Fronend followup created: https://github.com/metasfresh/metasfresh-webui-frontend/issues/979
