### ISSUE TITLE
board API: GET board/{boardId}/card?cardIds

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#467]
Implement "GET board/{boardId}/card?cardIds" endpoint which shall return requested cards, indexed by cardId.

This is a follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/441
Required for https://github.com/metasfresh/metasfresh-webui-frontend/issues/833

#### Note to IT
nothing to test

**Comment by metas-rc** [comment]
Moving task to Done.
