### ISSUE TITLE
Fix user full name in Avatar

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#468]
### What is the current behavior?
The name is displayed as "Last name, First name".

#### Which are the steps to reproduce?
![image](https://user-images.githubusercontent.com/1244701/27440525-bc777944-5773-11e7-991d-61ed2e404ab0.png)

### What is the expected or desired behavior?
It shall be "FirstName<space>LastName".

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
