### ISSUE TITLE
Cache image endpoint

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#470]
### Is this a bug or feature request?
feature request

### What is the current behavior?
Images are not cached at all.

#### Which are the steps to reproduce?
Just open your user profile and look for GET /rest/api/image/{imageId} calls.

### What is the expected or desired behavior?
browse cache/etag support.

**Comment by metas-mk** [comment]
Tested. The server sends a 304 status back to frontend "No changes". The image is not transmitted. Optimum would be if the Image would be directly served from Browser Cache "size (from disk cache)". Will create a low prio follow-up Issue for that. Closing this one. Done.
