### ISSUE TITLE
Dashboard API: specify position when adding a new KPI/target indicator

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#474]
see https://github.com/metasfresh/metasfresh-webui-frontend/issues/905#issuecomment-310672360

**Comment by metas-ts** [comment]
cherry-picked into `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/187/

**Comment by metas-rc** [comment]
See results of frontend IT https://github.com/metasfresh/metasfresh-webui-frontend/issues/905#issuecomment-310672360

Results of IT

Tested on mf15releasetest

Adding and removing KPI widgets works correcty in webui.
Stress-tested and had no problems either.
