### ISSUE TITLE
Sticky empty Filter in modal overlay.

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#481]
### Type of issue
Bug
### Current behavior
Currently, when opening the modal overlay Material Receipt window from material Disposition, an empty Sticky Filter is shown.
### Expected behavior
Shall not be shown for these filtered modal overlays, because the filter was set by the underlying selection in the main window and needed in the workflow.
### Steps to reproduce
Open window/540196, select a line and press Quickaction to open the Handling Unit Editor modal overlay.

![image](https://user-images.githubusercontent.com/13365687/27648183-056ce454-5c2e-11e7-9878-08012b68104d.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


when opening the HUEditor for a selection( e.g. material receipt candidates row) there is no filter observed in the inspection: OK
