### ISSUE TITLE
backend: refactor sticky filters

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#485]
Refactor view sticky filters as described in https://github.com/metasfresh/metasfresh-webui-frontend/issues/948

**Comment by teosarca** [comment]
rolled on w101

**Comment by teosarca** [comment]
as reported here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/948#issuecomment-313040703

it seems it does not work

**Comment by metas-ts** [comment]
just verified that the latest commit was already in the `release` branch

**Comment by metas-lc** [comment]
IT
tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/948
