### ISSUE TITLE
dashboard: support "position" when PATCHing a dashboard item

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#486]
### Is this a bug or feature request?
Feature request

### What is the current behavior?
Following PATCHing endpoints does not support "position" path:
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/changeKPIItemUsingPATCH
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/changeTargetIndicatorItemUsingPATCH

### What is the expected or desired behavior?
Those endpoints shall support "position" because this is how the frontend was delivered.

NOTE:  it seems the frontend it's not used the endpoints which were previously built to change KPI or target indicators order. I think we shall deprecated/remove those endpoints:
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/changeKPIsDashboardUsingPATCH
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/changeTargetIndicatorsDashboardUsingPATCH

### Note to IT
Test the frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/905

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Frontend IT went fine. Moving to done.
