### ISSUE TITLE
Wrong widget Type for Date-Range in Process Parameter

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#491]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Process Parameter Date-Range is not set properly in Process Parm Action Widgets
#### Which are the steps to reproduce?
Open Window Contract. Select a line. Open Action Menu and start the Action.
### What is the expected or desired behavior?
Shall have a Date Range for "Lieferzeitraum"

![image](https://user-images.githubusercontent.com/13365687/27850628-341ba006-6156-11e7-97a2-f38124652a46.png)

**Comment by metas-mk** [comment]
Belongs to this frontend issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/981

**Comment by teosarca** [comment]
update:
* introduced "DateRange" widget type
* exchanged value has following format:
```
{ "from":"2017-09-15T14:19:07.434+03:00", "to":"2017-09-15T14:19:07.434+03:00" }
```

**Comment by teosarca** [comment]
note to IT:
* wait for frontend task
* until the frontend task is not ready, wherever we have date range process parameter, that parameter won't be displayed by the frontend because atm the frontend does not recognize "DateRange"

**Comment by metas-lc** [comment]
IT
open window Contract, go to actions - create new contract
=> Anfangsdatum has widgettype DateRange and it's with value and value to OK
