### ISSUE TITLE
Functionality to add Actions for Subtab Data

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#492]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not able to add Actions to Subtab data/ rows.
#### Which are the steps to reproduce?
Open the window/540112/. In Action menu there is one action available. In Swing Client there are further Actions available for the included Subtab.
### What is the expected or desired behavior?
We need a possibility to also start actions for the Subtab. Ideas are

This issue belongs to https://github.com/metasfresh/metasfresh-webui-frontend/issues/982
Wait for decision there first pls.

**Comment by teosarca** [comment]
duplicate of https://github.com/metasfresh/metasfresh-webui-api/issues/495
