### ISSUE TITLE
API: Functionality to add Actions for Subtab Data

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#495]
### Is this a bug or feature request?
Feature Request.
### What is the expected or desired behavior?
Belongs to https://github.com/metasfresh/metasfresh-webui-frontend/issues/982
This Issue is for the Endpoint implementation and exposure.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
was already tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/982 OK
