### ISSUE TITLE
String document IDs cannot be converted to int Handling Unit Editor

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#496]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when selecting a CU in Handling Unit Editor an error occurs.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Open HU Editor w/o Filtering. Select the first CU Line. Error.

![image](https://user-images.githubusercontent.com/13365687/28153780-9fd31e80-67a7-11e7-915a-4ab6b0de7a3f.png)

### Note to IT:
Needs full regression tests on each window/view/modal which is about HUs and quick actions.
e.g.
* handling units stand alone view: https://w101.metasfresh.com:8443/window/540189
* receipt schedules (receive HU + transformations and stuff)
* manufacturing issue/receipt (issue, receipt etc)

**Comment by metas-lc** [comment]
IT
- Handling Units editor
=> selecting a CU which stands alone, on TU, on TU and LU => no errors
(in some places - not w101 - i still get old "row does not support attributes")

- receipt schedule
=> CU on TU and LU: "row does not support attributes"
=> CU on TU: no errors
=> single CU: no errors

- manufacturing
=> receive/issue HUs: 
=> CU on TU and LU: "row does not support attributes"
=> CU on TU: no errors
=> single CU: no errors

(i'll check if we need a task for attributes. As it's not in task's scope i'll close this one)
