### ISSUE TITLE
Return HUs to Customer action is not working

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#498]
### Is this a bug or feature request?
bug
### What is the current behavior?
Return HUs to Customer action is not working on webui
#### Which are the steps to reproduce?
(might be that step 4 is enough. You just need a complete shipment)
1. create a new sales order, add a product with TU, complete
2. go to picking terminal and pick your product
3. go to lieferdispo and create inout from gear(actions), using the TUs you picked on step 2
4. go to inout, actions - Return HUs to Customer => not working
"Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:Assumption failure: Parameter instance is not null"
(from swing it works)
### What is the expected or desired behavior?
an hu editor shall open with your HUs

**Comment by metas-rc** [comment]
This task was closed by mistake. 
It is not fixed yet.

**Comment by metas-rc** [comment]
I am moving it backk in TODO

**Comment by metas-rc** [comment]
Cloding because the bug was already solved in  https://github.com/metasfresh/metasfresh/issues/2142
