### ISSUE TITLE
Record_ID  not found for IsSOTrx = "N"

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-api#505]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* zooming into a record always wants to open the sales side window even if the record itself is IsSOTrx = "N"
#### Which are the steps to reproduce?
* Create a purchase order, complete it. Send an e-mail for it
* Open the linked Document Outbound.
* Click on the record ID
![image](https://user-images.githubusercontent.com/16001442/28272807-42840dcc-6b15-11e7-880e-c53b8d184b30.png)

=> 404 not found => NOK
* the window it tries to open is for Sales Order

![image](https://user-images.githubusercontent.com/16001442/28272826-5093ccc2-6b15-11e7-8963-23a3b05d8a59.png)

### What is the expected or desired behavior?
* The record window shall open for the correct IsSOTrx

**Comment by teosarca** [comment]
test case on w101: https://w101.metasfresh.com:8443/window/540170/1000905

**Comment by metas-rc** [comment]
I found another bug and I think it's related.

This time, the field points to an order, which is Purchase Order (IsSOTrx = "N") .
When clicking it I also get 404 not found and the URL is for Sales Order window.

The window where I found this is "Manufacturing Order"
Go to https://w101.metasfresh.com:8443/window/53009/1000023 , open the Advanced edit and get to the field"Purchase Order". Click and check.

**Comment by metasnw** [comment]
had the same problem also in the windows wareneingangsdisposition and invoice disposition.
also the relations from partner are wrong.
seems that webui does not differenciate between issotrx Y / N

**Comment by metas-lc** [comment]
IT
1. Zoom into material receipt, from material receipt candidate (single view), included tab=> working, OK 
2. Zoom into purchase order, from material receipt candidate (single view) => working, OK

**Comment by metas-ts** [comment]
cherry-picked to the `release` branch
