### ISSUE TITLE
view: accept included referencing documents when creating a new view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#506]
### Is this a bug or feature request?
FR

### What is the current behavior?
http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/createViewUsingPOST endpoint shall accept included document as "referencing".

e.g.
```json
{
"documentType":"540325",
"viewType":"grid",

"referencing":{
  "documentType":"540321",
  "documentId":"2008396",
  "tabId":"1",
  "rowIds":["2002141"]
},
"filters":null
}
```

Required for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1041

### Note to IT
Please test the frontend task.

**Comment by metas-lc** [comment]
IT
tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1041
