### ISSUE TITLE
DocumentIdsSelection.stream() and other methods shall work with "ALL"

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#509]
### Is this a bug or feature request?
feature

### What is the current behavior?

currently those methods will throw
```java
IllegalStateException("method not supported for ALL selection")
```

When called with `DocumentIdsSelection.ALL`

### What is the expected or desired behavior?

`DocumentIdsSelection.ALL` should be usable seamlessly

**Comment by teosarca** [comment]
Closing this task because there is nothing to be solved on DocumentIdSelection.stream() but it shall be solved by IView implementations.

In case of PickingSlotView, it was fixed here: https://github.com/metasfresh/metasfresh-webui-api/commit/5fdb2486e474871e0e14f467c38d4e75755d8bc7
