### ISSUE TITLE
Problems with Sales Opportunities Board

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-api#511]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
1) The cards that are added do not dissapear directly from the list of " Add cards" 

![image](https://user-images.githubusercontent.com/16001442/28324094-4485701a-6be3-11e7-9960-a8129d5fcfba.png)

* After clicking somewhere else then again on "Add cards" , they are no longer in the list.

![image](https://user-images.githubusercontent.com/16001442/28324136-64bccefa-6be3-11e7-8923-aa96e89e3711.png)

2) After all the cards are added, pressing on Add Cards leads to an exception.

![image](https://user-images.githubusercontent.com/16001442/28324250-82368192-6be3-11e7-904c-9f7ad501ffd1.png)

* The message is: 
> Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Assumption failure: fixedOrderList not empty"

#### Which are the steps to reproduce?

*As in the pictures above

### What is the expected or desired behavior?
* List of cards to add shall be directly updated, because we are not allowed to add the same card more than once.
* Add new shall not throw exception

**Comment by teosarca** [comment]
Note to IT: to be tested after the frontend task is fixed: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1066 (i.e. websocket events will be handled on frontend side).

**Comment by metas-lc** [comment]
IT
1. cards are disappearing as you add them OK
2. when you open add cards you don't get any error message. You get an empty list where it sais "There are no detail rows. You can create them in this window."
