### ISSUE TITLE
Support HU transform from HU window

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#514]
### Is this a bug or feature request?
Feature request

### What is the current behavior?

Current problem:
* often there are more than 100 M_HUs shown in the wewbui HU window
* if the transform process is selected with a TU or CU, then the action "TU to existing LU" resp. "CU to existing TU" are available.

Now, the problem is that aparently, the auto-complete widget that we enjoy in a generic window is not available in the process parameter window. That means that we only have a (truncated) list which might or might not contain the target LU resp. TU we want to select.

#### Which are the steps to reproduce?

Try is in master: you will get an exception because the java process coase tries to look up and load all LUs resp. TUs and a deeper part of the system (i.e. `HUEditorViewBuffer_HighVolume`) rejects to load more than 100 items at once.

I also experimented and changed the processes `M_TU_HU_ID` and `M_LU_HU_ID` parameters as follows
* autocomplete=>Y
* new validation rule to just show TUs resp LUs

Result: is get still a list of HUs for each respective parameter; no typeahead/autocomplete widget

### What is the expected or desired behavior?

I need an auto complete widget. it shall work like the ones we have in generic windows (e.g. to select an M_Product for an order line)

Other alternative we considered: only provide the transform process if there are less than 100 HUs in the currentl selection. This won't work because if the user wants to put a TU onto an LU, they would both need to be in that selection. That's not practical. The target HUs can't be resprcited by the view's selection; the user needs to scan the physical HU's ID and therefore select is as process parameter

**Comment by metas-mk** [comment]
@metas-ts 
about 

> Now, the problem is that aparently, the auto-complete widget that we enjoy in a generic window is not available in the process parameter window.

We are talking about this widget, right? It's available in general.

![image](https://user-images.githubusercontent.com/13365687/28449893-01f8a980-6de4-11e7-95db-1611b5e3aef3.png)

**Comment by metas-ts** [comment]
@metas-mk @teosarca 
Mark and I compared the AD_Process_Params from 
WEBUI_M_HU_Transform => M_LU_HU_ID
and
RV_Fresh_PriceList => C_BPartner_ID

no significant differences..
* C_BPanter is mandatory and has a default value set, and C_BPArtner_ID doesn't neew an AD_Reference_Value, because it's the actual table's PK
...but afaiu there are no "real" diffeerences between the two

**Comment by metas-lc** [comment]
IT
(don't know if the errors i found are related with this task)

0. General 
1. HU IDs in HU Editor are autocomplete

I. Receipt Candidates

1. Receipt Candidates - Receive HUs (receive 3 LUs each with 1 TU)
2. select a TU - transform, use TU on existing LU
=> only the LUs you have opened are available to choose OK
3. Open the line again on CUs only
4. put some on TUs and leave some out
5. select the CU line and use transform, CU on existing TU
=> only the TUs you have opened are available to choose OK
6. open hu editor with e.g. 120 LUs, each with 1 TU on each
7. select a TU, press on transform
8. select an action => error NOK

Error: Failed invoking private de.metas.ui.web.window.datatypes.LookupValuesList...
Server error
Failed invoking private de.metas.ui.web.window.datatypes.LookupValuesList de.metas.ui.web.handlingunits.process.WEBUI_M_HU_Transform.getActions() using [Ljava.lang.Object;@27e84f61
(note: also tryed with 100 LUs and it works...the available actions in transform just load slow)

II. HU Editor

1. go to HU Editor end select a random TU, use transform to put it on an existing LU
=> you can search for your LUs value, moves fast OK
=> but you can also select a TU. Is that OK? you get the following error
Error: Ihr Test hat einen...
Server error
Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
 Bitte leiten Sie diese Meldung an metas weiter: Error: parentPIItem==null for parentHU=X_M_HU[M_HU_ID=1000691, Value=1000691, trxName=<<ThreadInherited>>] and piOfChildHU=X_M_HU_PI[M_HU_PI_ID=2002659, Name=IFCO 6410, trxName=<<ThreadInherited>>]
 
2. go to HU Editor end select a random CU, use transform to put it on existing TU
=> you can also choose an LU but you get this error
Error: Ihr Test hat einen...
Server error
Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
 Bitte leiten Sie diese Meldung an metas weiter: Error: Param 'tuHU' does not have one 'MI' item; tuHU=X_M_HU[M_HU_ID=1000000, Value=1000000, trxName=<<ThreadInherited>>]
 is that OK?
 
 Select a TU => error
 Error: org.postgresql.util.PSQLException: ERROR: null value...
Server error
org.postgresql.util.PSQLException: ERROR: null value in column "m_hu_id" violates not-null constraint Detail: Failing row contains (1000000, 1000000, 2017-08-09 17:51:35+02, 2188223, Y, null, 1000029, null, null, null, 2017-08-09 17:51:35+02, 2188223, 2017-08-09 17:51:35+02, TRANSFORM_LOAD, null, null, null, 1000697, null, P, 1002026, null, 2005577, -10). SQL: INSERT INTO M_HU_Trace (AD_Client_ID,AD_Org_ID,Created,CreatedBy,EventTime,HUTraceType,IsActive,M_HU_Trace_ID,M_HU_Trx_Line_ID,M_Product_ID,Qty,Updated,UpdatedBy,VHU_ID,VHUStatus) VALUES (1000000,1000000,TO_TIMESTAMP('2017-08-09 17:51:35','YYYY-MM-DD HH24:MI:SS'),2188223,TO_TIMESTAMP('2017-08-09 17:51:35','YYYY-MM-DD HH24:MI:SS'),'TRANSFORM_LOAD','Y',nextval('m_hu_trace_seq'),1002026,2005577,-10,TO_TIMESTAMP('2017-08-09 17:51:35','YYYY-MM-DD HH24:MI:SS'),2188223,1000697,'P') RETURNING M_HU_Trace_ID

III. Issue

1. manufacturing order -> co-product -> issue
2. select a TU and use transform
=> you can choose from every active HU (like you would be in HU Editor). Is that wanted?
=> also, you can use LU and TU at the same time, like in Hu Editor cases

**Comment by metas-lc** [comment]
Recap NOKs:

1. Receipt Candidates - Receive HUs >= 120 LUs (1 TU each) -> select a TU -> transform -> select action => error
Failed invoking private de.metas.ui.web.window.datatypes.LookupValuesList...
Server error
Failed invoking private de.metas.ui.web.window.datatypes.LookupValuesList de.metas.ui.web.handlingunits.process.WEBUI_M_HU_Transform.getActions() using [Ljava.lang.Object;@27e84f61

2. go to HU Editor end select a random TU, use transform to put it on an existing LU
=> you can also select a TU. and if you select a TU, you get the following error
Error: Ihr Test hat einen...
Server error
Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter: Error: parentPIItem==null for parentHU=X_M_HU[M_HU_ID=1000691, Value=1000691, trxName=<>] and piOfChildHU=X_M_HU_PI[M_HU_PI_ID=2002659, Name=IFCO 6410, trxName=<>

3. same as last step, but CU on TU
=> Error: Ihr Test hat einen...
Server error
Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter: Error: Param 'tuHU' does not have one 'MI' item; tuHU=X_M_HU[M_HU_ID=1000000, Value=1000000, trxName=<>]

4. (this is a question pending answer)
Issue -> use transform -> put tu on existing LU -> you can select from  all active LUs. OK? or we wanna see only those which are open, there, in the ISSUE?

**Comment by teosarca** [comment]
not sure if this is up2date. Pls check it.

**Comment by metas-lc** [comment]
1. could not reproduce
2. i can still choose a "no packing item" and i get "Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Error: parentPIItem==null for parentHU=X_M_HU[M_HU_ID=1000031, Value=1000031, trxName=<<ThreadInherited>>] and piOfChildHU=X_M_HU_PI[M_HU_PI_ID=2002659, Name=IFCO 6410, trxName=<<ThreadInherited>>]"
path:"/rest/api/process/ADP_540763/1007674/start"
3. same Server error
Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
 Bitte leiten Sie diese Meldung an metas weiter: Error: parentPIItem==null for parentHU=X_M_HU[M_HU_ID=1000058, Value=1000058, trxName=<<ThreadInherited>>] and piOfChildHU=X_M_HU_PI[M_HU_PI_ID=2002659, Name=IFCO 6410, trxName=<<ThreadInherited>>]


for all 3 i created followup https://github.com/metasfresh/metasfresh-webui-api/issues/753
