### ISSUE TITLE
Default Filter for Documents "Target Document Type" does not work

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#517]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, it is not possible to define and use a default filter for Target Document Type Fields in WebUI
#### Which are the steps to reproduce?
Provided a testcase in window Open Window https://w101.metasfresh.com:8443/window/167
### What is the expected or desired behavior?
Target Document Type shall work as Filter in WebUI Windows.

![image](https://user-images.githubusercontent.com/13365687/28492245-cc0e0460-6eff-11e7-8fa3-dd0aa7e6dac3.png)

**Comment by teosarca** [comment]
cannot reproduce: opened https://w101.metasfresh.com:8443/window/167
but looks fine:
![image](https://user-images.githubusercontent.com/1244701/28493444-337f378e-6f20-11e7-91e3-e72050ad6d88.png)

**Comment by metas-mk** [comment]
checked again. confirmed. does not appear anymore. thanks. closing/ done.
