### ISSUE TITLE
Picking prototype (v6)

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#518]
### Is this a bug or feature request?
Feature
### What is the current behavior?

this is a follow up from #503 

* implement "unprocessing" of processed `M_Picking_Candidate` records
* on "pick HU" the HU editor with prefiltered HUs shall open (very very similar to what happens at "action issue" in manufacturing)
* implement HU locking similar with Mfg Issue/Receipt (need to talk with teo)
* fix #496 String document IDs cannot be converted to int Handling Unit Editor
* fix #508 UC constraint violation when filtering in picking window (can't reproduce)
* no open/close "flickering" (mark) when switching between packagables (frontend) metasfresh/metasfresh-webui-frontend#1038
* support/use dynamic picking-slot assignment
  * assignment (filtering for assignable slots) works
  * *unassignment is part of the a later iteration* (this iteration is about the "picking" side). But note we already have a feature of automatically unassigning when the shipment is created

**Comment by metas-ts** [comment]
**Done wrt original description**

* implement "unprocessing" of processed `M_Picking_Candidate` records
* assignment (filtering for assignable slots) works

**Also done**
* fix: pick to new hu didn't work properly (hu was just created)
* add i18n messages if a process is not available
* support picking from many shipment schedules (`M_Packageables`) into one picking slot
* M_ShipmentSchedule_QtyPicked is updated and HUs are set to "picked" when the picking candidates status is set "processed" (shipments can be generated at this point)
* HUs are added to picking slot queue when the picking candidates status is set "closed" (i.e. picking window is closed)

**To be clarified**
* on "pick HU" the HU editor with prefiltered HUs shall open (very very similar to what happens at "action issue" in manufacturing)
* implement HU locking similar with Mfg Issue/Receipt (need to talk with teo)
* fix #496 String document IDs cannot be converted to int Handling Unit Editor
* fix #508 UC constraint violation when filtering in picking window (can't reproduce)
* no open/close "flickering" (mark) when switching between packagables (frontend) metasfresh/metasfresh-webui-frontend#1038

**Comment by metas-lc** [comment]
IT
1. picking regression: don't know if the NOK is related. Please check https://github.com/metasfresh/metasfresh-webui-api/issues/503

2. webui picking

**Comment by metas-lc** [comment]
6. was changed and doesn't work like this anymore. Plus, that error doesn't appear when you pick OK
10. unprocessed worked on an active HU. Could not make a planning one OK
14. as soon as you process a picked hu, the HU becomes picked, and then you can do inout OK
15. this changed. See testcases from this task https://github.com/metasfresh/metasfresh/issues/2740 OK

**Comment by teosarca** [comment]
amen, scnr
