### ISSUE TITLE
ispaid flag is not displayed after paying an invoice

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#522]
### Is this a bug or feature request?
bug

### What is the current behavior?
paying an invoice is stored in the db but is not displayed

#### Which are the steps to reproduce?
1. create invoice
1. create incoming payment for that invoice
1. check field "paid" in invoice window
1. NOK: its not ticket
1. workaround: do a server cache reset

### What is the expected or desired behavior?
should be displayed without server cache reset

**Comment by teosarca** [comment]
https://github.com/metasfresh/metasfresh-webui-api/issues/19 again :(

**Comment by metas-lc** [comment]
closing this task. Was solved by https://github.com/metasfresh/metasfresh-webui-api/issues/19
