### ISSUE TITLE
Webui bug: Element Group primary is not respected

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-api#523]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* I found a case when the UI Style "primary" is not respected in an Element Group
#### Which are the steps to reproduce?
* Go to window Customer return, find an entry with Handling Unit assignments, open advanced edit for the HU Assignments:

![image](https://user-images.githubusercontent.com/16001442/28679457-f5599c4e-72fb-11e7-9e13-8306fe23e66b.png)

### What is the expected or desired behavior?
* The orimary should be respected ( the background should be white)

**Comment by teosarca** [comment]
Checked now and seems to be OK.
e.g. https://w101.metasfresh.com:8443/window/53097/1004233

looks like this:

![image](https://user-images.githubusercontent.com/1244701/28735810-af9738c0-73ef-11e7-8478-0314cd987623.png)

**Comment by metas-lc** [comment]
IT
i could reproduce: https://w101.metasfresh.com:8443/window/53097/1003905
Handling Units Assignment tab -> anvanced edit
