### ISSUE TITLE
error reappears after you changed window

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#533]
### Is this a bug or feature request?
bug
### What is the current behavior?
if you receive an error and move to another windows, it reappears each time
#### Which are the steps to reproduce?
1. open purchase order, create a new one, or use https://w101.metasfresh.com:8443/window/181/1005834
2. go to referenced documents and select Receipt candidates
3. select the product line and use Drucken Produkteinlieferung
=> you get an error for no printer OK
4. press back (to get back to purchase  order)
=> same error appears NOK
### What is the expected or desired behavior?
Error should not appear on every window you go

![print error](https://user-images.githubusercontent.com/16001666/29072806-f1aaa1f6-7c51-11e7-8074-5a20a584fa33.png)

**Comment by teosarca** [comment]
frontend issue.
https://github.com/metasfresh/metasfresh-webui-frontend/issues/1150
