### ISSUE TITLE
Implement endpoint for document cloning

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#54]
aka the Copy with details from our Swing client.

**Comment by teosarca** [comment]
Needed for https://github.com/metasfresh/metasfresh-webui-frontend/issues/96

**Comment by teosarca** [comment]
Note to IT:
* to test the actual task, pls wait for the frontend task
* besides that, regression is uber important, i.e. copy with details shall work for:
** order (sales, purchase)
** invoice (sales, purchase)
** BOM
** Role
** GL Journal/Batch

**Comment by teosarca** [comment]
(moved from https://github.com/metasfresh/metasfresh-webui-frontend/issues/1164#issuecomment-327421845)

IT
I. Sales order: OK
1. create a new sales order, add all mandatory fields
2. change all the dates, so it won't be today
3. set a reference, a dropshipment bpartner
4. add 2 products, set an attribute for one and for the other one let it empty, set HU for one and the other one "no packing item", change the price for one and the other one leave it like it is
5. complete the order
6. go to actions, select Clone
=> new sales order opens on the same tab
=> status draft, with 2 lines of product (no TU line)
=> all the fields were copied (bpartner, products, attributes, dropship, packages) besides: dates (all set on today), reference (empty), price (was taken from pricelist) 
7. complete the order => TU line is added 

II. purchase order OK??
1. create a new purchase order, add all mandatory fields
2. change all the dates, so it won't be today, also add tageslot
3. set a reference, a dropshipment bpartner
4. add 2 products, set an attribute for one and for the other one let it empty, set HU for one and the other one "no packing item", change the price for one and the other one leave it like it is
5. complete the order
6. go to actions, select Clone
=> new sales order opens on the same tab
=> status draft, with 2 lines of product (no TU line)
=> all the fields were copied (bpartner, products, attributes, dropship, packages, tageslot) besides: dates (all set on today, availability was empty), reference (empty), price (was taken from pricelist) 
7. complete the order => TU line is added 
.
.question: Availability Date was not copied.. while on swing was. OK??

![availabilitydate](https://user-images.githubusercontent.com/16001666/30117005-a93f6f54-9327-11e7-9d52-64c7ae1f864b.png)

III. sales invoice NOK?
1. create a sales invoice for a sales order (with multiple lines, product and TU)
2. clone this invoce
=> all fields are copied as they are (including date, reference)
=> document is draft
=> lines can change order (products first, TUs after) and they keep their prices
3. create a new sales invoice manually, add a product line and change the price
4. clone it
=> all fields are copied as they are (including date, reference)
=> document is draft
=> line doesn't keep it's price (on swing it does) NOK??

![price](https://user-images.githubusercontent.com/16001666/30121564-b72ffec8-9334-11e7-859d-24ceb9b7f1d6.png)


IV. purchase invoice
1. create a purchase invoice for a purchase order (with multiple lines, product and TU)
2. clone this invoce
=> all fields are copied as they are (including date, reference)
=> document is draft
=> lines can change order (products first, TUs after) and they keep their prices
3. create a new purchase invoice manually, add a product line and change the price
4. clone it
=> all fields are copied as they are (including date, reference)
=> document is draft
=> line keeps it's price

About step 2: i couldn't reproduce on swing an invoice creation with TUs first and products after


V. BOM NOK (probably it's related with the fact that you have to add the document no manually)
```
Error: org.postgresql.util.PSQLException: ERROR: duplicate key...
Server error
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "ppproductbomunique" Detail: Key (ad_client_id, value)=(1000000, P002737_AB Alicesalat 250g) already exists. SQL: INSERT INTO PP_Product_BOM (AD_Client_ID,AD_Org_ID,BOMType,BOMUse,CopyFrom,Created,CreatedBy,C_UOM_ID,DocumentNo,IsActive,M_Product_ID,Name,PP_Product_BOM_ID,Processing,Updated,UpdatedBy,ValidFrom,Value) VALUES (1000000,1000000,'A','M','N',TO_TIMESTAMP('2017-09-07 08:44:11','YYYY-MM-DD HH24:MI:SS'),2188223,100,'1000373','Y',2005577,'P002737_AB Alicesalat 250g',nextval('pp_product_bom_seq'),'N',TO_TIMESTAMP('2017-09-07 08:44:11','YYYY-MM-DD HH24:MI:SS'),2188223,TO_TIMESTAMP('2015-07-14','YYYY-MM-DD'),'P002737_AB Alicesalat 250g') RETURNING PP_Product_BOM_ID
```

VI. Role NOK (seems it's trying to copy the name)

```
Error: Der Rollenname muss eindeutig...
Server error
Der Rollenname muss eindeutig sein.
```

VII. GL Journal/Batch
```
Error: Cannot get TableName for...
Server error
Cannot get TableName for a null model. Possible development issue.
```

**Comment by teosarca** [comment]
update: "II. purchase order OK??" was fixed.
The others are still pending.

**Comment by metas-ts** [comment]
not needed in branch `2017-09-12`as talked with @metas-mk

**Comment by teosarca** [comment]
> VI. Role NOK 

fixed

**Comment by teosarca** [comment]
> III. sales invoice NOK?
> => line doesn't keep it's price (on swing it does) NOK??

hmm checked, and in my case it worked :)

My test case was:
* create a new sales invoice (manually)
* batch entry: add Topinambour . In my price list it's sold with 1EUR
* changed Topinambour's price from 1EUR to 2EUR
* batch entry: add Topinambour. It was added with the price 2EUR
* so now i have one line with price 1EUR and one line 2EUR

* clone it
* document looks nice :)

* on the second line, changed the price (PriceEntered) from 2EUR to 3EUR
* clone it
* document looks nice :)

![image](https://user-images.githubusercontent.com/1244701/30742087-4a83c354-9fa0-11e7-8c57-ba48e8fd4a92.png)

**Comment by metas-rc** [comment]
Moving this task to done because all its parts are either covered or with followups.
