### ISSUE TITLE
Sorting Indicator missing in initially sorted included Tabs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#541]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Sorting Indicator is missing in initially sorted included Tabs
#### Which are the steps to reproduce?
Open the window https://w101.metasfresh.com:8443/window/260/1000015. The first included Tab is sorted by Name initially. The OrderBy Triangle is not shown.
### What is the expected or desired behavior?
Shall be shown.

**Comment by teosarca** [comment]
this was already solved.
Right now there are some problems with sort indicator but those are on frontend side.
