### ISSUE TITLE
Notification Persisting

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#545]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, Notifications are not persisted in metasfresh Database. As soon as a cache reset is done, then the user notifications vanish.
#### Which are the steps to reproduce?
Open, create user notifications and reset the cache.
### What is the expected or desired behavior?
All user notifications shall be persisted.

**Comment by metas-lc** [comment]
IT
created notifications, used cache reset, checked the notifications => are still there OK

**Comment by teosarca** [comment]
note to IT: also make sure http://w101.metasfresh.com:8181/test/ping/notifications is working.
(hint: use SuperUser as user)

**Comment by metas-rc** [comment]
Resulta of IT

* Notifications persist no matter how many times I perform cache reset.
*  Both new and old notifications are persisted
* Using http://w101.metasfresh.com:8181/test/ping/notifications  creates notifications in our w101 system. After cache reset, they are still persisted, the same way real notifications are.
