### ISSUE TITLE
Notification Deleting

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#546]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the user cannot delete any User Notifications.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Allow the user to select and delete User Notifications.

**Comment by metasnw** [comment]
@teosarca are the notifications also deleted in the database or just hidden?

**Comment by teosarca** [comment]
@metasnw they are completely deleted.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* possibility for user to delete notifications: OK
* deleted notifications are not displayed anymore: OK
* possibility to select & delete >1 notification: ?
