### ISSUE TITLE
Validcombination Window does not allow NEW in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#549]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the user is not allowed to create a new Combination via Valid Combination Master Data Window, although insert records are allowed in Tab configuration.
#### Which are the steps to reproduce?
Open the window https://w101.metasfresh.com:8443/window/ in WebUI and see.
### What is the expected or desired behavior?
It shall be allowed to create a new Validcombination in that window.

![image](https://user-images.githubusercontent.com/13365687/29748531-df790b46-8b18-11e7-99d1-4e8e1b290af7.png)

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh/issues/2255

**Comment by teosarca** [comment]
You cannot create a new valid combination. Those are automatically created when user is filling "account" fields.

More, when checking the window layout i saw that supportNewRecord:false, so it seems the frontend is not handling this flag.

![image](https://user-images.githubusercontent.com/1244701/29760444-24ae7fa8-8bcc-11e7-8f3c-737d4fc17dae.png)

**Comment by teosarca** [comment]
Update: before fixing the frontend side (a new task shall be created for that purpose), we need to fix the backend side (https://github.com/metasfresh/metasfresh-webui-api/issues/550).

**Comment by metas-mk** [comment]
@teosarca as discussed. the issue here is that the tab is configured as "insert record", the button is shown in webui window, but exception appears in API.
![image](https://user-images.githubusercontent.com/13365687/29768023-ea7fc18e-8be4-11e7-8422-287dfa65db58.png)

**Comment by metas-rc** [comment]
Results of IT

IT OK. Please, check results from https://github.com/metasfresh/metasfresh/issues/2255
