### ISSUE TITLE
verify if lookup value is still valid

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#551]
### Is this a bug or feature request?
Bug
### What is the current behavior?

* related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/1165
* the scenario is the same.
* this issue is about making the API reload the list of available lookup values and set the field's current value to `null`, if the field's former value is not eligible anymore.

**Comment by metas-dh** [comment]
checked with metas-ts: can be moved to Done
