### ISSUE TITLE
webui notification-test fails

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#553]
### Is this a bug or feature request?
Bug

### What is the current behavior?

currently, the notification "testing endpoint" does not work

#### Which are the steps to reproduce?

* log into the webui with username "user"
* log in with the swing client also with username "user"
* invoke the testing endpoint as follows:
```bash
curl -u user:password http://app-host:8080/test/ping/notifications
```
=> There is a notification shown in the swing client, but not in the webui

Note: the fix needs to also end up in branch `2017-09`

**Comment by teosarca** [comment]
@metas-ts there was a bug when the Event.getDetailADMessage() was returning null, because AD_Note.AD_Message_ID is mandatory. Fixed that case.
Besides that, IMHO the notifications are working.
Can u pls confirm?

**Comment by teosarca** [comment]
(basically it was fixed in https://github.com/metasfresh/metasfresh-webui-api/issues/545 )

**Comment by metas-ts** [comment]
cherry-picked to `2017-09` see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/215/

**Comment by metas-ts** [comment]
Works again as checked by @metas-mk
