### ISSUE TITLE
Picking Window Main View adjustments

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#556]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are some more columns needed in Main View of picking window.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the columns Order, BPartner, Location, QtyPicked to Picking Window main view.

![image](https://user-images.githubusercontent.com/13365687/29866230-1c60c056-8d78-11e7-9b4c-c2ac7ffd0e31.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

main view Picking Terminal now includes columns Order, BPartner, Location & QtyPicked: OK
