### ISSUE TITLE
Email change in "Settings" isn't automatically applied to email in "User" and vice versa

### ISSUE THREAD

**Issue by metas-Kay** [metasfresh/metasfresh-webui-api#559]
### Is this a bug or feature request?
Bug

### What is the current behavior?
If you change the email in the window "Settings" it isn't automatically changed in the window "user" and vice versa.

#### Which are the steps to reproduce?
- Go to "Settings"
- change email
- go to "User" and open the respective user record
- change hasn't been applied/needs to be done manually a second time

### What is the expected or desired behavior?
The email change in either window should be applied automatically in the other, respectively.

**Comment by teosarca** [comment]
i would say it is... but https://github.com/metasfresh/metasfresh-webui-api/issues/19 :(

**Comment by metas-lc** [comment]
IT
testcase above works fine OK
in case you have 2 tabs: one for settings and one for user (user must be in grid view) and you make changes, then you get an error in console and the change is not shown (you need to refresh the page). Created new task for this: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1542
