### ISSUE TITLE
Picking: don't allow picking included rows

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#560]
### Is this a bug or feature request?
FR/workaround

To avoid the problem from https://github.com/metasfresh/metasfresh-webui-api/issues/558, for now we won't allow picking included rows.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Picking included rows not allowed: Action "Pick" is not available for included rows, action button is gray: OK
