### ISSUE TITLE
Handling Unit Editor - remove hardcoded filter for active HUs

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#563]
### What is the current behavior?
currently, only active (IsActive='Y') HUs are shown. It's hardcoded in `de.metas.ui.web.handlingunits.HUEditorViewFactory.createSqlViewBinding()`

**Comment by metas-mk** [comment]
We're talking about isActive = 'Y' which is set to 'N' when shipped or destroyed.

**Comment by metas-ts** [comment]
cherry-picked the fix to `2017-09`

**Comment by metas-ts** [comment]
CPed the fix to `2017-09` as well

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15WebUI

1. create a shipment using HUs, note the HU values
2. create material receipts, then use Korrektur to destroy the HUs (note the values as well)
3.  open Handling Unit Editor, search for your HUs (check single view as well):
* the HUs are included in the Editor, there status is Shipped / Destroyed 
* the HUs have IsActive=N in single view
