### ISSUE TITLE
Filter Layout Sequence

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#564]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Sequence of Filter Fields shown behind Filter Buttons, are taken from ad_column_id asc.
#### Which are the steps to reproduce?
Open any Filter selection in grid View and compare with Table/ Column configurations.
### What is the expected or desired behavior?
Provide a new Field in Column configuration that allws to define the "selectionColumnSeqNo". This shall then be used in WebUI to Order the Filter Fields.

![image](https://user-images.githubusercontent.com/13365687/29995860-c210f0de-8ff3-11e7-8721-8334e56f7fe0.png)

### How to configure it
![image](https://user-images.githubusercontent.com/1244701/30051993-b4223330-922c-11e7-84da-2cea7f9d81a6.png)

### Known limitations
* works only for webui. In swing the SeqNo is not considered

**Comment by metas-lc** [comment]
IT
checked outbound documents and default filtersing columns from the table. They are not in the same order. Is that ok?
