### ISSUE TITLE
Shipped HUs are not displayed correctly

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#567]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* open shipments window: https://w101.metasfresh.com:8443/window/169
* select a shipment where u have some HUs
* call "Select HU for return" action
* the HU editor view is displayed but only the LU level is displayed (TUs/CUs were not displayed).

![image](https://user-images.githubusercontent.com/1244701/30024908-9d4680d4-917e-11e7-8fc5-188262a6ec48.png)

### What is the expected or desired behavior?
The whole HU structure (LU-TU-CU) shall be displayed.

**Comment by metas-ts** [comment]
cherry-picked to `2017-09`

**Comment by metas-ts** [comment]
un-cherry-picked to `2017-09` :-)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* created a shipment including HUs: with LU including TUs and CUs, and TU as top-level HU including CUs
* "Select HU for return" action: all shipped HUs are displayed with complete structure, not only LU level: OK
