### ISSUE TITLE
filtering is not working in picking

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#568]
### Is this a bug or feature request?
bug
### What is the current behavior?
filtering is not working in picking
#### Which are the steps to reproduce?
1. open picking: https://w101.metasfresh.com:8443/window/540345?viewId=540345-eb9a8c886e994a19aaf8c23a0d77dfc4&page=1
2. select a product you know it has HUs (e.g. Topinambour)
3. pick
4. open hu selection window and filter for barcode or HU value
=> nothing was found
### What is the expected or desired behavior?
should select your HU

**Comment by teosarca** [comment]
frontend issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1172
