### ISSUE TITLE
clicking print on non-document window shows error page

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#570]
### Is this a bug or feature request?
bug

### What is the current behavior?
open print in any non document window and you get an error message

#### Which are the steps to reproduce?
1. open partner window
1. select one record
1. Actions => print
1. NOK: error

sample: https://w101.metasfresh.com:8443/rest/api/window/123/2156481/print/123_2156481.pdf

### What is the expected or desired behavior?
either dont show action or show something useful like a generic report showing the master data

Feedback by Harald S.

**Comment by teosarca** [comment]
Shall be solved after https://github.com/metasfresh/metasfresh-webui-api/issues/583

**Comment by teosarca** [comment]
note to IT: 
* if you really want to see that Print menu item vanishing, wait for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1195
* else, all you can do is to check the API response

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* API response:  no more "print" in standardActions array where not available: OK
* print action not available anymore: waiting for metasfresh/metasfresh-webui-frontend#1195, to be tested again

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* print action not available anymore: for documents where no printing available, e.g. bpartner or product: OK
* print action available where necessary, e.g. order: OK
