### ISSUE TITLE
qty doubled on vendor/customer return and destroyed HUs

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#572]
### Is this a bug or feature request?
bug
### What is the current behavior?
if you do vendor return from webui you get double qty of tu + if you revert it the LU gets destroyed while the TU is active (status)
#### Which are the steps to reproduce?
1. receipt candidates -> receive HUs 5 cu x 1 tu x 3 lu
2. make receipt for all 3
3. make vendor return from all 3 => nok you get 6 TUs (expected 3) 
4. storno the return => TU gets status active ok, LU is destroyed (nok expected status active) 
### What is the expected or desired behavior?
see expected on steps 3 and 4

**Comment by teosarca** [comment]
update: hotfixed the issue by using only the top level HUs from user's selection

TODO:
* make it obvious that included HUs are not supported

**Comment by metas-ts** [comment]
cherry-picked to `2017-09`

**Comment by metas-lc** [comment]
IT
retested testcase above
stpe 3 => OK 3 TUs
step 4 => OK hu status active
