### ISSUE TITLE
MoveToDirectWarehouse shall support multiple HUs

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#573]
### Is this a bug or feature request?
Enhancement
### What is the current behavior?

Currently, the process `WEBUI_M_HU_MoveToDirectWarehouse` ("Materialentnahme") allows such one top-level HU to be selected. If a user selects more than one, the process is not available anymore.

#### Which are the steps to reproduce?

try and see

### What is the expected or desired behavior?

If many (top-level) HUs are selected, then the process should still be available and all the selected HUs should be moved

**Comment by metas-ts** [comment]
cherry-picked to branch `2017-09-12`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15, WebUI & Swing

1. Set a MoveToDirectWarehouse in SysConfig
2. WebUI: Open Handling Unit Editor, select 2 LUs including TUs & CU, select Action Materialentnahme:
 * no error, gets processed: OK
 * check the HUs  in Editor (single view): warehouse (Locator) is now the one set as MoveToDirectWarehouse: OK
3. In Swing: Open Handling Unit POS,  select 2 LUs including TUs & CU, select Action Materialentnahme:
 * no error, gets processed: OK
 * check the HUs in Editor (single view): warehouse (Locator) is now the one set as MoveToDirectWarehouse: OK

question: checked M_Storage in Swing, for the MoveToDirectWarehouse:
 * the LU, TU and CU (product) moved via WebUI are all displayed in a single entry each
 * the LU, TU and CU (product) moved via Swing are summed up, e.g. LU qty: 2, TU wty: 2; is that OK?

**Comment by metas-mk** [comment]
@metas-dh thx

> check Warenbewegung: 1 movement was created, 1 for both LUs and including HUs: OK??

yes, is OK.
