### ISSUE TITLE
HU does not disappear after Correction Quick-action.

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#575]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Since the last release, the correction function in Material Receipt/ HU Editor does not let the selected HU disappear.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The selected HU(s) shall disappear after correction automatically.

**Comment by metas-lc** [comment]
IT
HU Editor. Try all cases where the HU shall disappear: 
- reverse OK
- materialentnahme OK
- dispose OK
- move to quality wh OK
- return to vendor OK
- pick selected HU OK
- unpick HU OK
- return to customer OK
