### ISSUE TITLE
Implement batch entry for Sales/Purchase Invoice documents

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#576]

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* batch entry for Sales/Purchase Invoice documents available: OK
* batch entry for Sales/Purchase Invoice documents: invoice lines created correctly, OK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* batch entry for Sales/Purchase Invoice documents: invoice lines created correctly:
the standard price is taken correctly from the pricelist, line net amt is calculated correctly
