### ISSUE TITLE
NPE when you issue HUs

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#579]
### Is this a bug or feature request?
bug
### What is the current behavior?
npe in manufacturing
#### Which are the steps to reproduce?
go to manufacturing and issue a coproduct => npe

**Comment by teosarca** [comment]
update: after talking with @metas-ts  did another fix

**Comment by metas-ts** [comment]
cherry-picked to the branches `release` and `2017-09-12`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* issue a Co-Product: no NPE, works fine: OK
* HU Editor: HU value & qties updated correctly after issueing: OK
