### ISSUE TITLE
API: Provide the document's standard actions

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#583]
### Is this a bug or feature request?
feature request

### What is the current behavior?
At the moment the standard document's actions are hardcoded on frontend side,
i.e. i am talking about those ones

![image](https://user-images.githubusercontent.com/1244701/30315947-2bcf41e4-97ae-11e7-83c6-d83405b2647d.png)

### What is the expected or desired behavior?
the API shall provide them as a list of standard actions which can be called for a given document.
The actions array shall be provided when the document is retried.

NOTE: this task is not supposed to check and return only those actions which are really available.
This task will just open the gates for other issues to be fixed, around this topic (e.g.  not having the print button if the print is not available etc).

**Comment by metas-rc** [comment]
Results of IT

* OK: The standard actions provided by the backend arre rendered by the frontend.
