### ISSUE TITLE
Lookup validation rule shall support @CtxName/Default@ annotation

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#585]
### Is this a bug or feature request?
Feature Request

### What is the current behavior?
See issue https://github.com/metasfresh/metasfresh/issues/2440: The lookup for `M_QualityInsp_LagerKonf_Version_ID` does not return anything, because it's use has  `... @ValidFrom/0001-01-01@...` in it.

#### Which are the steps to reproduce?

Try creating a new material tracking record

### What is the expected or desired behavior?

the validation rul should be evaluated the same way it happens in the old swing client.

**Comment by metas-dh** [comment]
checked with metas-ts: can be moved to Done
