### ISSUE TITLE
Cloning Feature: Error when cloning BOM

### ISSUE THREAD

**Issue by metas-Kay** [metasfresh/metasfresh-webui-api#588]
### Is this a bug or feature request?
bug

### What is the current behavior?
When cloning a BOM this error occurs: **org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "ppproductbomunique"...**
![error message cloning bom](https://user-images.githubusercontent.com/29163573/30441705-7ccad2ac-997a-11e7-928a-2ad6b9b4219d.jpg)

#### Which are the steps to reproduce?
1. Open or create a BOM record.
1. Clone the record.
1. The error occurs. No clone is created.

### What is the expected or desired behavior?
The entire BOM record should be duplicated and open in a new window.

**Comment by teosarca** [comment]
(follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/54)

**Comment by teosarca** [comment]
update: this task was fixed particularly but a similar problem we might encounter on other documents. The task which shall solve it for good is https://github.com/metasfresh/metasfresh/issues/2546

**Comment by metas-rc** [comment]
Results of IT

The BOMs can be cloned. The clone is correctly created and opened  in the same window.
