### ISSUE TITLE
Cloning Feature: Error when cloning Currency

### ISSUE THREAD

**Issue by metas-Kay** [metasfresh/metasfresh-webui-api#589]
### Is this a bug or feature request?
bug

### What is the current behavior?
When cloning a currency this error occurs: **org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "c_currencyisocode"...**
![error message cloning currency](https://user-images.githubusercontent.com/29163573/30441948-3e8faae8-997b-11e7-9156-12a99b1fd667.jpg)

#### Which are the steps to reproduce?
1. Open or create a currency record.
1. Clone the record.
1. The error occurs. No clone is created.

### What is the expected or desired behavior?
The entire currency record should be duplicated and open in a new window.

**Comment by teosarca** [comment]
There is no cloning support for this one, yet :)

The clone option will be hidden by https://github.com/metasfresh/metasfresh-webui-api/issues/593
