### ISSUE TITLE
Issues HUs are still selectable in HU editor while production is not completed

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#590]
### Is this a bug or feature request?
Bug
### What is the current behavior?

As reported by @metas-dh 

> HUs i used in Issue are still shown as Active in HU Editor, shouldn't they be destroyed after being used in the production process? i haven't completed the production yet, btw

#### Which are the steps to reproduce?
 Try it out

### What is the expected or desired behavior?

HUs that were issued shall not be available for anything else anymore, even if the production is not yet completed

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Have 2 PP_Orders, for the same product or products which consist of the same components
2. Have HUs with the different components available for issueing in production (note the values!):
* LUs including TUs and CUs
* LU including CUs only
* TUs including CUs, no LU
* CUs only, no LU or TU
3. In Manufacturing window, HU Editor, issue several HUs for one of the PP_Orders, for the different components:
* 1 LU including TUs and CUs
* >1LU including TUs and CUs
* LU including CUs only
* TUs including CUs, no LU
* CUs only, no LU or TU
4. Check these HUs in Handling Unit Editor after issueing:
* status: Issued: OK
* not only top level HUs have status Issued, but all included HUs are also displayed as Issued: OK
5. Open the other PP_Order, check the HUs available for issueing:
* the HUs with status Issued are not available in the HU Editor: OK
6. Go back to your 1st PP_Order, select some components and reverse the issueing for some HUs (note the values!)
7. In Handling Unit Editor, check the HUs where you reversed issueing:
* status: Active: OK
* not only top level HUs have status Active, but included HUs are also displayed as Active: OK
8. Check the HU Editor of the other PP_Order again:
* the HUs where you reversed issueing are now available for issueing in this PP_Order: OK

still to test:
* status of HUs after splitting & issueing: Transform is not working atm, see https://github.com/metasfresh/metasfresh-webui-api/issues/599

problems / questions:
* Gebinde Status in HU Editor, grid view: OK, BUT in single view incorrect: e.g. planning after issueing, or issued after reverse: NOK!
* HUs != top level, e.g. TUs included in LU: cannot be found with search for Barcode in HU Editor (no results), and you get 404 error when you double click on it: why?

**Comment by metas-dh** [comment]
Results of IT2

8. status of HUs after splitting & issueing: 
* status of issued HU which was split off: Issued: OK
* status of remaining HU: Active: OK
