### ISSUE TITLE
Filter by warehouse when selecting HUs to issue

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#591]
### Is this a bug or feature request?
FR
### What is the current behavior?
currently, be default the HU editor open without a warehouse filter

**Comment by metas-lc** [comment]
IT
1. make sure you have hus for product A in 2 different warehouses (X and Y)
2. go to manufacturing window and create+complete a new one, for a product that has product A as co-product, in wh X
3. press on issue/ receipt
4. select the co-product and press on issue
=> you can see only the HUs from wh X OK
