### ISSUE TITLE
Remove Clone action if not supported

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#593]
### What is the current behavior?
Document Clone action is enabled for any document

### What is the expected or desired behavior?
Shall be enabled only for documents which support this, same as in Swing.
Those documents are: order, BOM, RfQ etc

This task is a follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/54.

**Comment by teosarca** [comment]
note to IT:
Until https://github.com/metasfresh/metasfresh-webui-frontend/issues/1195 is implemented, all you can test/check is this:
![image](https://user-images.githubusercontent.com/1244701/30481348-bc6f02aa-9a26-11e7-8e89-58ec25581172.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Document Clone action only enabled for documents which support this:
* standard action clone enabled for e.g. order, RfQ, BOM (same as Swing): OK
* standard action clone disabled for e.g. bpartner, product (same as Swing):  OK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

Document Clone action only enabled in Action Menu for documents which support this:

* standard action clone enabled for e.g. order, RfQ, BOM (same as Swing): OK
* standard action clone disabled for e.g. bpartner, product, request, warehouse etc. (same as Swing): OK
