### ISSUE TITLE
error in picking

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#597]
### Is this a bug or feature request?
bug
### What is the current behavior?
cannot open the HUs in picking
#### Which are the steps to reproduce?
1. open https://w101.metasfresh.com:8443/window/540345?viewId=540345-284d660c54de4c378cb859e968cf2f45&page=1
2. select a product, pick
3. press on open hu selection window 
=> {timestamp: 1505807789877, status: 404, error: "Not Found",…}
error:"Not Found"
exception:"de.metas.ui.web.window.exceptions.DocumentLayoutBuildException"
message:"For input string: "pickingSlot""
path:"/rest/api/process/ADP_540809/1608430/start"
status:404
timestamp:1505807789877
### What is the expected or desired behavior?
shall open HUs to select window

**Comment by metas-lc** [comment]
IT
retested the case above => works fine, no errors

**Comment by metas-ts** [comment]
cherry-picked to `release`
