### ISSUE TITLE
String document IDs cannot be converted to int error on Transform

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#599]
### Is this a bug or feature request?
bug
### What is the current behavior?
cannot transform a TU from an LU
#### Which are the steps to reproduce?
1. go to material receipt candidates and select a product 
https://w101.metasfresh.com:8443/window/540196?viewId=540196-9fbb81fbcce14c689d1a1ce88e16b2ca&page=1
2. press on the green button to receive HUs (or use receive HUs button to make sure you have more than 1 TU on an LU)
3. in HU Editor select the TU and press on transform
4. try to choose an action
=> Error: String document IDs cannot...
Server error
String document IDs cannot be converted to int: 1013490_T1013489

similar case:
1. open picking terminal, select a line, pick
2. select a picking slot, open HU selection window, select HUs, OK
3. select the HU in picking slot, and select process picking in action menu
=> Server error
String document IDs cannot be converted to int: 1000104-1000010

**Comment by metas-ts** [comment]
Cherry-picked to release-branch

**Comment by metas-rc** [comment]
Results of IT:

Repeated test cases from the task and all works fine.
