### ISSUE TITLE
Handle incorrect AD_Window_ID in URL

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#603]
### Is this a bug or feature request?
FR
### What is the current behavior?

If a user wants opens a window it is checked whether they have the respecitve rights.
If not, the attempt is logged and request is created that can later on be granted or declined.
Problem: if there is no such window (because a user mistyped an URL), then creating that request fails with a hard-to-understand exception.

The consequence is that instead of getting the message that the given window is not accessible, the user gets a very technical `NoSuchForeignKeyException`  the conent of which is none of his business.

#### Which are the steps to reproduce?

just to to some window and change the number after the URLs `/window/` part..e.g. append some zeros

### What is the expected or desired behavior?

There shall be no `NoSuchForeignKeyException`, but the usual one that sais "you don't have access"

**Comment by metas-lc** [comment]
IT
opened a window that doesn't exists => Error: NoAccess...
Server error
NoAccess 
OK
