### ISSUE TITLE
I as an user want to store an URL as attachment to a record

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#605]
### Is this a bug or feature request?
FR

### What is the current behavior?
you can only upload actual files

#### Which are the steps to reproduce?
http://docs.metasfresh.org/webui_collection/EN/File_handling.html

### What is the expected or desired behavior?
have a way to manually paste an URL (e.g. http:// or any other protocol) which is shown as attachment on side bar and in documents (ad_attachment)

**Comment by metas-dh** [comment]
Results of IT
tested in mf15

* possibility to store a URL as attachment to a record (URL + Name): OK
* URL working correctly: OK
