### ISSUE TITLE
AD_Column.IsMandatory shall be overwritten by MandatoryLogic

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#607]
### Is this a bug or feature request?
FR
### What is the current behavior?

In the webui `AD_Column.MandatoryLogic` is only evaluated if `AD_Column.IsMandatory='N'`.

#### Which are the steps to reproduce?

i saw it with `C_FlatrateCondidtions.UOMType`..

### What is the expected or desired behavior?

if  `AD_Column.MandatoryLogic`is specified, go with it. Use  `AD_Column.IsMandatory='N'` as "fallback" in case no logic is specified

**Comment by metas-ts** [comment]
cherry-picked @teosarca's fix to the `release` branch

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new pricelist: pricing system is marked as mandatory field, so no porblems with setting a name for the pricelist / changing the currency (was not possible during last e2e bc of this problem): OK
* will test once more in next e2e

**Comment by metas-dh** [comment]
tested in mf15releasetest during e2e, working fine

**Comment by metas-dh** [comment]
tested in mf15releasetest during e2e, working fine
