### ISSUE TITLE
CU Quantity in Excel Export from HU Editor is wrong

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#608]
### Is this a bug or feature request?
bug

### What is the current behavior?
while testing https://github.com/metasfresh/metasfresh-webui-frontend/issues/1212 I found that the numbers in the download excel are incomplete

#### Which are the steps to reproduce?
1. open Handling unit editor https://w101.metasfresh.com:8443/window/540189?viewId=540189-2bf9fb37071a403c93b9d223df45b45c&page=1
1. select a few lines
![image](https://user-images.githubusercontent.com/16079655/30695447-895ed762-9ed8-11e7-93b2-83aea069a07d.png)

1. download them via action
![image](https://user-images.githubusercontent.com/16079655/30695465-90f55c58-9ed8-11e7-9d55-3628210fc7fb.png)

1. NOK: cu menge is 0 but should be 10

![image](https://user-images.githubusercontent.com/16079655/30695483-a4832368-9ed8-11e7-8205-320c5c06d349.png)

**Comment by teosarca** [comment]
note to IT: also pls do a quick regression, on swing too.

**Comment by metas-dh** [comment]
Results of IT
tested in mf15

* Menge CU in Excel Export from HU Editor correct: OK
* Headers missing in Excel Export: why?

![2017-10-19 16_59_19-report 1 xls - libreoffice calc](https://user-images.githubusercontent.com/18696715/31777679-ee165ae6-b4ee-11e7-93e5-26b5f2829655.png)

todo: regression
