### ISSUE TITLE
Field "Belegart" is included twice in payment window

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#609]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Field "Belegart" is included twice in payment window, only 1 can be set by user
#### Which are the steps to reproduce?
Open and see
### What is the expected or desired behavior?
not sure if this is wanted?

**Comment by metas-mk** [comment]
@metas-dh thx for the info. is a bug. taking 1 field out.

**Comment by metas-mk** [comment]
Closing this one (see new issue above in metasfresh repo).
