### ISSUE TITLE
Cannot add role for user if password has less than 8 characters

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#610]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Belongs to https://github.com/metasfresh/metasfresh-webui-frontend/issues/1218
The password Field is a mandatory Field. As soon as the user types at least 1 char, the mandatory logic is fulfilled and the "blue" borderline disappears. The record is not saved and the user does not receive an error.
#### Which are the steps to reproduce?
Check.
### What is the expected or desired behavior?
Provide a solution.
Proposal: Could be a check how long the password entry is. If not 8 digits, and leaving field focus. Then show the field in red border and add error tooltip.

@teosarca WDYT?

**Comment by teosarca** [comment]
@metas-mk  IMHO we shall check, improve and/or fix following processes:
* org.adempiere.user.process.AD_User_ChangePassword
* org.adempiere.user.process.AD_User_ChangeMyPassword

Also, we shall hide the Password field.

**Comment by metasnw** [comment]
there are also some suggestions here: https://github.com/metasfresh/metasfresh/issues/2212

**Comment by teosarca** [comment]
exactly that's the task we shall implement. Let's close this one.
