### ISSUE TITLE
Destroyed HUs in HU Editor

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#611]
### Is this a bug or feature request?
bug
### What is the current behavior?
you can see destroyed HUs in HU Editor
#### Which are the steps to reproduce?
1. go to https://w101.metasfresh.com:8443/window/540196?viewId=540196-87756eace8624b6d8a577db422541da6&page=1
2. select a product line, and open receive CUs
3. transform the CU line -> CU to new TUs, put the whole qty
![destrhu](https://user-images.githubusercontent.com/16001666/30848510-0094715c-a2a8-11e7-8eee-7f8338f5fb92.png)
=> NOK the destroyed line with CU is still visible

### What is the expected or desired behavior?
HUs that are destroyed shall disappear from HU Editor

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* repeated testcase above: destroyed HUs no longer displayed in HU Editor OK
* HUs destroyed in Korrektur: also no longer displayed in HU Editor: OK
