### ISSUE TITLE
Set unique hazlecast group name

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#613]
### Is this a bug or feature request?
Enhancement
### What is the current behavior?
Sometimes different webui-api instances find each other and try to communicate.
as of now, this is never wanted, so let's make sure they don't even try

### What is the expected or desired behavior?

the goup name should be something like 
```
<hostname> - webui-api - <someRandomStuff>
```

**Comment by metas-lc** [comment]
can be moved to done
