### ISSUE TITLE
Extend framework to allow modification of standard filter results

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#628]
### Is this a bug or feature request?
FR

Related to Product traceability https://github.com/metasfresh/metasfresh/issues/484

### What is the current behavior?

Right now, in the HU tracing window, we can e.g. flter for a particular `M_InOut_ID` if we do that, we are shown all the `M_HU_Trace`records that have that particular `M_InOut_ID`. This is the general behavior of metasfresh

### What is the expected or desired behavior?

We needs to register a component for a particular window which can receive the "standard" filter record and modify it.
For the HU trace window, this component needs to add to the result all HU_Trace records that are somehow connected to the result

**Comment by metas-lc** [comment]
already tested in https://github.com/metasfresh/metasfresh-webui-api/issues/632
