### ISSUE TITLE
HU-Trace: show all connected records

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#632]
### Is this a bug or feature request?

FR

Related to 
* Extend framework to allow modification of standard filter results #628
* Product traceability metasfresh/metasfresh#484

### What is the current behavior?
Right now, in the HU tracing window, we can e.g. flter for a particular M_InOut_ID if we do that, we are shown all the M_HU_Tracerecords that have that particular M_InOut_ID. This is the general behavior of metasfresh
### What is the expected or desired behavior?
For the HU trace window, when filtering, the window needs to *also* show HU_Trace records that are somehow connected to the result

**Comment by metas-lc** [comment]
IT
i did the following:
purchase order -> receipt -> split 1 LU into 2 LUs
sales order -> pick HU no2 -> shipment no1
pick HU no1 -> shipment no2
 
opened tracing window in 2 tabs: one filter for today and one for shipment no1
=> in tab with today filter i got multiple results: some unrelated HUs
=> in tab with shipment no1 I got all traces related to my case, including shipment no2
