### ISSUE TITLE
Move Picking Tray Clearing Functionality to new window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#637]
### Is this a bug or feature request?
Feature Request (belongs to https://github.com/metasfresh/metasfresh/issues/2763)
### What is the current behavior?
Currently, the Picking Tray Clearing Functionality is wrongly adapted to existing Picking Try window (maintenance/ master data window).
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Move the Picking Tray Clearing Functionality to the new window and recover the generic functionality of Picking Tray master data Window again.

**Comment by metas-lc** [comment]
IT
1. go to picking tray window (540206), select a slot with picked / processed HUs => there is no "take out hu" process OK
2. go to Picking Tray Clearing (Prototype) window (540371), select a slot with picked / processed HUs => there is "take out hu" process on the left side OK
