### ISSUE TITLE
Picking Tray Clearing requery to see the right view

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#643]
### Is this a bug or feature request?
bug
### What is the current behavior?
you need to requerry to see the HUs from the right side in Picking Tray Clearing (Prototype)

#### Which are the steps to reproduce?
1. open Picking Tray Clearing (Prototype) (540371)
2. select a slot that has picked and processed HUs
3. on the left side, select the HU 
=> take out HU button appeared OK
4. press on "take out HU" button 
=> it looks like nothing happened NOK
(you have to press on Picking Tray Clearing (Prototype) breadcrumb to requerry)
### What is the expected or desired behavior?
step 4: 
 the selected Hu goes on the right side and disappears from the left side

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

retested the case described above, working fine: no requery necessary to see the right view: OK
