### ISSUE TITLE
Hide window actions which are not available

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#644]
### Is this a bug or feature request?
FR

### What is the current behavior?
all window actions are shown

#### Which are the steps to reproduce?
e.g.
![image](https://user-images.githubusercontent.com/1244701/31898510-07cc2412-b822-11e7-859c-0cee4a1f4d5d.png)

### What is the expected or desired behavior?
window /actions endpoint shall not provide the disabled actions

**Comment by teosarca** [comment]
required for https://github.com/metasfresh/metasfresh/issues/2564

**Comment by teosarca** [comment]
introduced "disabled" parameter to:
* http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDocumentActionsUsingGET_1
* http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDocumentActionsUsingGET_2

By default, disabled=false => the disabled actions won't be returned

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

checked sev. windows (orders, inouts, invoice etc.): no disabled actions are shown: OK
