### ISSUE TITLE
window/actions: introduce support for selectedTabId and selectedRowIds

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#645]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDocumentActionsUsingGET_1 shall support:
* selectedTabId  - which is the currently selected included tab
* selectedRowIds - which are the currently selected rows of selectedTabId (comma separated)

**Comment by teosarca** [comment]
required for https://github.com/metasfresh/metasfresh/issues/2564

**Comment by metas-lc** [comment]
IT
on actions you have selectedTabId=1&selectedRowIds=.. your row
if there are multiple rows, they are separated by comma OK
