### ISSUE TITLE
shipped HU is still visible in picking terminal

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#647]
### Is this a bug or feature request?
bug
### What is the current behavior?
shipped HU is still visible in picking terminal
#### Which are the steps to reproduce?
1. go to sales order and create a new one, with salad, with more than 1 TU. complete
2. go to referenced documents -> open Picking Terminal (Prototype)
3. select your line, Pick
4. Open HU selection window and pick only 1 HU
5. select your HU -> process Picking. Done
6. go to sales order -> referenced documents -> Shipment Disposition
7. actions -> generate shipments, check both flags, ok
=> shipment created for this HU
8. go back to Picking Terminal (Prototype), select your line, pick
=> notice that the HU you just made shipment with, is still there NOK

(note: if i would have picked and shipped all HUs from my sales order, then the HUs would not appear anymore on step 8. It's happening only on partial shipment)
### What is the expected or desired behavior?
step 8: HU should not appear on the slot anymore, because the shipment was created for it

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

repeated testcase above: 
* shipped HUs not visible in picking terminal anymore: OK
* after both full and partial shipment: OK
