### ISSUE TITLE
Qty Delivered and Qty Picked not updated correctly in shipment schedule

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#649]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Qty Delivered and Qty Picked  are not updated correctly in shipment schedule, after picking and shipment.
#### Which are the steps to reproduce?
1. Create a sales order for a product available for picking
2. Do picking in picking terminal, e.g. qty: 10
3. Check the shipment schedule: Qty Picked is 0, NOK
4. Create the shipment, check the shipment schedule again: Qty Delivered is 0, NOK
### What is the expected or desired behavior?
Qty Delivered and Qty Picked in shipment schedule shall be updated correctly after picking and shipment.

**Comment by teosarca** [comment]
https://github.com/metasfresh/metasfresh-webui-api/issues/19 again :(

i.e. i think Qty delivered and picked are updated but the document is not refreshed.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

with picked HUs:
* Picking in Picking Terminal ("kommissionieren"), not processed yet: Qty Picked= 0, OK
* Picking in Picking Terminal processed: Qty Picked=  e.g. 10, OK
* Shipment created, not yet completed: Qty Picked=  10, Qty Delivered= 0, OK
* Shipment completed: Qty Picked=  0, Qty Delivered= 10, OK
* Picking in Picking Terminal ("pick", with selecting the Shipment Schedule, picking is processed directly): Qty Picked=  e.g. 10, OK
* Picking in Picking Terminal reversed: Qty Picked= 0, OK
* Shipment reactivated: Qty Picked=  10, Qty Delivered= 0, OK

without picked HUs:
* creating shipment from action menu in shipment schedule (not completed): Qty Picked=  10, Qty Delivered= 0, OK
* completing shipment: Qty Picked=  0, Qty Delivered= 10, OK
* reversing shipment: Qty Picked=  0, Qty Delivered= 0, OK
* voiding shipment: Qty Picked=  0, Qty Delivered= 0, OK

while testing with picked HUs, i had to switch between grid / single view to see the changes in shipment schedule; when testing without picked HUs, i could see the qties update in shipment schedule; why?
