### ISSUE TITLE
flatrate contractstatus not refresh in single view after terminated

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#650]
### Is this a bug or feature request?
bug

### What is the current behavior?
when terminating a subscription the field contractstatus is not updated

#### Which are the steps to reproduce?
http://docs.metasfresh.org/webui_collection/DE/Vertrag_kuendigen.html

### What is the expected or desired behavior?
field shall be updated without api cache reset

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

contract status corectly updated after termination in single view, without api cache reset: OK
