### ISSUE TITLE
Implement document discardChanges endpoint

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#652]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
Have 2 endpoints:
* POST /{windowId}/{documentId}/discardChanges
* POST /{windowId}/{documentId}/{tabId}/{rowId}/discardChanges

When called, given document/included document is discarded, which means:
* if it's a new document (not yet saved) it will be completely discarded
* if it's an existing document with changes not yet saved, those changes will be discarded

### References
* triggered by https://github.com/metasfresh/metasfresh-webui-api/issues/460

**Comment by metas-lc** [comment]
IT
tested with bpartner and sales order: 
added rows without country / product => the rows from the tabs were discarded OK
created new bpartner and sales order and moved to other window without saving => the documents were discarded OK

updated bpartner and sales order by removing mandatory fields from header, then moved to other windows => my changes were discarded OK
updated line in sales order by removing the product, moved to another window =>  my changes were discarded OK
