### ISSUE TITLE
Address country lookup not working correctly

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#654]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Assuming you are using English language.
Go to a BPartner.
Create a new location
Edit the address.
Try searching for some countries using their English name.
Usually there is nothing found because no matter what language you are using, the backend is always searching in base language (i.e. DE)

### What is the expected or desired behavior?
wysiwyg... search in login language

**Comment by metas-lc** [comment]
IT
login with DE, go to bpartner and add a new address, search for Rumänien 
=> found in de_DE OK
log in with EN, go to bpartner and add a new address, search for Romania
=> found in en_US OK
