### ISSUE TITLE
JSONUserSessionChangesEvent not fired when currently logged in user is changed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#660]
### Is this a bug or feature request?
bug

### Which are the steps to reproduce?
* Open you current profile.
* in meantime, using http://w101.metasfresh.com:8081/websocket_test.html,
 connect on websocket endpoint  /userSession/<YourUserId>. In case u are logged in with "it" user, that is /userSession/2188223
* in your profile page, change the language
=> no websocket event is fired.

### What is the expected or desired behavior?
A websocket event shall be fired when we change the language, email or full name.
e.g.
![image](https://user-images.githubusercontent.com/1244701/32434270-4cf60cc8-c2e6-11e7-82d0-edd0d86ad0df.png)

### References
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/1280 => i think that one can completely be solved by this issue
* https://github.com/metasfresh/metasfresh/issues/2919 => the websocket event was not sent because the trx was already commited. At least we shall make this case much more obvious.

**Comment by metas-lc** [comment]
IT
repeated the steps above => a websocket event was fired when i changed the language OK
