### ISSUE TITLE
Aggregate Storage for Product and Warehouse

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#662]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we have Storages in HU_Storage.
#### Which are the steps to reproduce?
None
### What is the expected or desired behavior?
For a faster retrieval of Storage Info we need an aggregation of storages per Product and Warehouse.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* SysConfig QueryAvailableStock=Y, with QueryStockAttributesKeys "all": "all" displayed for attributes, when selecting product in quick entry (0 Stk bc new db): OK
* SysConfig QueryAvailableStock=Y, with QueryStockAttributesKeys Bio":  "Bio" displayed for attributes, when selecting product in quick entry (0 Stk bc new db): OK
* SysConfig QueryAvailableStock=N: nothing displayed for attributes, when selecting product in quick entry: OK
