### ISSUE TITLE
Storage Information in Order Batch Input per Attribute Groups

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#663]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, Batch Input only Shows Information about the Product Identifier.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
We want to show the Storage Information for a Product, grouped by specific Attributes (these special Attributes will be set when declaring damage/ expiration. This will be done in seperate Issue).
- General Group (all Products w/o the following Attributes set)
- near-expiration Group (all Products w/ Attribute "near-expiration" set)
- damaged Group (all Products w/ Attribute "damaged" set)

The General Group shall be shown always. The other Groups only when Stock > 0.

![image](https://user-images.githubusercontent.com/13365687/32489435-4441893e-c3b0-11e7-92a7-89b003f911e2.png)

**Comment by teosarca** [comment]
note: atm, this feature is developed in branch gh662-webui of task https://github.com/metasfresh/metasfresh-webui-api/issues/662

**Comment by teosarca** [comment]
because all work was done on #662, i am closing this task.
