### ISSUE TITLE
Create Purchase Order Line by Line via Sales Order Lines

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#664]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we only have a process to create Purchase Orders from Sales Orders. The Information for this Process is taken from Product BPartner.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
The user shall be able to select a sales Orderline. Then start an action "Create Purchase Order". Then a modal Overlay shall be opened that shows a table of possible Vendors and Contact Information. Additional Fields allow to enter the qty and Reference and Promised Date and confirm. After Completion, the Purchase Order(s) are automatically generated.

![image](https://user-images.githubusercontent.com/13365687/32490177-8bfc23b8-c3b2-11e7-9930-7d1f4ab6be5d.png)

**Comment by teosarca** [comment]
TODOs:
* implement some locking mechanism
* notify user(s) when:
** purchase candidates were enqueued (maybe?)
** the purchase order was created (which user(s)?)
@metas-mk  wdyt?

**Comment by metas-ts** [comment]
hi @teosarca 
> implement some locking mechanism 

instead of e.g. inserting T_Lock  records, wdty about creating and using an implementation of `ILockDatabase` such that the system reports "locked" if there is an WP that references the record via one of its WP-elements and has `readyForProcessing=true && processed == false && error == false`

**Comment by teosarca** [comment]
@metas-ts  interesting idea. have to thing about it.
Bellow are some of my loud thinking concerns about this.
* performances? (the C_Queue_Element table is quite big and fast growing, but i know we are archiving it from time to time)
* we will need to implement some mechanism to determine which ILockDatabase implementation to use (maybe based on record's table name)
* problematically locking won't be supported which in particular for this case it's OK but in general it's NOT.

**Comment by teosarca** [comment]
note to IT:
![image](https://user-images.githubusercontent.com/1244701/35105016-394188f8-fc73-11e7-8bf7-ded63d5be6b4.png)

**Comment by cristinamghita** [comment]
![image](https://user-images.githubusercontent.com/15378036/35108272-cc75e7ba-fc7b-11e7-8100-c1cdb395f31e.png)

**Comment by metas-dh** [comment]
@cristinamghita is there more to test for this task?

**Comment by metas-dh** [comment]
checked with metas-mk: task has a couple of follow ups and the general functionality is working, so closing this one.
