### ISSUE TITLE
Change the JSONLookupValue format

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#666]
### Is this a bug or feature request?
FR

### What is the current behavior?
Currently the lookup values have following JSON format:
```json
{
	"<key>" : "<caption>"
}
```
e.g. integer key
```
{
	1000123 : "Some caption"
}
```

e.g. string key
```json
{
	"CO" : "Complete"
}
```

### What is the expected or desired behavior?
The biggest limitation of that format is that we cannot extend it... or if we do, it will be very twisted.
For that reason we shall change it to:
```
{
	"key" : <key>
	"caption" : <caption>
	
	// other optional attributes, e.g.
	"attributes" : { .... },
	"attributes2" : { .... }
}
```

The frontend shall not care about the other optional attributes, it just has to get then and pass it back when the lookup value is sent back.
e.g. the /dropdown endpoint was called and it returned some lookup values. The user picks one. The forntend shall send back the selected value including all it's optional attributes.
This is happening at the moment, but i just underline it because we need to keep this functionality.

**Comment by teosarca** [comment]
update: at the moment, i am using an intermediary solution (i.e. keeping the "key":"caption" pair as first one, but also having the "key", "caption" and other attributes).
While using this approach, it seems frontend almost work OK, but i found some cases where this is an issue.
Bellow i will list them.


### Document Actions
![image](https://user-images.githubusercontent.com/1244701/32537513-95e0e40e-c46b-11e7-8cf0-51d7b280b226.png)

**Comment by metas-rc** [comment]
![image](https://user-images.githubusercontent.com/16001442/32541915-c2f822e6-c479-11e7-8101-95312c5683fd.png)

**Comment by metas-rc** [comment]
![image](https://user-images.githubusercontent.com/16001442/32542090-3b3f0efe-c47a-11e7-9a80-b7adf5d9d7a2.png)

**Comment by metas-dh** [comment]
![2017-11-08 11_01_08-metasfresh](https://user-images.githubusercontent.com/18696715/32542886-4d6027f4-c474-11e7-9ed9-7a56a0f53807.png)

**Comment by cristinamghita** [comment]
![image](https://user-images.githubusercontent.com/15378036/32545475-8597ff60-c484-11e7-92b2-10e8c6c4eb92.png)

**Comment by cristinamghita** [comment]
![image](https://user-images.githubusercontent.com/15378036/32545964-1a567eaa-c486-11e7-90d8-a7a4f4c9623b.png)

**Comment by PabloSichert** [comment]
Does this only affect this [endpoint](http://w101.metasfresh.com:8081/swagger-ui.html#!/address-rest-controller/getAttributeDropdownUsingGET)?

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* all reported problems working fine now, see IT for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1327
* creation of new bpartner on the fly (https://github.com/metasfresh/db03/issues/172) also working fine
* lookup of specific product name & product number for a certain bpartner also working fine
