### ISSUE TITLE
CU-TU's built name and description is wrong

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#669]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
Select a product and add a new CU-TU record.
In my case initially the UOM was Stk.
Then when i set the ValidFrom date it changed to Killogram
.... but the Name and Description is still displaying "Stk".
![image](https://user-images.githubusercontent.com/1244701/32648087-efefb690-c5fc-11e7-8f41-45f6a2ac9b41.png)

### What is the expected or desired behavior?
Make sure the Name and Description are accurate & up2date.

**Comment by metas-rc** [comment]
Default value in M_HU_PI_ITEm_Product.C_UOM_ID column fixed the problem.

**Comment by metas-rc** [comment]
Tested on botwh swing and webui.

**Comment by metas-lc** [comment]
IT
tested on both webui and swing
=> if the product is kg then it's always kg, same for stk OK
=> changing date doesn't affect the name OK
=> changing the qty updates the name and description OK
