### ISSUE TITLE
views: backend shall specify which columns are editable and how to render the editor

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#670]
### Is this a bug or feature request?
FR

### What is the current behavior?
Frontend allows us to edit numeric fields by right clicking on them and then click "Edit field value"

#### Which are the steps to reproduce?
e.g.
https://w101.metasfresh.com:8443/window/540325
![image](https://user-images.githubusercontent.com/1244701/32650655-47936dce-c607-11e7-864d-c4a82291f7f3.png)

### What is the expected or desired behavior?
When providing the view layout, the backend shall specify how the field editor shall be rendered for each element.

e.g.
![image](https://user-images.githubusercontent.com/1244701/32650950-5c95c4be-c608-11e7-8be6-b6c5fb25f58d.png)

The "viewEditorRenderMode" can take following values:
* "never" - never render a field editor because field is not editable
* "on-demand" - it's exactly what we have now with right-click and "Edit field value"
* "always" - the editor field shall be present directly in grid

### Future
In nearest future we might also want to specify if some fields are readonly or not, on row level.
It's important to keep this in mind when developing the frontend/backend.

### References
* required for https://github.com/metasfresh/metasfresh-webui-api/issues/664

**Comment by wiadev** [comment]
@teosarca I'm still not getting viewEditorRenderMode property.

**Comment by teosarca** [comment]
@wiadev  just did a rollout.
Now it shall be available, e.g. https://w101.metasfresh.com:8443/rest/api/documentView/143/layout?viewType=grid&supportTree=true

I will also prepare an example where viewEditorRenderMode is "always"

**Comment by wiadev** [comment]
@teosarca 

![screenshot at nov 15 21-32-37](https://user-images.githubusercontent.com/18234060/32858750-c4dba3c0-ca4c-11e7-9abd-3bcad618623c.png)

if you check date field, it's showing date ISOString as it is without formatting.
is it fine?

**Comment by teosarca** [comment]
@wiadev  thanks for the info. will check...

**Comment by teosarca** [comment]
@wiadev  the thing is that, ofc it's not displayed correctly. It should be formatted according to user's locale.

Now, if i would send it formatted, the frontend won't be able to decode it correctly, so I have to send it into standard format (like i am doing it now).

The question is why the frontend is not correctly rendering it?
I remember some old talks with the developer who developed that component and in case of standard documents, he required to send the widgetType along with the "value", even though the widgetType was already provided in layout.
Is that true? Would that trick hotfix the issue?

**Comment by wiadev** [comment]
@teosarca I see that widgetType is coming along with the value as well but the value was used as it is now.
could you create new issue for this and describe the expectation?

**Comment by teosarca** [comment]
@wiadev  the expectation is to have the date field rendered correctly.
Can u pls create the issue and describe what the backend needs to provide in order to have that working?
(note... the widgetType is what i was guessing/remembering.... pls check if it's right or not)

**Comment by metas-lc** [comment]
IT
0. on elements we have:
viewEditorRenderMode:"on-demand", "never" OR "always" OK
1. went to product price, checked Price List field
=> it's "on-demand": meaning you have to right click + edit to change it. Works OK
2. checked another field, like Attributes
=> it's "never": meaning you cannot edit it. You can't OK
3. went to sales order, selected a document, selected 1 or 2 lines, actions - "create purchase orders"
=> qty to purchase and date promised have  "always" and are already editable (you don't have to right click. You can edit directly) OK
