### ISSUE TITLE
Window for easy Distribution Orderlines Handling in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#672]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently in WebUI the Bereitstellung POS (Swing)) window is missing
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Have a new Window for the Handling of Distribution Orderlines.

**Comment by teosarca** [comment]
@metas-mk  for the start, i think a standard window (which shows DD_OrderLines) would do the trick. wdyt?

**Comment by metas-mk** [comment]
@teosarca Yes, having that in mind too. I will prepare the window for a quickstart and we can see how to proceed.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* Create and complete a purchase order for a product that is a BOM.
* Go to the created receipt candidates
* Receive HUs ( remember the value of the top level)
* Create a material receipt

* Create and complete a Distribution order for the same BOM.
* Go to window Distribution Editor
* => OK: There is a new entry for my distribution order.
* Click this entry in grid mode
* => OK: There is an action available : Move HU
* OPEN: This action is not available in single view. Is this ok? 
* Call the process Move HU
* Set the top level HU from above as parameter
* Select a warehouse
* Start
* OK: No error
* Go to the distribution Order, check linked documents
* OK: There is an Inventory Move document.
* Open this Inventory Move
* OK: It contains the lines for product, TU and LU as I had them in the receipt
* OK: The lines have the right locator to and from.

**Comment by metas-rc** [comment]
Note: I noticed some small design problems with the Distribution Order window while testing. Created a followup: https://github.com/metasfresh/metasfresh/issues/3335
