### ISSUE TITLE
Creating shipment from shipment schedule not working after HU was taken out in Picking Tray Clearing

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#680]
### Is this a bug or feature request?
Bug
### What is the current behavior?
No shipment is created from shipment schedule after HU was taken out in Clearing.
#### Which are the steps to reproduce?
1. Pick a HU in Picking Terminal, & process the picking
2. Check the shipment schedule: HU displayed in Shipment / Picking subtab, with its qty in Qty picked: OK
3. Take out this HU in Picking Tray Clearing
4. Go back to the shipment schedule: HU still displayed, OK
5. Create a shipment, with Qty picked checked
6. Process is triggered, but no shipment is created: NOK
### What is the expected or desired behavior?
Shipment for the Qty picked should be created.

**Comment by teosarca** [comment]
fixed by https://github.com/metasfresh/metasfresh-webui-api/issues/678

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* shipment created after HU was taken out in Picking Tray Clearing: OK
* HU correctly shown in shipment & shipment schedule: OK
* HU status after shipment: shipped, OK
