### ISSUE TITLE
Picking not possible for >1 orderline in Picking Terminal

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#681]
### Is this a bug or feature request?
Bug
### What is the current behavior?
If you have >1 orderline from e.g. the same sales order, you cannot select picking action when >1 are selected.
#### Which are the steps to reproduce?
1. Create a sales order, >1 orderline (different products!)
2. Open Picking Terminal, from references: all orderlines from your sales order are displayed
3. Select >1 of them: Action button shows Pick, but read-only, you can pick only for 1 orderline at the time.
### What is the expected or desired behavior?
Picking for >1 orderline should be possible, if the bpartner, delivery address and delivery date are the same.

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15

Picking possible for >1 orderline: 
* for >1 orderline, from the same sales order: OK
* for >1 orderline, from the same bpartner, same address: OK

**Comment by metas-mk** [comment]
> for >1 orderline, from the same bpartner, same address, but different delivery dates: working, not sure this is OK? @metas-ts, @metas-mk ?

That's ok. thx. Closing.
