### ISSUE TITLE
Keeping lines selected when turning the page not working

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#682]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you select lines in grid view, and turn the pages, the lines don't stay selected.
#### Which are the steps to reproduce?
1. Open e.g. Handling Unit Editor
2. On 1st page, select all lines in all pages with 2x [ctrl]+a
3. Turn to page2: nothing selected, NOK
4. Turn back to page 1: nothing selected, NOK
### What is the expected or desired behavior?
Lines shall remain selected when you turn the pages.

**Comment by teosarca** [comment]
@metas-dh  that's a frontend issue. pls move it there.
