### ISSUE TITLE
Picking processed compress to top-level HU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#689]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, processed HU are shown in all Levels with all content in Picking Window/ Picking Tray.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Show processed only with their top level hu. Allow to expand the view with (+) button tree functionality.

![image](https://user-images.githubusercontent.com/13365687/32978498-957f8878-cc43-11e7-8554-f381fa93b0d7.png)

**Comment by teosarca** [comment]
note to IT: the collapsing/expanding rows works weird. That's a frontend bug: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1373

**Comment by metas-lc** [comment]
IT
tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1373 OK
