### ISSUE TITLE
Error in Quickentry Sales Order when canceling input

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#692]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When using Quickentry in Sales Order lines, selecting a Product an canceling via (X), an error appears.
#### Which are the steps to reproduce?
See above.
### What is the expected or desired behavior?
Error shall not happen.

![image](https://user-images.githubusercontent.com/13365687/33067931-ff1acb80-ceaf-11e7-8831-02973fc4742d.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

cancelling input with X, in quickentry in Sales Order lines: no error, input is cancelled: OK
