### ISSUE TITLE
Error in create purchase orders from Sales order line

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#693]
### Is this a bug or feature request?
Bug
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/664

### What is the current behavior?
When using the action "create purchase orders" in sales orderline, then an error appears as soon one wants to type the quantity.
#### Which are the steps to reproduce?
See above.
### What is the expected or desired behavior?
Shall work without error.
~~~Rename the modal overlay to Process name too~~~ (will be solved by #694)

![image](https://user-images.githubusercontent.com/13365687/33069209-100f9110-ceb4-11e7-92e1-e7be72d99036.png)

**Comment by metas-lc** [comment]
IT
sales order - select a line - run create purchase orders - set a qty => no errors OK
