### ISSUE TITLE
purchase view: set modal title as process caption

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#694]
### Is this a bug or feature request?
Bug
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/664

### What is the current behavior?
The modal's title is "Modal"

#### Which are the steps to reproduce?
just open it

![image](https://user-images.githubusercontent.com/1244701/33072975-1592b282-ceca-11e7-8ba0-a5500534e133.png)

![image](https://user-images.githubusercontent.com/1244701/33072954-00d530c2-ceca-11e7-894e-96447374c0f3.png)

### What is the expected or desired behavior?
The modal's title shall be the same as the action which launched it.

**Comment by metas-dh** [comment]
Results of IT1

modal window: title is not "Modal", but the one of the action that called it: OK
