### ISSUE TITLE
picking terminal: implement dynamic picking slot allocation/release

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#695]
### Is this a bug or feature request?
FR

### What is the current behavior?
The dynamic picking slots are never allocated to a bpartner.

### What is the expected or desired behavior?
Define and implement how this shall work.
When a dynamic picking slot shall be allocated.
When a dynamic picking slot shall be released.

**Comment by teosarca** [comment]
update:
* as soon as user adds an HU (even not processed), the picking slot shall be  allocated to HU's BP and location
* as soon as the slot is empty (no HUs in queue, no picking candidates or all picking candidates are already closed) the picking slot shall be released

**Comment by teosarca** [comment]
note to IT: full regression on picking terminal window is needed.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* user adds an HU, not processed: the picking slot is allocated to HU's BP and location (also in Tray Clearing): OK
* picked HU is processed: the picking slot is allocated to HU's BP and location: OK
* after shipment is created: picking slot is released and empty: OK
* after picking is reversed: picking slot is released and empty: OK
* after HU was taken out in Tray Clearing: picking slot is released and empty: OK

todo: regression on picking terminal window

**Comment by metas-dh** [comment]
update from regression testing:

* when picking for the whole qty of an orderline is done (picked & processed), the orderline disappears from the picking modal overlay: OK
* if the picking slots are not cleared yet, bc no shipment was created or the slot wasn't cleared yet, the slot is still allocated to the bpartner & location: OK

BUT: the processed HUs are not displayed in the slots which are still allocated, so you can't reverse the picking anymore: is that wanted?

orderline qty fully picked, orderline not displayed anymore, picked and processed HUs are not shown in the picking slot and picking cannot be reversed:

![2017-11-28 11_12_21-metasfresh](https://user-images.githubusercontent.com/18696715/33314424-e25e359e-d42d-11e7-8a21-facd5f4d02ec.png)


orderline qty not fully picked yet, orderline still displayed, picked and processed HUs shown in picking slot (read-only), so picking can be reversed:

![2017-11-28 11_20_25-metasfresh](https://user-images.githubusercontent.com/18696715/33314636-89b75780-d42e-11e7-87d4-593c7ec402cc.png)

**Comment by metas-dh** [comment]
Update:

tested again during latest weekly e2e: 
* processed HUs remain displayed in the slots which are still allocated, and user can reverse the picking: OK
* processed HUs only disappear from the picking slot if the slot is rack system: Y, OK
