### ISSUE TITLE
Material receipt schedule: attributes read-only

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#696]
### Is this a bug or feature request?
Bug
### What is the current behavior?
You cannot set attributes or change the weight of a product in Material receipt schedule, HU Editor, they are all read-only.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
User should be able to change the weight and set attributes of products as before.

**Comment by teosarca** [comment]
fixed: attributes are be editable in material receipt and readonly elsewhere

**Comment by teosarca** [comment]
also pls keep in mind that, while developing this, i found a the frontend bug: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1367

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* weight editable in material receipt schedule: OK
* certain attributes read-only, e.g. Karotten-ID & SSCC18: OK
* relevant attributes editable in material receipt schedule: i can set Quality Discount, Tageslot, MHD & Mindesthaltbarkeit; but i get an exception for all other attributes when i try to edit them:
e.g.
> Server error
> Invalid list value '{key=AF, caption=Afghanistan}' (class java.util.LinkedHashMap) for 
> MAttribute[1000001-Herkunft,Type=L,Instance=true].

* edited weight & attributes correctly taken for inout (material receipt & material receipt Jasper): OK

**Comment by teosarca** [comment]
@metas-dh  hotfixed & pushed

> relevant attributes editable in material receipt schedule: i can set Quality Discount, Tageslot, MHD & Mindesthaltbarkeit; but i get an exception for all other attributes when i try to edit them

**Comment by metas-dh** [comment]
@teosarca: tested again, no more exception when selecting an attribute; however, for 1 product the selected attributes were correctly shown in material receipt & Jasper, for the other product they were missing; checking further

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

=> attributes are directly set in orderline when selecting some products in quickentry, e.g. for Radiesli: Ausland_Deutschland, although not set in pricelist (afair, we had that in the past already?):
* attributes set/changed in HU Editor are correctly taken in the material receipt (Jasper) for those products
* if no attributes are directly set in orderline when selecting the product, then the attributes set/changed in HU Editor are NOT taken in the material receipt (Jasper)

**Comment by metas-ts** [comment]
CPed the current state into `release`

**Comment by teosarca** [comment]
@metas-dh the attributes are set because they are defined in the attribute set which is configured on product category level.

**Comment by metas-dh** [comment]
Results of IT 3
done in e2e in release, by metas-lc

1. ASI is set in orderline, but we know why (adr, in/ausland and country are taken from address) OK for now
2. attributes are editable in HU Editor OK
3. attributes were propagated to inout OK
4. label worked fine in swing (the attributes were set) OK
