### ISSUE TITLE
New BPartner is not available as SubProducerBPartner in MaterialReceipt BPartner

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#697]
### Is this a bug or feature request?
Bug

### What is the current behavior?

* create a subproducer (see SubProducerAttributeDAO.java on how to set it up...or ask/find documenation)
* the subproducer is not available in HU editor in the webui. only in swingUI
  * according to the user, it is available after 2-3 hours

Hints: check out 
* SubProducerAttributeDAO
* HUSubProducerBPartnerAttributeValuesProvider

maybre we just need to enable C_BPartner and ..Relation for remote cahcke invalidation?

**Comment by teosarca** [comment]
note: i did it as @metas-ts  suggested (thanks).
Didn't test it but i think it will work.

**Comment by teosarca** [comment]
note to IT: i think the test case is to create a new BP or to create an "IsMainProducer" BP relation in swing UI and then expect to be available in webui, while receiving new HUs.

**Comment by metas-mk** [comment]
Tested on w101. Is now available directly after creation.
