### ISSUE TITLE
Implement Batch entry in Forecast Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#699]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Batch entry available in Forecast Window WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Enable/ Implement Batch Input for Forecast Lines.

**Comment by teosarca** [comment]
note to dev: take de.metas.ui.web.quickinput.invoiceline.InvoiceLineQuickInputDescriptorFactory as example.

**Comment by teosarca** [comment]
note to IT:
* regression on order line batch entry

**Comment by cristinamghita** [comment]
Note to IT:
* test how the qtyTu and qtyCU are computed in forecast line

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* batch entry available in forecast window for forecast lines: OK
* qtyTu and qtyCU calculated correctly (initially / after change): OK
* regression on order line batch entry (initially / after change / w/ & w/o packing item): OK
