### ISSUE TITLE
Filter error after static filter set

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#700]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When opening a window with static filter e.g. Purchase order, referenced document material receipt candidates and then activating a standard filter, then 2 static filters are shown
#### Which are the steps to reproduce?
see above
### What is the expected or desired behavior?
The static filter shall dissappear as soon as a standard filter is selected.

![image](https://user-images.githubusercontent.com/13365687/33131070-b552f374-cf95-11e7-9d24-769564a920b2.png)

**Comment by metas-dh** [comment]
Results of IT1

* static filter is shown only once when opening referenced document material receipt candidates: OK
* static filter shall dissappear as soon as a standard filter is selected: still displayed after standard filter is selected:

![2017-11-23 16_05_02-metasfresh](https://user-images.githubusercontent.com/18696715/33178980-30935330-d068-11e7-9e5b-a5cd18764492.png)

**Comment by teosarca** [comment]
> static filter shall dissappear as soon as a standard filter is selected: still displayed after standard filter is selected

imho that's OK.
You can get rid of that sticky filter by clicking on it.

@metas-mk  wdyt?

**Comment by metas-mk** [comment]
@teosarca @metas-dh 
agree. let's leave it to the user to click on the sticky filter to get rid of it.

**Comment by metas-dh** [comment]
@metas-mk, @teosarca : thx, moving this to Done
