### ISSUE TITLE
SQL Error in Window Stock Control Purchase

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#704]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, there is an SQL Error when you create a new record in Stock Control Purchase Window (Zählbestand Einkauf)
#### Which are the steps to reproduce?
Open, try and see
### What is the expected or desired behavior?
Fix the error please.

![image](https://user-images.githubusercontent.com/13365687/33229690-d357d85e-d1d3-11e7-8c11-2cdd35e59c55.png)

**Comment by metas-mk** [comment]
Column SQL involved
ProductGroup:
( select OrderBy_ProductGroup from "de.metas.sp80".OrderBy_ProductGroup v where v.M_Product_ID = Fresh_QtyOnHand_Line.M_Product_ID )

ProductName:
( select OrderBy_ProductName from "de.metas.sp80".OrderBy_ProductGroup v where v.M_Product_ID = Fresh_QtyOnHand_Line.M_Product_ID )

**Comment by metas-ts** [comment]
was meanwhile fixed
