### ISSUE TITLE
Backend Logic for new Date Filter Widget

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#705]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, a date widget for filtering is a date-range widget.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create the backend functionality/ configuration possibility to have
- a date widget (only 1 date)
- with arrows to left/ right that allows date increments (back+1/ forth +1)
- and is initially set to the current date when window opening

### How to configure
![image](https://user-images.githubusercontent.com/1244701/33287954-2ef018b6-d3c3-11e7-99ba-bbe2297b7287.png)

**Comment by metas-lc** [comment]
IT
tested it in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1387
OK: Range Filter on N updated my filter to 1 day
Filter +/- buttons on Y added < and > arrows to my filter
Filter Default value NOW - set my filter to now
