### ISSUE TITLE
port current MRP Product Info Window to the webui

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#706]
### Is this a bug or feature request?
FR
related to https://github.com/metasfresh/metasfresh/issues/2646 MRP Product Info Just in Time

### What is the current behavior?
currently we have an InfoWindow based MRP Product Info Window in swing and nothing comparable in the webui

#### Which are the steps to reproduce?
go and check..

### What is the expected or desired behavior?
we need something adequate (not neccesary the same) in the webui too

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* MRP Product Info Window: infos are shown in Material Cockpit, in WebUI: OK
* correct qties etc. are tested in https://github.com/metasfresh/metasfresh/issues/2646
