### ISSUE TITLE
Barcode scan does not show actions in Manuacturing Order

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#707]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When scanning a Barcode in Manufacturing Order, then the quickactions are not shown anymore.
#### Which are the steps to reproduce?
Select Manufacturing Order, open HU Editor, barcode scan. Quickactions dissappear.
### What is the expected or desired behavior?
Quickactions shall be available.

![image](https://user-images.githubusercontent.com/13365687/33315430-fd4ed536-d430-11e7-893c-6cadc79e6a80.png)

**Comment by teosarca** [comment]
Cannot reproduce:
![image](https://user-images.githubusercontent.com/1244701/33393051-86944e6e-d546-11e7-8a58-02c8f996fafc.png)

**Comment by metas-mk** [comment]
Talked w/ @teosarca 
Is a frontend issue
https://github.com/metasfresh/metasfresh-webui-frontend/issues/1394
closing this one.
