### ISSUE TITLE
Document number not mapped 

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-api#71]
I sometimes get this error when trying to open certain documents ( orders, inouts) :
http://pastebin.com/debPwFCE

I don't know the exact cases when it happens.

**Comment by metas-rc** [comment]
It happened again today, after a series of "Back"- "Forward" clicks.
Stacktrace: http://pastebin.com/Mb8RfVvv

**Comment by teosarca** [comment]
note to IT: pls just check if this one it's still happening

**Comment by metas-lc** [comment]
IT
1. dashboard - sitemap- sales order- shipment candidate - shipment 
=> navigating back and forward worked fine
2. mix between all kinds of documents
=> navigating back and forward worked fine
3. navigating through side list (e.g. go to sales order, open in single view an order, use side list to open another order and so on, now move back and forward)

4. super fast back and forward clicks
(e.g. go to pricelist, warehouse, order, invoice...press back really fast)
in this case, if you move back and forward too fast, you get errors:
- "Internal Server Error"
- exception:"java.lang.IllegalArgumentException"
- message:"View's windowId is not matching the expected one.↵ Expected windowId: 540321↵ View: SqlDocumentViewSelection{viewId=70e433f4-3acc-4500-b23b-8aa42f6b80b4, AD_Window_ID=139, tableName=M_Warehouse, defaultSelection=DocumentViewOrderedSelection{uuid=70e433f4-3acc-4500-b23b-8aa42f6b80b4, size=4, orderBys=[DocumentQueryOrderBy{fieldName=Name, ascending=true}, DocumentQueryOrderBy{fieldName=M_Warehouse_ID, ascending=true}]}}"
- path:"/rest/api/documentView/540321/70e433f4-3acc-4500-b23b-8aa42f6b80b4/quickActions"

- this means that for Warehouse is expecting Pricelist window. 
- also noticed it always happens around pricelist, so make sure you are also selecting it
