### ISSUE TITLE
picking terminal: additional shall support grouping lines by order

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#711]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3078

### What is the current behavior?
Picking terminal window (https://w101.metasfresh.com:8443/window/540345) it's aggregating the lines by warehouse and product.

#### Which are the steps to reproduce?
Open https://w101.metasfresh.com:8443/window/540345.

### What is the expected or desired behavior?
Support 2 methods of aggregation:
* aggregate by warehouse and product (like we are doing it now, but with some layout changes, read below)
* aggregate by order

The aggregation method shall be configured in M_Picking_Config. 
M_Picking_Config will be a new table (and window) where we will store various picking configs (instead of using AD_SysConfig).

#### Warehouse+Product grouping and layout
```
grouping: Product                   |  -          | sum              | sum           | Warehouse | where DeliveryDate min
         line: BP + BPLocation     | Order   | QtyToDeliver | QtyPicked | Warehouse | PreparationDate
```

#### Order grouping and layout
```
grouping: Order + BP              | -            | -                    | -                | Warehouse | PreparationDate
         line: BPLocation              | Product | QtyToDeliver | QtyPicked | Warehouse | PreparationDate
```

**Comment by metas-lc** [comment]
IT
open picking terminal window 
=> products are aggregated by warehouse and product
go to picking configuration window (i used the one in swing, logged in as sysadmin)
set profile to "Group by Order"
go back in picking terminal, refresh the page
=> products are aggregated by order OK
