### ISSUE TITLE
login authenticate: provide an unique key for each JSONLoginRole

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#714]
### Is this a bug or feature request?
FR

### What is the current behavior?
When [login authenticate endpoint](http://w101.metasfresh.com:8081/swagger-ui.html#!/login-rest-controller/authenticateUsingPOST) is called, the provided JSONLoginRole(s) have no unique "key".

#### Which are the steps to reproduce?
Try login and inspect.

### What is the expected or desired behavior?
JSONLoginRole(s) shall have a unique "key" property.
![image](https://user-images.githubusercontent.com/1244701/33542946-c99fea02-d8dd-11e7-9c8a-8879d4399eb6.png)

### Note to IT
Cannot be tested. Check the frontend task.

**Comment by metas-lc** [comment]
IT
tested https://github.com/metasfresh/metasfresh-webui-frontend/issues/1404 OK
