### ISSUE TITLE
picking terminal: scan picking slot by barcode

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#716]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3078

### What is the current behavior?
There is no way to scan and filter a picking slot(cart) by barcode.

### What is the expected or desired behavior?
Have "Scan picking slot" filter:
![image](https://user-images.githubusercontent.com/1244701/33553702-6eecc06a-d902-11e7-8c09-30be18ecb037.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* "Scan picking slot" filter in picking terminal: OK, but name needs to be changed:

![2017-12-05 17_48_47-metasfresh](https://user-images.githubusercontent.com/18696715/33619163-c232dcb8-d9e4-11e7-99ba-382bbd52b724.png)

* filtering for a barcode of an HU in the picking slot: Internal Server Error, bc picking slot for bpartner wasn't found, although slot is set with bpartner:

![2017-12-05 17_54_16-metasfresh](https://user-images.githubusercontent.com/18696715/33619432-8b23346a-d9e5-11e7-913c-9dbc69c08806.png)

**Comment by teosarca** [comment]
@metas-dh 
* i've added that missing message. The label shall now display "Scan picking slot"
* about that error message, that error message is thrown when no picking slot is found (in database, the message is PickingSlot_NotFoundFor_PartnerAndLocation). The filter you are using is ONLY for scanning picking slots and not HUs.

**Comment by metas-dh** [comment]
Results of IT2

* Scan picking slot" filter in picking terminal: now also called  Scan picking slot: OK
* Filtering for a picking slot: 
1. filter working fine: only picking slot that matches is displayed, OK
2. all picked HUs currently inside the picking slot are displayed: OK
3. working for all picking slots: dynamic slots, rack system slots, and other slots: OK

questions:
* all picking slots show the same HU, which is currently the source HU in picking terminal, after filtering, is that wanted?

![2017-12-08 09_49_15-metasfresh](https://user-images.githubusercontent.com/18696715/33758319-12ee2002-dbfe-11e7-84c8-41895d9473fc.png)

![2017-12-08 09_49_40-metasfresh](https://user-images.githubusercontent.com/18696715/33758326-19ba298a-dbfe-11e7-883c-6aa15f5f2d07.png)

**Comment by teosarca** [comment]
> all picking slots show the same HU, which is currently the source HU in picking terminal, after filtering as well, is that wanted?

@metas-mk  wdyt?

**Comment by metas-mk** [comment]
Source HU shall be warehouse dependant (for now). shall not consider in which picking slot the user was when selecting it initially. So seems ok to me.
