### ISSUE TITLE
picking terminal: open HUs to pick shall display Best Before date and Locator

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#717]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3078

### What is the current behavior?
The HUs view displayed when the "open HUs to pick" action is called looks exactly like in any other place where the HUs are displayed.

#### Which are the steps to reproduce?
* picking terminal view: https://w101.metasfresh.com:8443/window/540345
* select something and Pick
* select a picking slot and call the "open HUs to pick" action
* the HUs to pick view is displayed on right side of the modal panel

### What is the expected or desired behavior?
That HUs view shall display the "HU Best Before Date" and "Locator" columns.
The Locator shall be formated as `Warehouse Name`_`Locator Name` _ `X` _ `X1` _ `Y` _ `Z.`
The HUs shall be sorted by Best Before Date, ascending (the ones which are about to expire at the top).

**Comment by metas-lc** [comment]
IT
went to warehouse and renamed fields (for visibility). Set:
aisle to x
Rack to x1
Tray to Y
Level to Z
also updated the name
went to picking slots, selected a line, used pick -> open hu selection window
=> last 2 columns are bestbeforedate and locator OK
=> locator is called Warehouse Name_Locator Name _x_x1_Y_Z OK

go to receipt candidates and make some HUs with Mindesthaltbarkeit attribute set
also make sure you have an LU with 2 different TUs, each with different Mindesthaltbarkeit 
go to picking slots, select a line, use pick -> open hu selection window
=> beste before date is set like you set on the LU and each TU OK
