### ISSUE TITLE
picking terminal: HUs to pick: scan/filter by Locator

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#721]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3078

#### Which are the steps to reproduce?
* picking terminal 
* select a line and Pick
* select some picking slot and "Open HUs to pick"

### What is the expected or desired behavior?
In HUs to pick view (see above) we need an "Scan locator" filter.
After users scan the Locator, only the HUs for that locator will be displayed.
First matched HU shall be selected by default.

#### Locator barcode
At the moment, we will consider the M_Locator_ID as Barcode.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new Filter in picking terminal, HU selection window, "Scan Locator": OK
* scanning for locator (atm, M_Locator_ID): only HUs for this locator are displayed: OK
* first matched HU is selected by default: OK
