### ISSUE TITLE
picking terminal: picking slot rows shall NOT have duplicate IDs

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#722]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
Issue described here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1373#issuecomment-349571505
i.e.
 we have an issue with duplicated ids. please, take a look at this.
![screenshot at dec 06 09-20-25](https://user-images.githubusercontent.com/18234060/33652313-3d2e77c2-da69-11e7-8761-ccf84c21dc04.png)

### What is the expected or desired behavior?
the included TU and CU shall not have the same IDs.

**Comment by metas-lc** [comment]
Tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1373 and worked fine OK
