### ISSUE TITLE
picking terminal: HUs to pick: Pick CUs process

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#723]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3078

### What is the current behavior?
There is none :)

#### Which are the steps to reproduce?
* open picking terminal 
* select a line and call Pick
* select a picking slot and call "Open HU selection window"
* select an HU and we will be able to call an new process called "Pick CUs".

### What is the expected or desired behavior?
The "Pick CUs" process shows the product and qty to be picked.
A scan of the product is awaited.
If it's the correct product then the user can enter the QtyCU to be picked.
If not then an error appears that says "wrong product".

**Comment by metas-lc** [comment]
IT
1. make sure you have multiple products in picking terminal
2. make sure you have multiple products in warehouse
3. go to picking terminal, select a product, use Pick
4. select a slot, open HU selection window
5. select an HU, use Pick CUs
=> modal opens and asks you about product and qty OK
=> if you select a product that is not on the HU: Error: You scanned the wrong...
Server error
You scanned the wrong product: Radiesli gerüstet Industrie. Product Frisée Industrie was expected. OK
=> if you put a qty >qty on that HU, will take the max qty  OK
=> after you pick cu, the slot updates, and also the HU. If you use again "open HU selection window" you can see OK

6. open HU selection window and select 2 HUs, use Pick CUs
7. add the product name and qty
=> Error: Only one HU shall...
Server error
Only one HU shall be selected
(NOK ? i think we should make the process readonly when more HUs are selected.. or?)

8. make sure you have an LU with 2 different products on it
9. pick one of those products and run Pick CUs on that LU, take a small qty
=> modal opens and asks you about product and qty OK
=> if you select the other product that is on the HU but not on your line: Error: You scanned the wrong...
Server error
You scanned the wrong product: Radiesli gerüstet Industrie. Product Frisée Industrie was expected. OK
=> if you put a qty >qty on that HU, will take the max qty  OK
=> after you pick cu, the slot updates, and also the HU. If you use again "open HU selection window" you can see OK

10. pick from an TU that is not on LU
=> picks fine, no errors, same as above OK

**Comment by teosarca** [comment]
@metas-lc  fixed.
Also do regression on Pick HU process. That one shall be work with multiple HUs selected. In that case all of them shall be picked.

**Comment by metas-lc** [comment]
IT
retested steps 6 and 7
=> pick CUs is readonly OK

**Comment by metas-ts** [comment]
cherry-picked to `release`
