### ISSUE TITLE
Allow search of Subproducer

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#727]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to search the subproducer in Handling Unit Editor in material Receipt Candidates.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Change the dropdown field to a lookup widget. The user shall be able to search & autocomplete w/ dropdown list. Identifier shall be BPartner, value and GAP.

### How to configure an atttribute to be Lookup field
NOTE: works only in webui

![image](https://user-images.githubusercontent.com/1244701/33804615-3eecb31c-ddb1-11e7-83ca-43c1c006a545.png)

**Comment by metas-lc** [comment]
IT
wait for frontend task:  https://github.com/metasfresh/metasfresh-webui-frontend/issues/1433

**Comment by metas-lc** [comment]
IT
tested it here https://github.com/metasfresh/metasfresh-webui-frontend/issues/1433 OK
question: 
"Identifier shall be BPartner, value and GAP." if it's about how you can search for the bpartner, i notice you can find it only by name
