### ISSUE TITLE
hide Receive HUs (default) when there are no HUs

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#735]
### Is this a bug or feature request?
bug
### What is the current behavior?
material receipt candidates window - lines with no packing item have receive HUs as the default action  
#### Which are the steps to reproduce?
1. create a purchase order, add a product line, don't set any HU, complete
2. zoom to material receipt candidates
=> receive HUs is the default action  NOK
3. select receive HUs 
=> Error: LU/TU configuration is resulting...
Server error
LU/TU configuration is resulting to infinite quantity: X_M_HU_LUTU_Configuration[M_HU_LUTU_Configuration_ID=1000020, trxName=<<ThreadInherited>>]
### What is the expected or desired behavior?
hide that action

**Comment by teosarca** [comment]
> default action is now "Close row", is that wanted? shouldn't it be "Receive CUs"?

agree, but that another topic.

> action "Receive HUs" is not hidden, can still be selected: imho that's OK, since you can e.g. put the CUs e.g. on a LU

agree

**Comment by metas-dh** [comment]
> agree, but that another topic.

created #915, closing this one.
