### ISSUE TITLE
Weighing not working correctly in material receipt candidate

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#742]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Weighing is not working correctly in material receipt candidate
#### Which are the steps to reproduce?
1. Have a material receipt candidate with UOM:kg
2. Open HU Editor, with e.g. 1LU/1TU config: weight gross: empty, NOK

![2017-12-13 13_46_12-metasfresh](https://user-images.githubusercontent.com/18696715/33940235-83f638e8-e00e-11e7-9900-9fc4735e1e36.png)

3. Set a weight, check the qty in the HUs: no change, NOK

![2017-12-13 13_47_49-metasfresh](https://user-images.githubusercontent.com/18696715/33940250-8e40af72-e00e-11e7-85c4-48a4b615daf3.png)

4. Select the TU: weight gross: empty, NOK

5. Select the LU again: weight gross: empty again, NOK

6. Create the receipt: only now you can see the weight that was set

![2017-12-13 13_49_15-metasfresh](https://user-images.githubusercontent.com/18696715/33940267-9e162fb2-e00e-11e7-8efd-fd656f78459d.png)

### What is the expected or desired behavior?
1. Weight gross shall be: weight LU + weight TU + weight product (as ordered)
2.  After weight was changed, this shall be shown in the HUs (Qty CU)
3.  The value set by the user in weight gross shall be saved

**Comment by teosarca** [comment]
note: API is providing all attributes but for some reason, frontend fails to render them....

**Comment by metas-dh** [comment]
frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1444
closing this one.
