### ISSUE TITLE
Ordering problem in included tabs

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-api#743]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* If I want to order by a certain column in included tabs, the first time it works, but afterwards it doesn't work any more and they stay in the same order no matter how many times I press that column again.
#### Which are the steps to reproduce?
* I noticed this is other windows too, but I will use the window Contract as example
* Go to Contract, select an entry that has several Subscription Forecast entries
* The entries come ordered by seqNo:

![image](https://user-images.githubusercontent.com/16001442/33942240-f3a1e78c-e01d-11e7-95b0-4ab0f2df8a1d.png)

* Order the Subscription Forecast entries by date

![image](https://user-images.githubusercontent.com/16001442/33942274-13d0bdd0-e01e-11e7-9b0c-0e9e41a04ebc.png)

* Click on the Date column header again (to order the other way around) 
* => NOK: They are the same

![image](https://user-images.githubusercontent.com/16001442/33942299-33338586-e01e-11e7-85d8-995376657b5c.png)

### What is the expected or desired behavior?

* They entries should be ordered correctly as many times as I click the column header.

**Comment by teosarca** [comment]
frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1445
