### ISSUE TITLE
Batch entry mode w/o Packing Instruction

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#745]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, when using Batch entry mode in metasfresh, we always have a combination of Product and Packing Instruction.
#### Which are the steps to reproduce?
Open, try and see, e.g. in Sales Order.
### What is the expected or desired behavior?
It shall be possible to switch off the packing instruction in Batch entry mode. This could be done systemwide w/ a system configuration.
Alternative idea: Have a flag-seqno combination in ui-element and sub that declares which elements are Batch entry.

### Configuration
Check `webui.quickinput.EnablePackingInstructionsField` sysconfig.
By default it's enabled.

**Comment by teosarca** [comment]
Note to IT: Order and Forecast batch entries are affected by this task. Pls test them with and without packing instructions field enabled.

**Comment by metas-lc** [comment]
IT
sysconfig Y
sales and purchase order
=> batch entry have product + HU OK
=> product gets in line with or without hu (depending if the product has hu) OK
forecast
=>batch entry have product + HU OK
=> product gets in line with or without hu (depending if the product has hu) OK

sysconfig N
sales and purchase order
=> batch entry doesn't have product + HU OK
=> product gets in line with No Packing Item OK
forecast
=>batch entry have product + HU OK
=> product gets in line with or without hu (depending if the product has hu) OK???
shouldn't it be with  No Packing Item??


in all cases i tested with a product that has HUs and with one that doesn't
to check: why on purchase order line i can't see the HU (only no packing item) on dropdown
