### ISSUE TITLE
Picking Tray Clearing: Scan picking slot barcode filter

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#746]
### Is this a bug or feature request?
FR
part of https://github.com/metasfresh/metasfresh/issues/3190

### What is the current behavior?
no such filter

### What is the expected or desired behavior?
![image](https://user-images.githubusercontent.com/1244701/34000983-7c351c2a-e0f7-11e7-89cf-319427d87cef.png)

**Comment by metas-lc** [comment]
IT
1. go to Picking Tray Clearing (Prototype)
=> see filter: scan picking slot OK
2. use Scan picking slot filter
=> it looks like a barcode filter, you write smth like 105.0 and press enter. Filter works fine
3. press on filter again
=> the value is still there. If you want to remove it delete and press enter OK
4. remove what you wrote, press enter
=> all slots are shown OK
5. use the filter again on a picking slot that doesn't exist
=> Error: Zum Geschäftspartner <-1>, Standort...
Server error
Zum Geschäftspartner <-1>, Standort <-1> konnte kein Picking Slot gefunden werden.
and the last slot you had filtered is still there OK?
