### ISSUE TITLE
Picking Tray Clearing: filter picking slots by Partner

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#747]
### Is this a bug or feature request?
FR
part of https://github.com/metasfresh/metasfresh/issues/3188

### What is the expected or desired behavior?
[Picking Tray clearing](https://w101.metasfresh.com:8443/window/540371) shall be filterable by BPartner.

**Comment by metas-lc** [comment]
IT
went to Picking Tray Clearing, filer by bpartner
selected different bpartners => worked fine, but when it didn't find a slot for that bpartner got error:
Error: Zum Geschäftspartner <-1>, Standort...
Server error
Zum Geschäftspartner <-1>, Standort <-1> konnte kein Picking Slot gefunden werden.
(need to check if it can be fixed here: https://github.com/metasfresh/metasfresh-webui-api/issues/752 or i shall create a new task)

i also added some HUs on some pickingslots and a bpartner was set on them => filter showed them OK

other issue: the filter seems to small and i cannot use the scrollbar. If i press on a scrollbar no bpartner is set and it closes
![image](https://user-images.githubusercontent.com/16001666/34113089-42e05728-e417-11e7-9847-9f4020d723f0.png)
