### ISSUE TITLE
Picking Tray Clearing: packing HUs: Add to Transportation Order action

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#751]
### Is this a bug or feature request?
FR
part of https://github.com/metasfresh/metasfresh/issues/3188

### What is the current behavior?
-

### What is the expected or desired behavior?
* open Picking Tray Clearing
* select a picking slot
* make sure you have some HUs in the right side view
* select one or more and call the new "Add to Transportation Order" action
* the action opens and user is able to select an open Transportation Order

When the process is executed, it shall
* create M_Package(s), M_Package_HU(s) and link them to given Transportation Order
* the HUs added to the transportation order shall no longer be visible in the right side view, nor later.

### Note to IT
Regression:
* make sure that adding an HU to transportation order still works in Swing.

**Comment by metas-lc** [comment]
IT
1. repeated the testcase above: i had some HUs on the right side in Picking Tray Clearing and also made a transportation order
2. select one or more and call the new "Add to Transportation Order" action
=> i had to add "10" to have something in search, then "1000233" appeared, which is the docno of my transportation order
(question: should if have appeared after i wrote 1? ) NOK (backend)
3. the HU(s) gone, and they appeared in transport line OK
(m_Package(s) and m_Package_HU(s) are created)

regression: 
0. i had to go to a picking slot and made the locator verdichtung !!!! it was set on the main locator.. 
1. picked some hus in kommissionier terminal (on the picking slot with verdichtung locator)
2. went to verdichtung pos 
3. selected the HU(s) and set a transportation => they got grey Ok
4. closed and made inouts => worked OK
(in speditionsauftrag the package was created OK)

then i tested again on the webui with this slot with verdichtung  OK
