### ISSUE TITLE
Picking Tray Clearing: picking slot filter no results

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#752]
### Is this a bug or feature request?
fr
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/746, https://github.com/metasfresh/metasfresh-webui-api/issues/747
part of https://github.com/metasfresh/metasfresh/issues/3190
### What is the current behavior?
if you filter for a slot that doesn't exists, you'll get an error. Shall get no rows message on empty window, like in the other filters
#### Which are the steps to reproduce?
open Picking Tray Clearing, filter for a slot that doesn't exists. e.g. 1111
=>  Error: Zum Geschäftspartner <-1>, Standort...
Server error
Zum Geschäftspartner <-1>, Standort <-1> konnte kein Picking Slot gefunden werden.

### What is the expected or desired behavior?
Shall get no rows message on empty window, like the other filters
"There are no detail rows
You can create them in this window."

**Comment by metas-lc** [comment]
Same issue if you filter for bpartner
"Error: Zum Geschäftspartner <-1>, Standort...
Server error
Zum Geschäftspartner <-1>, Standort <-1> konnte kein Picking Slot gefunden werden."

please fix both filters in this task

**Comment by teosarca** [comment]
note to IT:
regression: on swing UI, picking shall (still) show error when there were no picking slots found for BPartner.

**Comment by metas-lc** [comment]
IT
Picking Tray Clearing: checked both filters: scan picking slot and business bpartner
=> when you add a slot or bpartner that doesn't exist for any slots, then you don't get any errors, just the empty rows with "There are no detail rows
You can create them in this window."
OK
=> rest works the same OK

swing: inactivated most pickingslots (those without bpartners), opened kommissioner terminal for a bpartner that doesn't have picking slot
=> still get error message OK
Zum Geschäftspartner G0001, Standort teststraße 996
45678 teststadt 3 konnte kein Picking Slot gefunden werden.

also checked Picking Terminal -> picking -> scan picking slot 
=> no errors, just "no detail rows" 
Zum Geschäftspartner G0001, Standort teststraße 996
45678 teststadt 3 konnte kein Picking Slot gefunden werden.
