### ISSUE TITLE
Processes: support for parentViewSelectedIds and childViewSelectedIds

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#755]
### Is this a bug or feature request?
FR
part of https://github.com/metasfresh/metasfresh/issues/3190
required for https://github.com/metasfresh/metasfresh-webui-api/issues/758

### What is the current behavior?
When starting a process from a view, frontend provides view's current selected row IDs (i.e. viewDocumentIds).

### What is the expected or desired behavior?
Frontend shall be able to provide:
* parentViewId/parentViewSelectedIds
* childViewId/childViewSelectedIds

### Note to IT
Consider testing the frontend task, or better the task for whom this one was made, i.e. https://github.com/metasfresh/metasfresh-webui-api/issues/758

**Comment by metas-lc** [comment]
tested in https://github.com/metasfresh/metasfresh-webui-api/issues/758
