### ISSUE TITLE
Picking Tray Clearing: process to take out an HU and add it to existing HU

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#758]
### Is this a bug or feature request?
part of https://github.com/metasfresh/metasfresh/issues/3190

### What is the expected or desired behavior?
Have a process which allows user to transfer Qty from a picking tray HUs to an existing HU.

The process shall be available when:
* you select a top level HU on left side (picking slots clearing view)
* you select a top level HU on right side (HUs to pack view)

The process has one param, the QtyCU which is set, by default, to picking slot's HU available quantity.

If, after running the process, the picking slot's HU becomes empty, it shall be destroyed and it shall vanish from left side.

### Note to IT
wait for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1465

**Comment by metas-lc** [comment]
IT
1. created sales order went to picking terminal and picked some LUs
2. processed the picking and went to picking tray clearing
=> on left side i had those LUs, on right side was empty (for me)
3. i took out an HU
4. selected an LU from left side and the one from right side
5. used Take Out and add to new HU
=> the new TU appeared on right side, but not on the LU and the LU from left side disappeared OK
6. selected an LU from left side and the one from right side
7. used Take Out and add to HU
=> the new TU appeared on right side, on the LU i selected and the LU from left side disappeared OK
8. using take out HU moved the whole LU to the right OK
9. partially moving hu to another hu updates both left and right correctly OK
