### ISSUE TITLE
Picking Tray Clearing: process to take out an HU and add it to new HU

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#760]
### Is this a bug or feature request?
part of https://github.com/metasfresh/metasfresh/issues/3190

### What is the expected or desired behavior?
Have a process which allows user to take out a given amount of CUs and add them to new HU.

### Note to IT
wait for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1465

**Comment by metas-lc** [comment]
tested in https://github.com/metasfresh/metasfresh-webui-api/issues/758
