### ISSUE TITLE
Show onhand quantity in new WebUI MRP Product Info Window

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#762]
### Is this a bug or feature request?
FR

### What is the current behavior?
as I learned from #706 there is a representation of the MRP Product Info in WebUI.
this issue is about also showing onhand quantity in that window.

### What is the expected or desired behavior?
@metas-mk feel free to design it

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* On Hand Qty in Material Cockpit was increased after receipt was created
=> stopped testing bc connections crashed (a lot of requests were sent for material cockpit update)

**Comment by metas-dh** [comment]
Update:

* On Hand Qty is shown in Material Cockpit: OK
* testing of correct qties etc. will be done in #754
