### ISSUE TITLE
Precision Layout in Price of Orderlines

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#766]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the price precision in orderlines  (invoicelines, invoice schedule) are not respected. Even if precision 3 is recored, only 2 digits are shown.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Show the digits that are defined in product prices or in recording of prices.

**Comment by teosarca** [comment]
Update, as discussed with @metas-mk, now will work as following:
(applies for views and included tabs)
Amounts/Costs/Quantities will be displayed with 2 decimals.
If an amount has more than 2 decimals (leading zeros does not count!), those extra decimals will be displayed up to 5 decimals.

### Suggested test cases:
#### Product prices view
* open product prices view: https://w101.metasfresh.com:8443/window/540325
* on some product prices, set a price with more than 2 digits.. e.g. 1.1234
* go to grid mode: that price shall be displayed correctly (i.e. 1.1234), all other prices from the same column shall have 2 digits
* keep that view open and in another browser tab open a particular product price and change the price.
Take a look at the product prices view (DO NOT refresh!)... it shall display correctly the changed price

#### Sales Order/Order line 
The test is similar with previous one but on sales order line.
Make sure you are using a product which has a price with more than 2 decimals. You can reuse the products you changed on previous test ;)

Same, open the order in another browser tab. Edit there the order line, changing the Price.
Observe the first browser tab where you also have the order opened. The order line shall display correctly the new price (DO NOT refresh).

**Comment by metas-lc** [comment]
IT
Product price window
1. open 2 tabs of product price window (window/540325)
2. start updating prices in grid and dock view in one tab
3. check the other tab without refreshing
=> prices are updated OK
4. set prices like 6.0666666, check griview and docview
=> in gridview is 6.06667 and in docview remained as you set it (6.0666666) OK
5. add prices like 1 or 1.5
=> in both grid and docview are updated to 1.00 and 1.50 OK

Sales order Line
