### ISSUE TITLE
Picking Tray Clearing: packing HUs: generate shipper's package label 

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#768]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/763
part of https://github.com/metasfresh/metasfresh/issues/3190

### What is the current behavior?
Task https://github.com/metasfresh/metasfresh-webui-api/issues/763 and https://github.com/metasfresh/metasfresh-webui-api/issues/751 implemented actions which allows user to add selected HU(s) to a given shipper transportation document.

### What is the expected or desired behavior?
When adding the HUs to a shipper transformation, if possible, we shall contact shipper's API, generate and print the shipper's label which shall be stick on the package.

**Comment by teosarca** [comment]
update: WIP

**Comment by metas-ts** [comment]
@teosarca  this issue is hard to CP. please check whether it's really needed and if you think it is, coordinate with me in the respective channel

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Set up Shipper gateway: you need to have GO as shipper, and also set the GO config in Shipper window
2. Set up printing (printing config, hardware printer etc., pls note: printing is disabled by default in metasfresh, you need to enable it!)
3. Create a transportation order, with GO as Spediteur: **important**: the transportation order must not have pick up date in the past, so you cannot use an old one!
4. Create a sales order & do picking for it
5. In Picking Tray Clearing, select the picked HU on the left side and use Take out HU action, to move the HU to the right window
6. Select your HU on the right side, and use "Add to Transporation Order, Ship and Invoice" action (**not** the other  one, "Add to Transportation Order"!)
  * notification for invoice & shipment being created: OK
7. Check the printing queue:
  * 3 new entries: shipment, invoice & package label (only sec.s apart): OK
8. Check GO delivery order window:
  * new order was created: OK
  * check attachments of your order: label in PDF form is attached (you can use alt+p to check the print preview too): OK



follow up for the case the delivery order fails:
