### ISSUE TITLE
New context variable for isWebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#769]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we don't have the context isWebUI that allows to use in Display Logic.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the context isWebUI to be used in display logic.

**Comment by metas-lc** [comment]
tested in tested in https://github.com/metasfresh/metasfresh/issues/3260 OK
