### ISSUE TITLE
Raise session Timeout of WebUI Application

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#770]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
After Login to WebUI and roughly 5-15 mins of inactivity, the session seems to be expired. When the user then starts a Sales Order window, for example, the response is 401 and the user gets forwarded to the login page.
#### Which are the steps to reproduce?
Open try and see.
### What is the expected or desired behavior?
Raise the "Session" timeout to at least 120min.

### Configuration
Check `server.session.timeout` from `application.properties`.
By default this is set to 7200(seconds).

**Comment by teosarca** [comment]
note: we introduced FixedMapSessionRepository which is a re-implementation of MapSessionRepository which fires session created/destroyed events.
About this topic, there was a discussion on spring-session project: https://github.com/spring-projects/spring-session/issues/151

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

Opened a session ( on incognito) at 13:42

* OK: Checked at 13:50 -> it opened correctly, no login required
* OK: Checked at 14:50 -> it opened correctly, no login required
