### ISSUE TITLE
EMail Attachment Name in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#772]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the eMail Attachment Caption has %28 and %29 char that look ugly in the browser when opening the eMail Editor.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Remove those char and add "-" instead. If easily possible also add the document no to the Attachment name. Drop the "Jasper" string.

Example:
Bestellung-123456.pdf

![image](https://user-images.githubusercontent.com/13365687/34639912-3cdf9d08-f2e9-11e7-8ec8-8d283e17cf8a.png)

**Comment by teosarca** [comment]
update: the report file name is build as follows (first rule which applies and returns an non empty result):
* if document, IDocument.getDocumentInfo() will be used; depends on implementation, usually that method is returning "document type<space>document no".
* process title if not empty (shall not be empty!?!)
* fallback: report_<AD_PInstance_ID> (shall not happen).

So, in case of purchase order, the attachment looks like this:
![image](https://user-images.githubusercontent.com/1244701/34993303-9f327e3e-fad8-11e7-905f-3bae6d29bc4b.png)

**Comment by metas-mk** [comment]
Testes. Works nicely. Closing.
