### ISSUE TITLE
Add name and menu entry for WebUI window Package

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#773]
### Is this a bug or feature request?
FR
### What is the current behavior?
You can zoom into the window Package (Packstück) from window Transportation Order (Transport Auftrag), but the window has no proper name and cannot be found in menu (window/319).
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Pls add the name and menu entry for the window.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: The window Package is in the menu
* OK: The window respects our layout conventions and cornerstoned
* OK: The included tab which supports new has white background.
* NOK: The included tab is not usable. Followup created:  https://github.com/metasfresh/metasfresh-webui-api/issues/900

* OK : All the fields are translated in both German and English.
