### ISSUE TITLE
error when using TU to new TUs transform

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#774]
### Is this a bug or feature request?
bug
### What is the current behavior?
if you use transform TU to new TUs and there is more than 1 TU you get an error
#### Which are the steps to reproduce?
open receipt candidates, select a product - open hu editor with 1 LU and 6 TUs
select the TUs, use transform - TU to new TUs
=> looks like nothing happened, but the attributes are not available anymore and error:
error:"Not Found"
exception:"de.metas.ui.web.exceptions.EntityNotFoundException"
message:"No document found for rowId=1000132"
path:"/rest/api/documentView/540189/540189-be02d14ae88549e0a19ff2c2ec925648/1000132/attributes/layout"
### What is the expected or desired behavior?
shall move out those 6 TUs

**Comment by teosarca** [comment]
cannot reproduce. might be that it was already fixed

**Comment by metas-lc** [comment]
IT
could not reproduce OK
=> 6 new TUs were created and LU removed. No errors
