### ISSUE TITLE
Use readOnlyFlag from AD_Field and AD_Tab when creating DocumentLayoutElements

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#778]
### Is this a bug or feature request?
FR
### What is the current behavior?
Currently, the read-only behavior of fields is very static.

#### Which are the steps to reproduce?
In generic windows (like sales orders), e.g. quantities are always right click-editable

### What is the expected or desired behavior?
If one of the following is set to `Y`, then the field shall not be editable in the webui
* `AD_Field.IsReadOnly`
* `AD_Tab.IsReadOnly`
* `AD_Table.IsView`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

tested in different windows, with different fields / tabs / tables
* `AD_Field.IsReadOnly`: if set=Y: not editable in Webui, OK
* `AD_Tab.IsReadOnly`: if set=Y: not editable in Webui, OK
* `AD_Table.IsView`: if set=Y: not editable in Webui, OK

problem: for testing i set field pricesystem in sales order readonly='Y'; the field in this sales order remained readonly also after i set it back to readonly=N, when the order was still in status:Draft, although it was editable in a newly created sales order
