### ISSUE TITLE
HU editor view gets empty after splitting out one TU

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#781]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* open HU editor window: https://w101.metasfresh.com:8443/window/540189
* look for an LU with multiple TUs
* select the TU line and call Transform, TU to new TUs, 1 TU and press OK
=> the view gets empty: NOK,
but after requerying the HU editor window, the HU is there: OK

### What is the expected or desired behavior?
* the view shall not get empty
* the view shall show the newly (split) TU as last line

**Comment by teosarca** [comment]
note: found while testing/fixing https://github.com/metasfresh/metasfresh-webui-api/issues/781

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The view doesn't get empty after transforming TU to new TUs
* OK: The newly created TUs are displayed at the bottom of the view (last lines) after they are split.
