### ISSUE TITLE
Act gracefully on old/invalid AD_UserQuery

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#785]
### Is this a bug or feature request?
FR
### What is the current behavior?

If a system has an AD_UserQuery with a column that doesn't exist anymore, then getting the webui layout fails

### What is the expected or desired behavior?

It should instead just 
* log a warning (create an AD_Issue)
* deactivate the AD_UserQuery in question
* move on

**Comment by metas-ts** [comment]
ìmplemented in `master` and `2018-06`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* have an invalid AD_UserQuery: change an AD_UserQuery in e.g. printing queue, with an invalid value (in db)
* run that AD_UserQuery, check: AD_UserQuery is set to isactive=N, description: info about invalidity: OK 
* no webui layout fail: OK
