### ISSUE TITLE
deadlocks occuring around material cockpit

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#787]
### Is this a bug or feature request?
Bug
### What is the current behavior?
If you play around with the material cockpit you sooner or later experince a deadlock

**Comment by metas-ts** [comment]
fixed in branches `master` and `2018-06`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

played around with material cockpit for a while: created sales & purchase orders, reactivated and completed them again, changed date promised etc.: material cockpit was updated correctly after a few sec., no deadlock: OK
