### ISSUE TITLE
Allow Filtering of Label-Type-Fields in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#788]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to add a label-type-field in WebUI grid view.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the possibility to search for the content (labels) of label-type-fields. The search field shall look and feel like the content fields, with the same recording functionality. Entered search labels shall be concatenated w/ OR (AND?).

![image](https://user-images.githubusercontent.com/13365687/35097049-b9f96918-fc4e-11e7-9a1c-662b5f8d0e06.png)

### Configuration
![image](https://user-images.githubusercontent.com/1244701/35183132-95acfefc-fde9-11e7-958d-0cec7676a401.png)

**Comment by teosarca** [comment]
note: 
> Entered search labels shall be concatenated w/ OR (AND?).

for now, labels are ANDed. So basically, if you filter by 2 labels you will get all records where at least those 2 labels were assigned.

**Comment by metasnw** [comment]
IT 
OK: works fine for reference list when you use the mouse to select
OK: in case you are typing the label its also working now after fix 
https://github.com/metasfresh/metasfresh-webui-frontend/issues/1520
