### ISSUE TITLE
Provide "loadDuration" when fetching document references

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#793]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
* open some document
* check the document references, also have chrome Network tab open
* check the ".../references" reponse, it shall have entries like:
![image](https://user-images.githubusercontent.com/1244701/35149921-ac739e9e-fd20-11e7-93d7-789b0951e557.png)

**Comment by metas-dh** [comment]
Results of IT
tested in mf15

checking document references:  "loadDuration" is shown in  Network ".../references" reponse: OK
