### ISSUE TITLE
Provide actions's evaluateDuration

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#794]
### What is the expected or desired behavior?
Each action which is provided to frontend (via quickActions in case of views or via actions in case of single document) shall contain "evaluateDuration" property.
That's how long it took to evaluate that action and check if is applicable in current context.
Technically, how much took de.metas.process.IProcessPrecondition.checkPreconditionsApplicable(IProcessPreconditionsContext).

It shall look something like this:
![image](https://user-images.githubusercontent.com/1244701/35151088-97482a08-fd25-11e7-9f77-a19e17a646e2.png)

![image](https://user-images.githubusercontent.com/1244701/35151103-a39d22a4-fd25-11e7-8647-355965c64d93.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

checking document actions: "evaluateDuration" is shown in Network, for each action displayed: OK
