### ISSUE TITLE
error on filter with +/- buttons

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#796]
### Is this a bug or feature request?
bug
### What is the current behavior?
error when you use filter with +/- buttons

#### Which are the steps to reproduce?
1. open window 540253
2. use the filter
=> "Failed converting DateDoc's value '2018-01-20T01:00:00+02:00' (class java.lang.String) to class java.util.Date↵ LookupDataSource: null↵ Widget type: Date"

**Comment by teosarca** [comment]
update: i've just improved the error message.
this is not a backend issue, see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1387#issuecomment-359116926

**Comment by metas-rc** [comment]
Moving to done because it's a frontend problem.
