### ISSUE TITLE
Allow Filtering for Table References and show table identifier

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#798]
### Is this a bug or feature request?
Feature Request
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/788
### What is the current behavior?
Currently, it's not possible to add a Label Field as Filter Element which does not point to a reference list, but to a Table ID.
#### Which are the steps to reproduce?
Check Testcase for Location in Business partner window. Open the Filter and Try last Filter entry.
### What is the expected or desired behavior?
Shall work.

**Comment by metasnw** [comment]
IT: working fine
