### ISSUE TITLE
Transforming aggregated CU with "CU to existing TU" not working correctly

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#801]
### Is this a bug or feature request?
Bug, i think
### What is the current behavior?
An aggregated CU cannot be transformed by using the "CU to existing TU" action, causes an error.
#### Which are the steps to reproduce?
1. Open HU Editor in material receipt candidates, with e.g. 1 TU (G1 x 10kg) on 1 LU
2. Select the CU line, use action Transfom
3. Select "CU to new TU", with G1 and qty: 1
=> new TU is created with qty: 1: OK (original LU now has 1 TUs with qty: 9
4. Select the CU line of the TU on the LU, use action Transform
5. Select "CU to existing TU", set qty: 1, and select the new standalone TU:
=> error:
`
"Internal Server Error"
exception
:
"de.metas.handlingunits.exceptions.HUNotAssignableException"
message
:
"Assigning HUs which are not top-level is not allowed↵Zeile Nr.: X_M_ReceiptSchedule[M_ReceiptSchedule_ID=1000001, trxName=null]↵Handling Units: 1000102 (ID=1000102)"
path
:
"/rest/api/process/ADP_540763/1002365/start"
`

### What is the expected or desired behavior?
Transfom shall work.

**Comment by metas-lc** [comment]
IT
1. tested the testcase above: 
1 LU 1 TU 10 CUs
used "CU to new TU" qty 1 => works fine, new TU was created, qty 1. Old TU and LU were updated with qty 9 OK
used "CU to existing TU" qty 1 => works fine, the new TU has now qty 2 and 2 CUs OK
created inout => product has qty 10 OK

2. similar with the testcase above, opened HU Editor with 1 TU 10 CU
used "CU to new TU" qty 1 => works fine, new TU was created, qty 1. Old TU was updated with qty 9 OK
used "CU to existing TU" qty 1 => works fine, the new TU has now qty 2 and 2 CUs. Old TU has qty 8 OK
created inout => product has qty 10 OK
