### ISSUE TITLE
Reduce Export Time for massive excel Exports

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#813]
### Is this a bug or feature request?
FR

### What is the current behavior?
see #744 

### What is the expected or desired behavior?
export 11K records < 1 minute and 100K records in < 10 min.
be it async + notification or with a loading bar

**Comment by teosarca** [comment]
note to IT:
* pls test selecting all rows and selecting just some rows
* regression: test in swing too

**Comment by metas-ts** [comment]
CPed to `release`

**Comment by metasnw** [comment]
Tested with various data sets both small and big (>12K)
