### ISSUE TITLE
Transform TU to exiting LU takes too long for Handling Unit Dropdown List

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#815]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Transform TU to exiting LU takes too long for Handling Unit Dropdown List, In environments with a lot of Handling Unit date, this can take 5-6 mins.
#### Which are the steps to reproduce?
- Open Picking Tray Clearing
- Select Picking Try
- select TU
- Start Action Transform
- Select Action "TU to existing LU"
- Press space in Handling Unit (LU). Loading indicator Pending.
### What is the expected or desired behavior?
Shall work much faster.

![image](https://user-images.githubusercontent.com/13365687/35683458-4a4fb68c-0764-11e8-8d8b-b3c5f3780c3e.png)

**Comment by teosarca** [comment]
note to IT:
* regression: pls test the existing LU and existing TU process params. Check them in Receipt Candidates -> HU Transform and other places too

**Comment by metas-lc** [comment]
IT
1. checked the testcase above, from Picking Tray Clearing 
=> showing the existing LUs worked fast OK
=> also, only LUs were shown OK

2. opened material receipt candidates - hu editor with 100 LUs, 1 TU each. Selected a TU and selected action "TU to existing LU"
=> showing the existing LUs worked fast OK
=> also, only LUs were shown OK

3. regression: receipt schedules
CU to Existing TU - shows TUs that exists (including the one you are on) OK ??
CU to new CU - no params OK
CU to new TUs - possible new TUs OK

TU to Existing LU - shows existing LUs you can move to (not including the one you are currently on) OK
TU to new TUs - no params OK
TU to new LU - possible new LUs OK
own TU - no params OK

own LU - no params

4. regression: hu editor (more than 100 HUs)

CU to Existing TU - shows TUs (No packing Item) and LUs that exists (including the one you are on) OK ??
CU to new CU - no params OK
CU to new TUs - possible new TUs OK

TU to Existing LU - shows existing LUs/ TUs/CUs you can move to (including the one you are currently on) OK??
TU to new TUs - no params OK
TU to new LU - possible new LUs OK
own TU - no params OK

own LU - no params
