### ISSUE TITLE
Values.valueToJsonObject() shall return JSONNullValue instead of null

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#818]
### Is this a bug or feature request?
FR
### What is the current behavior?
currently, this function might return `null`.
For me that's a problem, because 
* that way `IVIewRow.getFieldNameAndJsonValues()` does not return entries for `null` row values.
* therefore, those null row values are not part of the `fieldsByName`map that is send to the frontend.
* therefore, the respective row's viewEditorRenderMode isn't sent either
* therefore, the frontend falls back to a parent value, which is - in my case - wrong

Note that my particular problem could be handles in other ways, but i think if we have that method and we have `JSONNullValue`, then let's use it to avoid returning null

**Comment by metas-ts** [comment]
cherry-picked to 2018-06

**Comment by metas-lc** [comment]
found related issue when you pick more than you ordered https://github.com/metasfresh/metasfresh-webui-api/issues/847

**Comment by metas-rc** [comment]
Nothing to IT. Moving this to Done.
