### ISSUE TITLE
Picking Terminal: Detailed Picking Issues

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#820]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
There are a few issues in Picking terminal that can be optimized. Please check proposals below.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The following issues can be optimized in Detailed Picking in Picking Terminal:
- Have a Config (see M_Picking_Config table) that decides if overdelivery is allowed in Picking or not. If not then user shall receive an error.
- In Action "Pick to new/ existing HU" the qty initially set shall be the remaining qty (qty to deliver - picked qty)
- The Packing Instructions shall be initially set to the one defined in Shipment Schedule

**Comment by metas-ts** [comment]
Hi, @metas-rc @metas-mk 
i just integrated the two PRs:
* https://github.com/metasfresh/metasfresh/pull/3531
* https://github.com/metasfresh/metasfresh-webui-api/pull/866

afaiu still todo for **that particular item**
* add field for the new M_Picking_Config column
* add a user friendly error message..afaiu right now it's a hardcoded message which the user would see

**Comment by teosarca** [comment]
note to IT: the overdelivery is prevented only for some of the processes.
We need to prevent it no matter how u do it.

**Comment by teosarca** [comment]
idea/loud thinking:
I think we shall enforce the restriction in `de.metas.handlingunits.picking.pickingCandidateCommands.ProcessPickingCandidateCommand.allocateHUToShipmentSchedule(I_M_HU)`. Mainly, have a flag for `HU2PackingItemsAllocator`.

Also please check/evaluate if we can enforce it on a lower level, like some `M_ShipmentSchedule_QtyPicked` interceptor...

**Comment by metas-rc** [comment]
> de.metas.handlingunits.picking.pickingCandidateCommands.ProcessPickingCandidateCommand.allocateHUToShipmentSchedule(I_M_HU). Mainly, have a flag for HU2PackingItemsAllocator.

**Comment by metas-rc** [comment]
> Also please check/evaluate if we can enforce it on a lower level, like some M_ShipmentSchedule_QtyPicked interceptor...

* I also did this. Please, let me know if this make the one above obsolete, or it is safer to keep them both

**Comment by metas-rc** [comment]
> the overdelivery is prevented only for some of the processes.
* I left this in the code, too. Because the prevention happens earlier and I think it's more efficient to not get to the end before throwing the error, at least for these 2 processes from the original requirements.

**Comment by metas-rc** [comment]
@teosarca Please, review when you have time and let me know if I shall change something.

**Comment by metas-lc** [comment]
IT
1. login as sysadmin and go to Picking Configuration window (540382)
=> notice new flag: Allow Overdelivery OK
=> by default is set on N

2. create/complete a new sales order, qty TU 5 (x10 cu)
3. go to picking terminal and pick: pick 6 TUs: 4 LUs with 1 TU and 1 LU with 2 TUs
=> cannot pick. Err message: Eine Überlieferung ist nicht erlaubt.  OK
4. login as sysadmin and set Allow Overdelivery on Y (see step 1)
5. login as admin, go back to picking and try to process that LU with 2 TUs
=> worked, no errors OK
6. go to shipment candidates and create inout
=> inout created fine, qty TU 6, qty 60 OK
