### ISSUE TITLE
Dropdown for packing instruction in batch entry mode

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#824]
### Is this a bug or feature request?
FR
### What is the current behavior?
If there are several packing instructions available for a product, and one is set in batch entry, you have to remove this and then start writing the name of the other packing item, so it will be displayed and selectable.
#### Which are the steps to reproduce?
1. Packing instruction must be enabled for Batch entry mode, see #745 
2. Have a product with 2 packing items set in CU-TU Allocation
3. Product and both packing items must be included in the PLV you want to use in the order
4. Create an order, and use batch entry mode:
* start writing product name: product is displayed: select it
* one of the packing items is displayed: remove it and start writing the name of the other one: the latter one is displayed
=> not very user-friendly
### What is the expected or desired behavior?
If there are >1 packing items available for a product, batch entry shall have a dropdown for those, so the user can easily select one.

**Comment by teosarca** [comment]
@metas-dh  @metas-mk @siemiatj  IMHO this is a pure frontend issue. wdyt?

**Comment by metas-dh** [comment]
Update:
works now, got a dropdown of available packing items in batch entry after pressing space bar: OK; closing this issue.
