### ISSUE TITLE
Planning status in manufacturing order not updated 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#829]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you close a manufacturing order in Swing, then the status of that order in WebUI is not updated correctly.
#### Which are the steps to reproduce?
1. Have 2 manufacturing orders
2. Close one in WebUI: planning status: completed: OK
3. Close the other one in Swing, and check in WebUI: planning status: planned: NOK
### What is the expected or desired behavior?
Planning statusin manufacturing order shall be updated correctly after changes in Swing Client.

**Comment by teosarca** [comment]
update: enabled remote cache invalidation for PP_Order. Not tested but it shall work...

**Comment by metas-lc** [comment]
IT
if you complete a manufacturing document in swing, is also updated in webui OK
but if you do receipt and and process it (or in swing you receive and close order) then the maske pos / webui won't update. I think they work different
