### ISSUE TITLE
Cache issue in shipment schedules subtab

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#846]
### Is this a bug or feature request?
bug
### What is the current behavior?
when you create a new shipment from shipment scheds you have to refresh the window to see the new entry in subtab 
#### Which are the steps to reproduce?
1. create and complete a new sales invoice
2. go to shipment schedules and open it in doc view
3. go to actions and create (and complete) shipment
=> notice that the shipment/picking subtab did not appear NOK
(you can refresh and then it will show) 
### What is the expected or desired behavior?
row shall be visible

**Comment by teosarca** [comment]
note to IT:
* reggression: check cache invalidation for C_Order/C_OrderLine and M_ShipperTransportation/M_ShippingPackage.

**Comment by teosarca** [comment]
### Configuration example

![image](https://user-images.githubusercontent.com/1244701/36148845-0fd67976-10c6-11e8-8e2d-a8076ad61e59.png)

**Comment by metas-lc** [comment]
IT
1. testcase from above works. The line is shown after the inout was done, without refreshing OK
2. regression:
check cache invalidation for C_Order/C_OrderLine 
=> i notice that if i have 2 tabs with the same order opened, and i complete it in one tab, in the second one didn't update
M_ShipperTransportation/M_ShippingPackage
=> i opened transportation order in 1 tab and picking clearing in another tab. I used "add to transportation order" and i had to refresh the page to see the new line

**Comment by teosarca** [comment]
did a quick test on my laptop and it seems to work. Pls check it again after https://github.com/metasfresh/metasfresh-webui-api/issues/851

**Comment by metas-lc** [comment]
IT
1. shipment schedule/shipment line appeared without refresh OK
2. order/orderline tabs were updated without refresh OK
3. transportation order line appeared after picking clearing without refresh OK
