### ISSUE TITLE
Sorting by Virtual Column Follow-up

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#850]
### Is this a bug or feature request?
bug
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/848
### What is the current behavior?
when you click on the header of a virtual column in webui you get an error
though sorting all other fields works fine
#### Which are the steps to reproduce?
open bill candidates and sort by "Total of Order" OK
sort by other fields NOK
=> Product Category does not work
```org.postgresql.util.PSQLException:` ERROR: column master.m_product_category_id does not exist Position: 228 SQL: INSERT INTO T_WEBUI_ViewSelection ( UUID, Line, Record_ID) SELECT ? , row_number() OVER (ORDER BY (SELECT NULLIF (TRIM(M_Product_Category.Name), '') FROM M_Product_Category WHERE M_Product_Category.M_Product_Category_ID=master.M_Product_Category_ID ) ASC NULLS LAST) , master.C_Invoice_Candidate_ID FROM T_WEBUI_ViewSelection sel LEFT OUTER JOIN C_Invoice_Candidate master ON (master.C_Invoice_Candidate_ID=sel.Record_ID) WHERE sel.UUID=? SQL params: [540092-9f2d794fb3634ceea30b22751eccf4a4, 540092-02914fc2b0054642a11324c0cc58cfb4]```
### What is the expected or desired behavior?
no errors, shall sort

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


OK:  I used the virtual column for sorting and it worked well
OK: Stress test on virtual column also worked
 
Regression: 
* OK: Sorting on a default window (e.g. Request, Sales Order, Price List etc. )  works correctly
* OK: Sorting on a view (Shipment statistics) works correctly
