### ISSUE TITLE
Virtual field from header doc shall be refreshed when one of the included row is changed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#851]
#### Which are the steps to reproduce?
Case 1:
* BPartner window
* suppose you have a virtual column called `Phone` which is showing the Phone number of the default contact
* when changing Contact's phone it shall be automatically refreshed in BPartner header

Case 2:
* BPartner window, `Credit limit Usage` field
* create/change the credit limit from `Business Partner Credit Limit` tab (last one) => it shall be automatically refreshed in header

Case X:
any case where there is a virtual column on header document which depends on some of the included rows.

### What is the expected or desired behavior?
Virtual column shall be automatically refreshed.

**Comment by metasnw** [comment]
Partial IT:
tested Case 1:
- updated phone number on subtab via advanced edit => virtual column in header is updated (worked before)
- updated phone number on subtab via grid edit => virtual column in header is updated (works now!)
- updated street of address on subtab via grid edit => virtual column in header is updated 
- updated checkbox on subtab via grid edit => header is updated

**Comment by teosarca** [comment]
@metasnw  about Case 2, pls also ask @cristinamghita  but AFAIK the credit limit is calculated async, so that's why it might that 3 seconds.

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* I had an entry in Business Partner Credit Limit tab for one partner and the Credit Limit on the Order Header was 29 %.
* I deleted the Business Partner Credit Limit  entry and waited => nothing happened
* I refreshed (F5) => nothing happened.
* I refreshed (Ctrl + Shift + R)  => Nothing happened
* I ran cache reset ,  Ctrl + Shift + R => Only now it updated to 0 %


* I added a new entry in Business Partner Credit Limit, with amt 1000
* Selected the line and ran the process  BPartner Credit Limit Approve
* Waited => Nothing happened
* F5 => Nothing Happened
* Ctrl + Shift + R => Nothing happened.
* Cache reset,  Ctrl + Shift + R => It updated to 86 %

**Comment by metas-lc** [comment]
IT
checked again, because there were changes in the area
"I deleted the Business Partner Credit Limit entry and waited " 
=> credit limit updated to 0.0%
"I added a new entry in Business Partner Credit Limit, with amt 1000. Selected the line and ran the process BPartner Credit Limit Approve" => credit limit updated
I also created a new one (first one was insurance, the second one was management which has priority). Selected the line and ran the process BPartner Credit Limit Approve => credit limit updated OK
