### ISSUE TITLE
Color Indicator Widget functionality API

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#852]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to have a color indicator Field in metasfresh, e.g. a field with a colored background or a field with content that is just a small green, yellow or red circle (nice to have).
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Provide the API side for this frontend issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1603

**Comment by teosarca** [comment]
note to IT: to be tested together with frontend task... or better, when a task which requires this task is in Testing.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


OK: As described in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1603
