### ISSUE TITLE
Automatic group creation in sales order lines

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#853]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we have the action to create sales orderline groups in webui. When creating, the user must decide which groups shall be created and how they shall be called.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The user shall be able to select all orderlines (select all button?) and then start a new action "automatic grouping". The groups are then created automatically per product >> product category >> sales group_id. The Product used in the grouping lines shall always be "Sum".

**Comment by teosarca** [comment]
Update: works as follows

* select the order lines you want to multi-group and call `Multigroup lines` action; in the example below i've selected the first 2 lines
![image](https://user-images.githubusercontent.com/1244701/36352747-6595d830-14c6-11e8-921a-7455c8ef41d3.png)

* specify the discount product you want to use and press `Start`
![image](https://user-images.githubusercontent.com/1244701/36352753-7e3ac51c-14c6-11e8-80e9-eaee3d51fa66.png)

* Result:
![image](https://user-images.githubusercontent.com/1244701/36352762-b1c965dc-14c6-11e8-9472-c1e8aca859e7.png)

### How the groups are identified
For each order line, we take a look at the product's category:
* if the product category has Parent Product Category set, we will use that one
* else we will use the product category as grouping

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

**SetUp:**

1. Create 2 products to use for compensation grouping, and add them to the customer pricelist to use in order:
* Summe
* discount
2. Create 2 compensation group schemas:
* TestGrouping, set Summe as product
* TestGrouping2, set Discount as product
3. Set compensation group schema for product category:
* Convenience Salate: TestGrouping
* Convenience Früchte: TestGrouping
* Industrie Salate: TestGrouping2
* Convenience Gemüse: none
* Gebinde: none
4. Set parent product category:
* Convenience Gemüse: Convenience Früchte
* Gebinde: none
5. Products to test with (make sure all are on the customer pricelist to use in order!):
* Convenience Salat: product category: Convenience Salate
* Frisée Industrie: Industrie Salate
* Testproduct: Industrie Salate
* Testsalat: Convenience Gemüse
* IFCO 6410: Gebinde
* Karotten gestückelt: Karotten

**Testing:**
Test I:
1. Create a sales order, add orderlines in the follwing order:
* Convenience Salat
* Testproduct
* Frisée Industrie
* Testsalat
* IFCO 6410 (as ordered product, not packing item)
2. Select all order lines, run Multigroup action: => orderlines are grouped as follows:
* Convenience Salat, Group TestGrouping
* Testsalat, Group TestGrouping
* Summe, Group TestGrouping, Group Compensation Line, Compensation Type: Discount, Compensation percentage to set
* Testproduct, Group TestGrouping2
* Frisée Industrie, Group TestGrouping2
* Discount, Group TestGrouping2, Group Compensation Line, Compensation Type: Discount, Compensation percentage to set
* IFCO 6410, no Group
=> OK
3. Set a percentage each for the compensation, check print preview:
=> percentage of discount is correct, as is overall sum, OK


Test II:
1. Create a sales order, add orderlines in the follwing order:
* Convenience Salat
* IFCO 6410 (as ordered product, not packing item)
* Testproduct
* Karotten gestückelt

2. Select all order lines, run Multigroup action: => orderlines are grouped as follows:
* Convenience Salat, Group TestGrouping
* Summe, Group TestGrouping, Group Compensation Line, Compensation Type: Discount, Compensation percentage to set
* Testproduct, Group TestGrouping2
* Discount, Group TestGrouping2, Group Compensation Line, Compensation Type: Discount, Compensation percentage to set
* IFCO 6410, no Group
* Karotten gestückelt, no Group
=> OK
