### ISSUE TITLE
If the window is missing from menu then render it's name in breadcrumb

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#854]
### Is this a bug or feature request?
FR

#### Which are the steps to reproduce?
Atm we can reproduce with `DATEV Export Format`, until Mark will add it to menu: https://w101.metasfresh.com:8443/window/540414

![image](https://user-images.githubusercontent.com/1244701/36353814-bae7fdba-14d3-11e8-88ba-4fb46fdb3827.png)

### What is the expected or desired behavior?
![image](https://user-images.githubusercontent.com/1244701/36353816-c6a3a37a-14d3-11e8-8369-711ab67e4559.png)

**Comment by metas-lc** [comment]
IT
opened window 540414 => DATEV Export Format breadcrumb is generated OK
