### ISSUE TITLE
Material Cockpit additional Filter criteria

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#857]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Material Cockpit Window https://w101.metasfresh.com:8443/window/540376 has the following filter criteria:
- Date
- Product Name
- Product key
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the following filter criteria:
- Product Category
- Purchased
- Sold

![image](https://user-images.githubusercontent.com/13365687/36374365-6270dd58-156b-11e8-812f-a1f4a908dde7.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new filter criteria in Material Cockpit: Product Category, Purchased & Sold: OK
* tested the new filter criteria, but they were not working correctly:
  * e.g. changed Purchased=N to Purchased=Y for a product, but this product was still included in the results when i filtered for Purchased=N (did cache reset and clear filter before new filtering),
  * or filter for product category=Diverse showed results from all types of categories:

![2018-02-20 12_09_22-metasfresh](https://user-images.githubusercontent.com/18696715/36421735-fd806f2e-1639-11e8-98b9-91bef8bd82fa.png)

=> NOK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

filter criteria, Purchased, Sold & Product Category:
* all work fine when running the 1st time w/o changes in product window
* when i change sth in product window, e.g. change the product category, and filter in cockpit for the old category, then this product is still included, showing the new, different category:

filtered for category Gebinde, after changing the category for Bigbag (Gebinde => Diverse):

![2018-02-21 12_03_39-metasfresh](https://user-images.githubusercontent.com/18696715/36476985-da80480c-16ff-11e8-9665-bbe958b62383.png)

**Comment by metas-ts** [comment]
hi @metas-dh @teosarca 
there was a bug regarding M_Product cache invalidation. Fixed now

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

=> changes in product window, e.g. change of product category, are now correctly considered in Material Cockpit filter results: OK, results are updated after change in product without even running the filter again: OK
