### ISSUE TITLE
Navigation Menu shown duplicated for Windows not in Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#859]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Navigation Menu shown duplicated for Windows, not in Menu
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall not be shown duplicated.
Could be a result of: https://github.com/metasfresh/metasfresh-webui-api/issues/854

![image](https://user-images.githubusercontent.com/13365687/36379520-3e4e2700-157f-11e8-8dee-b0814b9f1aed.png)

**Comment by teosarca** [comment]
note to IT: i won't be able to reproduce it with "Compensation Group Schema" window because in meantime was added to menu.

You can try with Archive window, which is not in menu: https://w101.metasfresh.com:8443/window/540176.

To find out other windows which are not in menu, you can use:
```sql
select w.AD_Window_ID, w.Name
from AD_Window w
where not exists (select 1 from AD_Menu m where m.AD_Window_ID=w.AD_Window_ID)
```

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* navigation menu shown only once for windows not in menu: OK
* checked Archive and other windows from the query above: all OK
