### ISSUE TITLE
Sometimes the error message is in German even if I am logged in with English

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#869]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
One example was described here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1584#issuecomment-367473982.

It happens in some cases because at the time the exception message is translated, the user session is no longer available so we fallback to base language (which is German atm).

### What is the expected or desired behavior?
The error shall be in user logged in language.

**Comment by metas-rc** [comment]
Results of IT


Tested on webui

The case described in the linked task is working well now.
* Login with English
* Go to Accounting Export Format ( Buchungen Export Format) 
* Advanced edit on the included tab
* OK: The error message is in english
* Change login name to German
* Advanced edit on the same included tab
* OK: The error message is now in German.
