### ISSUE TITLE
Error when selecting tabs in bpartner window

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#871]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you select the tabs in bpartner window, e.g. bank or print format, you get errors like this:

print format:

```
error
:
"Internal Server Error"
exception
:
"java.lang.IllegalArgumentException"
message
:
"detailId '11' not found for Document{tableName=C_BPartner, id=2156426, windowNo=467, writable=false, valid=Valid, validOnCheckout=Valid, saveStatus=DocumentSaveStatus{saved=true, hasChangesToBeSaved=false, error=false, reason=just loaded}, saveStatusOnCheckout=DocumentSaveStatus{saved=true, hasChangesToBeSaved=false, error=false, reason=just loaded}}"
path
:
"/rest/api/window/123/2156426/11"
status
:
500

```

=> pls note, this only happens in releasetest, not cloudit,  and only for a bpartner that was created in Swing, not for the ones created in WebUI!

#### Which are the steps to reproduce?
Try in releasetest and see (Swingfirma).
### What is the expected or desired behavior?
No errors, shall work.

**Comment by teosarca** [comment]
note to IT: not sure if I've fixed it, but at least i've made it easier to understand if it happens again.

**Comment by metas-dh** [comment]
Results of IT1
tested in weekly e2e

did not happen anymore, neither for
* bpartner created in Swing or
* bpartner changed in SetUp Wizard => OK
