### ISSUE TITLE
Don't show passwords in grid view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#872]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Passwords are shown in grid view.

#### Which are the steps to reproduce?
Any view where we have a password field displayed.
e.g. https://w101.metasfresh.com:8443/window/540397
![image](https://user-images.githubusercontent.com/1244701/36542260-04ce9200-17e9-11e8-949a-2195eec7d19b.png)

### What is the expected or desired behavior?
Instead of showing clean passwords in grid view, show just `********` (always 8 stars).
![image](https://user-images.githubusercontent.com/1244701/36542197-cb3c7dc2-17e8-11e8-9c88-abb723eb3412.png)

NOTE: this is not the complete solution about hiding passwords. It's just a small step forward.

**Comment by teosarca** [comment]
note to IT: try browsing, changing passwords. make sure documents are saved without any errors.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: When setting the password in single view, the characters are all replaced by *
* OK: in gridview, there are always 8 *s displayed instead of the password
* OK: The entries are saved correctly in the database, with the right password that I introduced
