### ISSUE TITLE
Preset Product and Qty in Process/ Action Pick CU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#876]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the user must scan all products in action Pick CU 540894.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Preset the Product and Qty in the parms of that action.

**Comment by teosarca** [comment]
the default Qty shall be QtyToDeliver - QtyPickedPlanned.
atm the default is set to selected HUs' Qty => NOK

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: When I first start the process Pick CUs for a certain picking cand line, I get the product preset (as in the line) and the qty preset as  QtyToDeliver .
* OK: After I picked a partial qty ( didn't process the picking yet)  and start the Pick CUs again, the product is still set to the product from line and the qty is preset to QtyToDeliver - QtyPickPlanned
