### ISSUE TITLE
Picking tray Clearing action: Take out and add to new/ existing HU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#877]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Picking Tray Clearing via "Take out and add to new HU" is not possible for multiple selected lines from Picking tray. Also, it is not possible to add a line to an already existing HU (already taken out of picking try).
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Please provide the following features/ adjustments:
- [ ] Allow to select multiple Product lines from Picking tray and call the action "Take out and add to new HU".
- [ ] Have a new Action "Take out and add to existing HU" that can be called when 1 or more product lines are selected in picking tray and an existing TU is selected on the right view.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. allow to select multiple Product lines from Picking tray and call the action "Take out and add to new HU": 
  * possible for multiple Product lines from the same picking tray, but not from different trays: is that wanted?
  * possible for multiple Product lines w/ different products: OK
  * different types of (top-level!) HUs can be selected on the left side: LU, TU, CU: OK
  * 1 new HU is created w/ all qty, e.g. in modal overlay  set qty CU: 10, selected were 2 product lines w/ qty: 10 each => HU is created w/ qty: 20 (2 CUs w/ qty: 10 each): OK 
  * if all qty from HU on the left is taken out to new HU on the right, old HUs are destroyed: OK
  * if the action is called for different products (w/ different UOMs), then 2 new HUs are created on the right side: is that OK?
  

2.  have a new Action "Take out and add to existing HU" that can be called when 1 or more product lines are selected in picking tray and an existing TU is selected on the right view: 
  * "Take out CUs and add to TU": possible only if selected product line is standalone CU, cannot take out CUs included in a TU or LU:  is that wanted?
  * possible for >1 product lines (from both the same and from different picking trays), but then the modal overlay is empty and you cannot set qty CU:  NOK i think:

![2018-02-27 12_11_05-metasfresh](https://user-images.githubusercontent.com/18696715/36727279-f44610c0-1bbc-11e8-8181-7bd1fbd3914b.png)

  * existing HU can contain different product / different UOM from the HU selected on the left: OK, but no UOM in the HU anymore after adding CUs: is that OK?:

![2018-02-27 13_12_44-](https://user-images.githubusercontent.com/18696715/36728213-4eee1b78-1bc0-11e8-8d75-2809e45fc3cb.png)

**Comment by teosarca** [comment]
> possible for >1 product lines (from both the same and from different picking trays), but then the modal 
> overlay is empty and you cannot set qty CU: NOK i think:

imho it's OK. because in that case i cannot ask you about Qty CU....

**Comment by metas-dh** [comment]
checked w/ metas-mk:  
* possible for >1 product lines (from both the same and from different picking trays), but then the modal overlay is empty and you cannot set qty CU: OK
* possible only if selected product line is standalone CU, cannot take out CUs included in a TU or LU: OK
* if the action is called for different products (w/ different UOMs), then 2 new HUs are created on the right side: NOK, #884
* existing HU can contain different product / different UOM from the HU selected on the left: OK, but no UOM in the HU anymore after adding CUs
