### ISSUE TITLE
Distribution Editor Move HU dropdown list HU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#878]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Handling Unit Parameter dropdown list is not filtered by the previously selected DD Orderline Product.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Filter the shown Handling Units be previously selected information (source WH, Product)

![image](https://user-images.githubusercontent.com/13365687/36656370-5b183c06-1ac8-11e8-8159-d971cec47094.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Filter the shown Handling Units by previously selected information (source WH, Product): OK 
* also only HUs with status: Active are shown, not e.g. picked o shipped ones: OK
