### ISSUE TITLE
Collapse Purchase Order dispo in Sales Order modal

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#880]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the tree in purchase order dispo modal is not collapsible. This takes a lot of space for a large amount of lines and vendors.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Make the purchase order dispo lines collapsible.

**Comment by metas-lc** [comment]
IT
follow-up https://github.com/metasfresh/metasfresh-webui-frontend/issues/1637
you can collapse but when you select an included line, it uncollapses NOK
