### ISSUE TITLE
webui: Pimp Data Import window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#882]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/879

### What is the expected or desired behavior?
pimp window 540419

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: The window was added and is respecting our layout conventions
* OK: Window is functional. I was able to import products using it.
