### ISSUE TITLE
HU Labels in WebUI

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#883]
### Is this a bug or feature request?
fr
### What is the current behavior?
there are some labels for HUs. They are defined in M_HU_Process. They are currently working only on swing. We need to make them work in webui as well
#### Which are the steps to reproduce?
open HU editor and try to print a label => action is missing
note: we might need to cover the cases where some labes are printed by default (have to check if it's a sysconfig). Found the sysconfigs: de.metas.handlingunits.MaterialReceiptLabel.*
### What is the expected or desired behavior?
shall be able to run labels on webui

**Comment by teosarca** [comment]
note to IT: regression: processes handling code was massively refactored. Pls try do regression on it.

**Comment by metas-lc** [comment]
noticed that you don't get PDFs for receipt label when you create receipts. Created follow-up https://github.com/metasfresh/metasfresh-webui-api/issues/895

**Comment by metas-lc** [comment]
IT
1. opened HU Editor with 1 LU and 5 TUs
2. run reports on LU line - i think NOK - to check
=> wareneingangsetikett 1 page
=> sscc 1 page
=> ifco 5 pages
(on swing there are 2 IFCO labels. Have to check why. One runs on 1 page, the other one on 5)
=> halbfabrikat 5 pages 
(on swing there are 2 halbfabrikat labels. Have to check why. One runs on 1 page, the other one on 5)

3. run reports on TU line - i think NOK - to check
=> wareneingangsetikett 5 pages
=> sscc -
(on swing we have it and it's an empty page NOK)
=> ifco 5 pages
(on swing there are 2 IFCO labels. Have to check why. One doesn't run, the other one on 5)
=> halbfabrikat 5 pages
(on swing there are 2 halbfabrikat labels. Have to check why. One doesn't run, the other one on 5)

4. run other kind of jaspers OK
=> document types: e.g. c_order: works, in both swing and webui
=> process in menu: e.g. open items: works, in both swing and webui
=> process in window: e.g. pricelist comparison in bpartner: works, in both swing and webui
=> for autoprinting ones we have followup: https://github.com/metasfresh/metasfresh-webui-api/issues/895

5. No jasper processes:
=> document related: create inouts/invoices (both sales and purchase side)

**Comment by teosarca** [comment]
note to IT: pls do regression for https://github.com/metasfresh/metasfresh-webui-api/issues/209

**Comment by metas-dh** [comment]
weekly e2e:

i set qty: 2 when printing e.g. IFCO label, but only got 1: NOK

**Comment by metas-lc** [comment]
checked @metas-dh case: "i set qty: 2 when printing e.g. IFCO label, but only got 1: NOK"
happens on both swing and webui NOK

checked the rest of the labels: 
=> wareneingangsetikett 1 page on LU , 5 on TU
=> sscc 1 page
=> ifco 5 pages (need to check if it should be 1 or 5 on LU)
=> halbfabrikat 5 pages  (need to check if it should be 1 or 5 on LU)
on both webui and swing OK
also checked in webui, on dropdown, which process is called. The ID was the correct one, accordingly to the ones in Handling Unit Process Window in sysadmin OK
