### ISSUE TITLE
Field Readonly = 'Y' but still updateable in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#886]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it seems for some cases not possible to make Fields read-only (e.g. BusinessPartner Value, DocumentNo ...) in WebUI.
#### Which are the steps to reproduce?
Prepared a case on w101 for Businesspartner Value. Set Field to readonly = 'Y'. Column is only updateable = 'Y'.
### What is the expected or desired behavior?
Shall be readonly.

**Comment by teosarca** [comment]
### Update
There was a hardcoded rule which always made Value and DocumentNo fields editable.
I've took it out, so now, regular field settings are respected, same as for other fields.


### note to IT:
For regression check other windows where we have Value or DocumentNo fields (e.g. product, product category, bp, bp group, documents like order, invoice, shipment, payment etc).
When creating a new record, make sure the Value/DocumentNo is preset, or if it's not, at least the field shall be editable. Else, we would not be able to create new records in that window.

**Comment by metas-lc** [comment]
IT
1. login as sysadmin and make bpartner.value field readonly (put it back on N after IT)
2. (cache reset if you did that from swing)
3. go to bpartner window 
=> value is readonly OK
4. create a new bpartner, save
=> value is set by default, bp is saved OK
5. create purchase and sales orders/invoices
=> documentNos are editable and the documents are saved, so even where you don't have generated docno is ok
6. check other documents/windows like manufacutring, product and so on 
=> all saved OK
