### ISSUE TITLE
New Composed Primary Keys

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#894]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it's not possible to show Translation data in WebUI, because a primary key is missing. Creating a default primary key is not an option because of system independent updates of Translations.
#### Which are the steps to reproduce?
See new Window  https://w101.metasfresh.com:8443/window/540420
### What is the expected or desired behavior?
It shall be possible to have a new composed primary key.

**Comment by teosarca** [comment]
note to IT: it needs full regression (e2e) on webui!

**Comment by metas-rc** [comment]
I found a bug and I think it's related with this task

* have a top level CU (e.g. by transforming a CU into a new CU)
* Go to the cu, Transform, CU to new CU
* set a qty
* Done
* => NOK: I get this error: 
```
Error: Invalid composed key: [SqlViewRowFieldBinding(fieldName=M_HU_ID,...
Server error
Invalid composed key: [SqlViewRowFieldBinding(fieldName=M_HU_ID, columnName=M_HU_ID, columnSql=M_HU_ID, keyColumn=true, widgetType=Integer, virtualColumn=false, sqlValueClass=class java.lang.Integer, sqlSelectValue=M_HU.M_HU_ID AS M_HU_ID, sqlSelectDisplayValue=org.adempiere.ad.expression.api.NullStringExpression@72b11ae8, usingDisplayColumn=false, sqlOrderBy=M_HU_ID, fieldLoader=SqlViewFactory.DocumentFieldValueLoaderAsSqlViewRowFieldLoader(fieldValueLoader=DocumentFieldValueLoaders.IntegerDocumentFieldValueLoader(sqlColumnName=M_HU_ID, encrypted=false), isDisplayColumnAvailable=false))]
```


* Here is the full stacktrace from the log: https://pastebin.com/Qk7qN8wT

**Comment by metas-dh** [comment]
got a similar error when using "Take out HU" in Picking Tray Clearing:

```
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"Invalid composed key: [SqlViewRowFieldBinding(fieldName=M_HU_ID, columnName=M_HU_ID, columnSql=M_HU_ID, keyColumn=true, widgetType=Integer, virtualColumn=false, sqlValueClass=class java.lang.Integer, sqlSelectValue=M_HU.M_HU_ID AS M_HU_ID, sqlSelectDisplayValue=org.adempiere.ad.expression.api.NullStringExpression@1bab4a38, usingDisplayColumn=false, sqlOrderBy=M_HU_ID, fieldLoader=SqlViewFactory.DocumentFieldValueLoaderAsSqlViewRowFieldLoader(fieldValueLoader=DocumentFieldValueLoaders.IntegerDocumentFieldValueLoader(sqlColumnName=M_HU_ID, encrypted=false), isDisplayColumnAvailable=false))]"
path
:
"/rest/api/process/ADP_540874/1000807/start"
status
:
500
```

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-dh** [comment]
Results of IT
tested in e2e, release

* the 2 problems described above work fine again: OK
* had no other problems related to composed keys in last e2e: OK

imho we can close this one, @teosarca wdyt?
