### ISSUE TITLE
Automatic printing HU Labels in WebUI

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#895]
### Is this a bug or feature request?
fr
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/883
### What is the current behavior?
we have some sysconfigs to automatically run a label when you create inouts. See de.metas.handlingunits.MaterialReceiptLabel.*
currently works only in swing
#### Which are the steps to reproduce?
1. go to receipt candidates, select a line, receive some hus
2. create receipt
=> receipt label shall be printed
### What is the expected or desired behavior?
besides receipt label, we need Picking TU Label (Jasper) process to start when we do picking: pick to new HU

**Comment by metas-rc** [comment]
Note: The receipt label is automatically printed, but we can't see  it from webui. A way to notify this on wbeui was not yet implemented. I created a followup: https://github.com/metasfresh/metasfresh-webui-api/issues/903

**Comment by metas-rc** [comment]
Sys configs for picking label ( done on the model of the Receipt Label) :
![image](https://user-images.githubusercontent.com/16001442/37462481-bd56cc44-285a-11e8-82ac-9d6c6382df3c.png)

**Comment by metas-rc** [comment]
Note to IT

You will not be notified in webui if the printing worked or why did it fail. The followup for it is: #903
But the followup is not extra urgent, like this task is. SO please, when testing, Ask @metas-ts  to help with a printing client.

**Comment by metas-dh** [comment]
Results of IT
tested in mf15

tested in https://github.com/metasfresh/metasfresh/issues/3767:
* set up PDF as printer
* created material receipt, and picked to new HU in picking terminal (=> Picking TU Label shall be printed for those automatically)
* checked printing queue: new entries for the material receipt and the picking TU label: OK
* checked the PDFs: OK
