### ISSUE TITLE
Provide media size info for columns

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#901]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, on mobile devices, there are shown as many columns as on desktop size application.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Provide the information to frontend which columns shalöl be shown in which media sizes.

Belongs to https://github.com/metasfresh/metasfresh-webui-frontend/issues/1673

**Comment by teosarca** [comment]
### How to configure for regular windows?
![image](https://user-images.githubusercontent.com/1244701/37460672-97881eb0-2854-11e8-8461-ef39045493b2.png)

**Comment by teosarca** [comment]
As a result, on view layout endpoint, the element will have the `restrictToMediaTypes` property set.
Based on that property, the frontend shall decide if that column will be displayed or not.
e.g.
![image](https://user-images.githubusercontent.com/1244701/37460810-10009cf0-2855-11e8-9e20-bf37b957ded7.png)

**Comment by teosarca** [comment]
Following columns shall be displayed only on PC screen (not on Tablet nor on Phone)

Picking
---------------------------------
Pickig slots (right side)
* packing instructions

HUsToPick (right side): 
* Code
* HU Type
* packing instructions
* HU Status


Picking Clearing
------------------------------------
Picking Slots (left side): 
* packing instructions


HUs picked (right side): 
(this one it's using the general HU editor layout)
* packing instructions



Material receipt -> HU Editor: 
------------------------------------
* code
* HU Type
* packing instructions
* HU status


HU Editor (general): 
------------------------------------
* HU Type
* packing instructions

**Comment by metas-dh** [comment]
Results of IT1
tested  in mf15 / w101

1. these columns are not displayed on tablet: 

Picking
---------------------------------
Pickig slots (right side)
* packing instructions: OK

HUsToPick (right side): 
* Code: OK
* HU Type: OK
* packing instructions: OK
* HU Status: OK


Picking Clearing
------------------------------------
Picking Slots (left side): 
* packing instructions: OK


HUs picked (right side): 
(this one it's using the general HU editor layout)
* packing instructions: OK



Material receipt -> HU Editor: 
------------------------------------
* code: OK
* HU Type: OK
* packing instructions: OK
* HU status: OK


HU Editor (general): 
------------------------------------
* HU Type: OK
* packing instructions: OK


2.  shows all those columns are displayed on PC screen, all columns have restrictToMediaTypes: ["screen"]: OK (mf15)
