### ISSUE TITLE
API token is not shown in the webui

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#902]
### Is this a bug or feature request?
Bug
### What is the current behavior?

Go to the users window and create a new auth-token
![image](https://user-images.githubusercontent.com/1264789/37449278-f86d37c2-2829-11e8-9bda-9d003b92a0a9.png)

As a user, i need to copy that token to my local application, so i need to *see* it..

**Comment by metas-lc** [comment]
IT
1. open Uesr window
2. go to Authentication Tokens Tab
3. create a new one
=> Authentication Token field is there, readonly OK
=> trls are missing: https://github.com/metasfresh/metasfresh/issues/4215
