### ISSUE TITLE
KPIs in RC showing error

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#905]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The KPIs in the current RC show only "Error loading data..."
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
KPIs shall be displayed.

**Comment by metas-ts** [comment]
duplicate of https://github.com/metasfresh/metasfresh/issues/3671
