### ISSUE TITLE
2nd orderline for product missing in picking terminal

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#910]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you have 2 orderlines for the same product (also happens with different products), one of them is missing in picking terminal.
#### Which are the steps to reproduce?
1. Create a sales order
2. Add 2 orderlines for the same product, e.g. Convenience Salat, 1 w/ 2 TUs and 1 w/ 5 TUs
3. Complete and check picking terminal:
=> only 1 orderline is shown in the dropdown in 1st window: NOK
4. Select the line and press Pick:
=> only 1 orderline is shown in the modal window, on the left: NOK
### What is the expected or desired behavior?
Both orderlines shall be displayed correctly.

**Comment by metas-mk** [comment]
Only the product of the first Sales Orderline is shown in Picking Terminal.

**Comment by teosarca** [comment]
issue was introduced by https://github.com/metasfresh/metasfresh-webui-api/issues/894

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

2nd orderline for product not missing in picking terminal:
* 2nd orderline is correctly shown in picking terminal: OK
* if 1st and 2nd orderline have the same product, then in 1st picking terminal window the qties are correctly summed up in header, and each orderline with its qty is shown in indent: OK
* 2nd picking terminal window shows both orderlines, same order as in sales order: OK
* picking for both orderlines into same or different slot working as before: OK
