### ISSUE TITLE
HU attributes shall consider M_HU_PI_Attribute.IsDisplayedUI flag

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#911]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* untick the HU PI attribute's IsDisplayed flag
* in webui -> receipt candidates -> HU editor, the attribute shall not be displayed
![image](https://user-images.githubusercontent.com/1244701/37647038-fa25cd32-2c33-11e8-9631-a98429f940d4.png)
![image](https://user-images.githubusercontent.com/1244701/37647116-27e3f974-2c34-11e8-841f-e9b1bb020781.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. set M_HU_PI_Attribute.IsDisplayedUI flag for HU attribute: Label ='N', for HU_PI: IFCO 6410, check material receipt candidates:
* standalone TU IFCO 6410: attribute Label displayed: false, OK
* aggregated TU IFCO 6410: attribute Label displayed: false, OK
* LU with aggregated TU IFCO 6410: attribute Label displayed: true, OK
* CU included in TU IFCO 6410: attribute Label displayed: true, OK
* TU G1: attribute Label displayed: true, OK

2. set M_HU_PI_Attribute.IsDisplayedUI flag for HU attribute: Label ='Y', for HU_PI: IFCO 6410, check material receipt candidates again:
=> Label displayed for TU IFCO 6410 again, OK
