### ISSUE TITLE
Allow to display only positive ATP values in product lookup

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api#919]
### Is this a bug or feature request?
FR
### What is the current behavior?
Currently, whenever ATP is queries and the result is displayed in the product lookup, also zero and negative values are shown

### What is the expected or desired behavior?

We need a switch to allow us to just show positive values.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* set all sysconfigs about product lookup=Y, and had ATP in material dispo
=> no qty displayed in product lookup though: checked w/ metas-ts: ATP & material dispo still has bugs, so will keep this one assigned for now

**Comment by metas-dh** [comment]
Update:
* only positive qty in ATP batch entry, when config set accordingly: OK
* all qty in ATP batch entry, when config set accordingly: OK

=> ATP & material dispo still has some bugs, but we have newer tasks for those, so i'm closing this one.
