### ISSUE TITLE
Contact is not set when order is cloned

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#946]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The partner & invoice contact is not set when an order is cloned.
#### Which are the steps to reproduce?
Case No. 1
1. Create e.g. a sales order, set the contact in bpartner field and invoice partner field
2. Clone the order => contact in the new order is empty, in both partner and invoice partner field: NOK

~Case No. 2~
~1. Create new sales order~
~2. create a new partner WITH a contact using~
~http://docs.metasfresh.org/webui_collection/EN/Quick_create_new_business_partner.html~
~NOK: the sales order does contain the partner but the contacts fields are empty~
See [#4078 AD_User_ID/Bill_User_ID not set in Sales Order when using Quick creation of partner](https://github.com/metasfresh/metasfresh/issues/4078)

### What is the expected or desired behavior?
Contact shall be cloned as well.

**Comment by cristinamghita** [comment]
Wrong place
see [#4079 Contact is not set when order is cloned](https://github.com/metasfresh/metasfresh/issues/4079)
