### ISSUE TITLE
Shorten the ViewIds

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#952]
### Is this a bug or feature request?
FR

### What is the current behavior?
At the moment the view IDs are quite long.
e.g.
https://w101.metasfresh.com:8443/window/143?viewId=143-fabc5efc43f1455383018f340a29c428&page=1

### What is the expected or desired behavior?
Have something much more shorter, e.g. https://w101.metasfresh.com:8443/window/143?viewId=143-A7jQ&page=1

**Comment by metas-lc** [comment]
IT 
checked view IDs => they have short version now. E.g. window/540196?viewId=540196-C8&page=1
