### ISSUE TITLE
Allow configuring lookup cache reset on table record changes

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#954]
### Is this a bug or feature request?
FR

### What is the current behavior?
At the moment there is no way to invalidate the lookup's cache when a record on which that lookup is depending was changed.

### What is the expected or desired behavior?
Have a way to specify on which tables a given validation rule is depending.
When a record from that table is changed all lookups which are using that validation rule will be cache invalidated.

![image](https://user-images.githubusercontent.com/1244701/39400676-df1fed0a-4b3d-11e8-83eb-be9622765223.png)

**Comment by teosarca** [comment]
note to IT: ask @metasnw  or let him test it

**Comment by metasnw** [comment]
IT OK
