### ISSUE TITLE
NPE when opening Manufacturing Issue/Receipt

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#959]
### Is this a bug or feature request?
bug
thanks @siemiatj for catching it.

### What is the current behavior?
Got NPE error when opening Issue/Receipt for some manufacturing orders.

#### Which are the steps to reproduce?
Have a manufacturing order you have already issued completely some HUs. So, those HUs are now empty.
Try to open the Issue/Receipt modal again. An NPE error about qty is thrown.

e.g. on w101, try with manufacturing order 630019.
![image](https://user-images.githubusercontent.com/1244701/39581049-60ccc022-4ef3-11e8-9c07-43a17ce8352d.png)

### What is the expected or desired behavior?
Shall work :)

**Comment by metas-lc** [comment]
IT
1. create a new manufacturing order, complete
2. press on issue/receipt (while in gridview)
=> modal opens, no errors
3. close it and open it again
=> no errors 
4. issue an HU (Issue complete HU)
5. close the modal and open it again 
=> no errors
6. issue included TUs, close modal and open it again
=> no errors
7. receive LU+TU, close, open again
=> no errors
8. receive TU, close, open again
=> no errors
9. receive CU, close, open again
=> no errors
10. process, close, open again
=> no errors
OK
