### ISSUE TITLE
DocStatus missing in Transportation order

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-api#990]
### Is this a bug or feature request?
bug
### What is the current behavior?
currently we see an empty button instead of draft in Transportation order, when you e.g. create a new one
#### Which are the steps to reproduce?
1. go to transportation order window ( 540020), create a new one
=> notice draft button
![image](https://user-images.githubusercontent.com/16001666/41714568-61368714-7559-11e8-92b5-57c5b0ed359d.png)
2. check network: 
=> the field is missing

### What is the expected or desired behavior?
please add DocStatus in transportation order

**Comment by metas-dh** [comment]
checked in latest e2e:
DocStatus is correcly included in Transportation Order: OK
